### ISSUE TITLE
Mission Hold Position

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#10]
When I send a mission to Hold position the error.
Included in this task and other tasks, the process failed to recall the fleet.
I try the ACS system, I could not

Fatal error: Call to undefined method Stay::stayMission() in /home/eskiog/public_html/beta6/application/libraries/MissionControlLib.php on line 128

Warning: Invalid callback Sessions::write, cannot access private method Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

Warning: Invalid callback Sessions::close, cannot access private method Sessions::close() in Unknown on line 0

**Comment by XGProyect** [comment]
Fixed
