### ISSUE TITLE
[Beta11] Error in Admin/home.php

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#100]
this error notice Notice: Trying to get property of non-object in C:\xampp\htdocs\NewGalaxy\application\controllers\adm\home.php on line 142 close this theme its for xgp update..

**Comment by BeReal86** [comment]
Hello,
This bug has been verified. Thanks for your feedback.

**Comment by XGProyect** [comment]
This issue has been fixed on GitHub before this ticket.
