### ISSUE TITLE
[Beta11] lunar do not add fields

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#102]
When editing the moon and the lunar base have not sum points fields.. (will a bug or not)
![sin titulo](https://cloud.githubusercontent.com/assets/2124810/14694909/66415a12-0743-11e6-8941-5efac86a1c68.png)
![sin titulo](https://cloud.githubusercontent.com/assets/2124810/14694930/971a8000-0743-11e6-9eb5-b5cf00f66482.png)

**Comment by BeReal86** [comment]
Thank you for your feedback.

has been tested. an a bug. 
In normal operation.; 1 stage base = 1/4
2 stage base = 2/7
15 stage base = 15/45 
(only lunar base in this calculation are available)
