### ISSUE TITLE
[Beta11] Bug in Stats

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#103]
Select the option for administrators appear and made a update to the database do not appear to me points.
![sin titulo](https://cloud.githubusercontent.com/assets/2124810/14694979/0f9228c6-0744-11e6-85cf-1ae632e01174.png)
![sin titulo](https://cloud.githubusercontent.com/assets/2124810/14695000/22f6ecda-0744-11e6-9a4c-4a510741e485.png)
the three accounts are edited

**Comment by BeReal86** [comment]
Thank you for your feedback.

yes, this problem is tested and approved. There were errors in the previous notification. The problem continues. AdminCP added units are not reflected in the statistics list of points.

**Comment by XGProyect** [comment]
I can't reproduce this bug. I have disable the statistics and set it just for players, then I start playing and doing stuff, then I reactivate the statistics and my points were updated. Image attached as proof.
<img width="548" alt="screen shot 2016-04-22 at 11 40 34" src="https://cloud.githubusercontent.com/assets/3051274/14744913/281a30c8-087f-11e6-9b75-e861fd32345d.png">

**Comment by BeReal86** [comment]
yes, no problem you raise levels of normally enter the building. ranking and scoring normally. But units AdminCP 'is also added which can not be included in the scoring.

![aaaaa](https://cloud.githubusercontent.com/assets/16218107/14749141/795afc46-08c6-11e6-95cb-dcbf66888153.png)

**Comment by XGProyect** [comment]
Ok, got it.
