### ISSUE TITLE
Error on Message System

### ISSUE THREAD

**Issue by Reigen1991** [XGProyect/XG-Proyect-v3.x.x#105]
When clicking on the Message Icon to write message to player following error occures:

Fatal error: Class 'application\controllers\game\FormatLib' not found in /home/www/web59/html/testgalaxy/application/controllers/game/messages.php on line 202

Warning: Invalid callback application\core\Sessions::write, cannot access private method application\core\Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct () in Unknown on line 0

Warning: Invalid callback application\core\Sessions::close, cannot access private method application\core\Sessions::close() in Unknown on line 0

**Comment by BeReal86** [comment]
Hello, Thank you for your feedback.

The error was confirmed.
