### ISSUE TITLE
Pagina Alianza

### ISSUE THREAD

**Issue by djlolito** [XGProyect/XG-Proyect-v3.x.x#107]
El rango por defecto de las alianzas es Líder, he editado solo el texto externo nada mas, al darle a guardar se convierte a L&iacute;der

**Comment by XGProyect** [comment]
@djlolito no entiendo bien que es el problema que tienes. Podrías describirlo mejor?

**Comment by djlolito** [comment]
Si perdona veo que github corrigió el texto...  El rango líder sin tocarlo ni nada... Edito la alianza y le doy a guardar y en vez de salir lìder sale l(símbolo)der. Si puedo subo una captura más tarde
