### ISSUE TITLE
Al registrarse no llega email

### ISSUE THREAD

**Issue by djlolito** [XGProyect/XG-Proyect-v3.x.x#109]
Lo dicho, cuando se registra un usuario nuevo no le llega el email. No da error ni nada simplemente registra bien pero no llega el mail

**Comment by FGServers** [comment]
por que xgp no tiene un sistema de integracion de emails voy a ver si puedo adaptar phpmailer a xg pero seria bueno que se integre pcomo el antiguo ogame que tenia integrado
