### ISSUE TITLE
Mission Transport

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#11]
Fatal error: Call to undefined method Transport::transportMission() in /home/eskiog/public_html/beta6/application/libraries/MissionControlLib.php on line 128

Warning: Invalid callback Sessions::write, cannot access private method Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

Warning: Invalid callback Sessions::close, cannot access private method Sessions::close() in Unknown on line 0

**Comment by XGProyect** [comment]
Fixed
