### ISSUE TITLE
[3.0 RC] Global Email Error

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#110]
Warning: mail(): "sendmail_from" not set in php.ini or custom "From:" header missing in C:\xampp\htdocs\xgp\application\controllers\adm\globalmessage.php on line 107

Warning: mail(): "sendmail_from" not set in php.ini or custom "From:" header missing in C:\xampp\htdocs\xgp\application\controllers\adm\globalmessage.php on line 107

Warning: mail(): "sendmail_from" not set in php.ini or custom "From:" header missing in C:\xampp\htdocs\xgp\application\controllers\adm\globalmessage.php on line 107

**Comment by FGServers** [comment]
si es un error comun  se deberia integrarle phpmailer a xg
