### ISSUE TITLE
[3.0 RC] Bug in Defense

### ISSUE THREAD

**Issue by spinal25** [XGProyect/XG-Proyect-v3.x.x#112]
cannons creates on their own ( creates themselves )

**Comment by BeReal86** [comment]
Hello, please tell us more descriptive way.

**Comment by XGProyect** [comment]
Hey @spinal25 , can you please elaborate a little bit more?

**Comment by spinal25** [comment]
I didn't build nothing but i have all defense value are "1" on new colony and mother planet
I build variety of cannons and they reset to value "1" sometimes

Sorry for my English, it's not my mother tounge.

**Comment by XGProyect** [comment]
@spinal25 ok, I'll investigate this issue. Have you add stuff from the admin panel?

**Comment by spinal25** [comment]
Yes I added One User, ships, buildings and defences

**Comment by XGProyect** [comment]
@spinal25 Ok, I'll close the ticket, and you can reopen it if the issue reappears.

**Comment by spinal25** [comment]
Can you reopen this issue ?? I found  when it come

**Comment by spinal25** [comment]
I found this bug at length, please reopen ticket

When i send mission "attack" defense is gone crazy for all users
with each attack so happens
defense itself creates 

I think this error is probably related to the battle engine 

I can share login and password for you if necessary
My game works on Raspberry Pi3 PHP  5.6.20 and SQL 5.5
