### ISSUE TITLE
Error join alliance url

### ISSUE THREAD

**Issue by mascotte88** [XGProyect/XG-Proyect-v3.x.x#113]
information alliance, clic join alliance 

url : page=alliance&mode=apply&allyid= <== ?? ID unkown

**Comment by BeReal86** [comment]
I have never encountered such a problem doing trials. 

There is no error

![a](https://cloud.githubusercontent.com/assets/16218107/15194435/8ee71cd4-17cb-11e6-876b-89bc5e9a3c23.png)

**Comment by mascotte88** [comment]
Search is OK.  
Clic page statistics.  Id unkown

**Comment by mascotte88** [comment]
Test this page: /game.php?page=alliance&mode=ainfo&allyid=1

**Comment by BeReal86** [comment]
problems have been identified. Thanks for your feedback
