### ISSUE TITLE
Small cargo speed Upgrade (v3.0.0RC)

### ISSUE THREAD

**Issue by eX-Arkangel** [XGProyect/XG-Proyect-v3.x.x#116]
when you reach impulse drive level 5, it updates its base speed to 10.000 but keeps  using the 5.000 original base speed to add the upgraded levels of the drive, so instead of getting 20.000 speed as it should (or basically the same speed as the heavy fighter) with impulse level 5, it only gets 15.000

**Comment by BeReal86** [comment]
Thanks for your feedback.

necessary checks were done and confirmed.

**Comment by XGProyect** [comment]
@eX-Arkangel I think you made a mistake.
Base speed 1: 5000
Base speed 2: 10000 (Impulse Drive >=5)
**Impulse Drive multiplier is 20%**

**Formula without Impulse drive will be:**
base speed + (base speed * combustion drive level * 0.1)
**Ex.:** 5000 + (5000 * 5 * 0.1) = 7500 final speed

**Formula with Impulse drive will be:**
base speed 2 + (base speed * impulse drive level * 0.2)
**Ex.:** 10000 + (5000 * 5 * 0.2) = 15000 final speed

Reference: http://ogame.wikia.com/wiki/Base_Speed

**Comment by BeReal86** [comment]
yes, as a reference site and bought it originally OGame base.

![sc](https://cloud.githubusercontent.com/assets/16218107/15379738/d25916a4-1d78-11e6-98fa-79b132a2576e.png)

**Ex.**: 10000 + (5000 * 5 * 0.4) = 20000 final speed

According to that picture of my techniques 9
**Ex.**: 10000 + (5000 * 9 * 0.4) = 28000 final speed

**Comment by XGProyect** [comment]
Ok, I found the problem, Applying 0.4 doesn't works, because we have to use the base speed 2 in the formula too like this:

Formula without Impulse drive will be:
base speed + (base speed * combustion drive level * 0.1)
Ex.: 5000 + (5000 * 5 * 0.1) = 7500 final speed

Formula with Impulse drive will be:
base speed 2 + (base speed 2 * impulse drive level * 0.2)
Ex.: 10000 + (10000 * 5 * 0.2) = 20000 final speed

**Comment by BeReal86** [comment]
Yeah, well that's great. congratulations :)

**Comment by XGProyect** [comment]
Ok, I'm sending the fix now, this issue was happening also for the bomber and recycler.
