### ISSUE TITLE
Colonizers return after colinizing a planet (v3.0.0RC)

### ISSUE THREAD

**Issue by eX-Arkangel** [XGProyect/XG-Proyect-v3.x.x#117]
Some times the colonizers return (almost always) even after colonizing a new planet and very few times they disappear after a successful colonization

**Comment by BeReal86** [comment]
Thanks for your feedback.

In some experiments we did, but we did not encounter this problem. If you can control the astrophysical techniques better. perhaps it reached the maximum number of colonies.
