### ISSUE TITLE
Master (3.0.1) ShortCuts in Fleet

### ISSUE THREAD

**Issue by bornhaeusser** [XGProyect/XG-Proyect-v3.x.x#118]
Hi,

i ve got a Problem with the Fleet Shortcut Pages. If i go to add / edit i got this:

<img width="1002" alt="bildschirmfoto 2016-05-19 um 19 32 15" src="https://cloud.githubusercontent.com/assets/6609040/15403277/74889038-1df8-11e6-9d4d-1053d8b8403e.png">

**Comment by BeReal86** [comment]
Hello, Thank you for your feedback.

The error was confirmed.

**Comment by FGServers** [comment]
MiniFix : Add before this 

`$this->_current_user = parent::$users->getUserData();`

This 
`$this->_lang = parent::$lang;`

**Comment by XGProyect** [comment]
@FGServers Un pull request hubiera estado bueno 😄
