### ISSUE TITLE
Messages issue

### ISSUE THREAD

**Issue by bornhaeusser** [XGProyect/XG-Proyect-v3.x.x#119]
Select one box (Addressbook) click on ok - nothing happens. Also in Notes if i wrote one.

<img width="947" alt="bildschirmfoto 2016-05-19 um 21 06 32" src="https://cloud.githubusercontent.com/assets/6609040/15406206/bd013286-1e05-11e6-814b-faa396dfc529.png">

**Comment by BeReal86** [comment]
Thank you for your feedback.
Posts in trial work I've done in the game. address book and notes section is passive
 There are currently not working.
![messages](https://cloud.githubusercontent.com/assets/16218107/15406739/5eca4dfa-1e10-11e6-925b-d7f9af3c785a.png)

**Comment by bornhaeusser** [comment]
the others works. (like in your pictures)
