### ISSUE TITLE
Administration Alliance Tag empty

### ISSUE THREAD

**Issue by bornhaeusser** [XGProyect/XG-Proyect-v3.x.x#120]
In adminmenue the Tag is empty - also if i update the Tag in Adminmenue it is empty in the game

<img width="609" alt="bildschirmfoto 2016-05-19 um 21 13 08" src="https://cloud.githubusercontent.com/assets/6609040/15406378/8cc059de-1e06-11e6-8a97-a3347ae0f0d9.png">
<img width="782" alt="bildschirmfoto 2016-05-19 um 21 13 24" src="https://cloud.githubusercontent.com/assets/6609040/15406380/8e3bda68-1e06-11e6-91f4-5bc7c7701499.png">

**Comment by BeReal86** [comment]
Hello, Thank you for your feedback.

The error was confirmed.

**Comment by FGServers** [comment]
Try this go to upload/application/views/adm/alliances_information_view.php search this line
`<td><input type="text" name="ally_tag" value="{ally_tag}"></td>`

chage for this
`<td><input type="text" name="alliance_tag" value="{alliance_tag}"></td>`

**Comment by bornhaeusser** [comment]
works!!

**Comment by FGServers** [comment]
Ok thank yous for this feedback bug it's confirmed.

**Comment by XGProyect** [comment]
@bornhaeusser & @FGServers please check this commit https://github.com/XGProyect/XG-Proyect-v3.x.x/commit/1adc3ee8dbf79ca66454a46c62d96f4ac41ef429, it contains other related fixes.
