### ISSUE TITLE
Alliance Page - SWITCH Button

### ISSUE THREAD

**Issue by bornhaeusser** [XGProyect/XG-Proyect-v3.x.x#121]
The Switch Name / Tag pictures are not quite useful - i do not now wich is for what....

<img width="934" alt="bildschirmfoto 2016-05-19 um 21 25 34" src="https://cloud.githubusercontent.com/assets/6609040/15406844/680ecd08-1e08-11e6-9260-d0a04e983597.png">

**Comment by FGServers** [comment]
These are from the old switch ogame are to change the name and tag of the alliance

**Comment by XGProyect** [comment]
For now, we keep the classic ogame design.
