### ISSUE TITLE
[XGP 3.0.1 RC] Error notice in fleetshorcut and fix this

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#122]
Lucky I leave the solution for error notice in the fleetshorcut.php

![sin titulo](https://cloud.githubusercontent.com/assets/2124810/15414054/2e76359a-1e0d-11e6-9e63-4fb8cdd4fcea.png)

Mini fix: $ShortcutsRowTPL = parent::$page->getTemplate("shortcuts/shortcuts_row"); before add $parse['block_rows'] = '';

**Comment by XGProyect** [comment]
@FGServers thanks! pls pull request la próxima.
