### ISSUE TITLE
[XGP 3.0.1 RC] Error notice in fleet2 and fix this (from shorcuts)

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#123]
Error notice in fleet2 from select shorcut
![2](https://cloud.githubusercontent.com/assets/2124810/15414194/7fc52180-1e0e-11e6-9229-225fee8ecd3e.png)

After `$parse['p'] = $p;` add this `$shortcut['shortcut_options'] = '';`

**Comment by XGProyect** [comment]
@FGServers thanks!
