### ISSUE TITLE
Time in Messages

### ISSUE THREAD

**Issue by bornhaeusser** [XGProyect/XG-Proyect-v3.x.x#125]
The Time is not shown 24h. I see also not if am or pm.

The Time in the Message is 18:36 and 19:56

<img width="583" alt="bildschirmfoto 2016-05-20 um 19 57 58" src="https://cloud.githubusercontent.com/assets/6609040/15437068/53f6fb02-1ec5-11e6-9bf8-89fee6dd5722.png">

**Comment by XGProyect** [comment]
@bornhaeusser That depends on your configuration, you can change it from the admin cp

**Comment by bornhaeusser** [comment]
On other Pages the time shows 24h

**Comment by bornhaeusser** [comment]
It is hard Coded in messages.php Line 374

It should look like:

<            $message['message_time']    = date('m-d H:i:s', $message['message_time']);     >

**Comment by XGProyect** [comment]
Ok, thanks I'll look into that.
