### ISSUE TITLE
Premium Commander

### ISSUE THREAD

**Issue by bornhaeusser** [XGProyect/XG-Proyect-v3.x.x#126]
The Premium Commander has no benefit for building queue.

Can build 5 Buildings in the queue with and without commander active.

**Comment by BeReal86** [comment]
Thank you feedback

in later times as it is written in the road map is already an update will be made.

**Comment by bornhaeusser** [comment]
Ok - sounds good. 
I hope i do not post to much here..... let me know if its too much. Thanks

**Comment by XGProyect** [comment]
@bornhaeusser don't worry. We like that people share and contribute 😉
