### ISSUE TITLE
Colors in Overview during Attack

### ISSUE THREAD

**Issue by bornhaeusser** [XGProyect/XG-Proyect-v3.x.x#127]
The Colors of the Planets are Different - Think it would be better if they are all grey or maybee red.

<img width="524" alt="bildschirmfoto 2016-05-20 um 22 44 30" src="https://cloud.githubusercontent.com/assets/6609040/15441695/a948ea04-1edc-11e6-9c03-b9a36f879373.png">

**Comment by BeReal86** [comment]
we 're actually trying to simulate the original ogame :)

**Comment by bornhaeusser** [comment]
i did not played it.... shame on me ;)

**Comment by FGServers** [comment]
Yes the css its not work the css is not optimized

**Comment by XGProyect** [comment]
That's the normal behaviour.
