### ISSUE TITLE
Oficiales no sale tiempo en topnav

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#128]
Cuando esta activado el oficial no debería salir así "Activo por más de xxx días" pero solo sigue diciendo. Consigue lo ahora. en el antiguo ogame si me acuerdo lo decía.

![sin titulo](https://cloud.githubusercontent.com/assets/2124810/15445049/01082c86-1ecf-11e6-98c0-3e4abe6e2be6.png)

**Comment by XGProyect** [comment]
Si conseguis una captura lo implemento.

**Comment by FGServers** [comment]
Mejor lo ago mod por que de aca que busque una img de hace 7 años seria milagro

**Comment by FGServers** [comment]
Cierro esto coloco el nuevo despues
