### ISSUE TITLE
[v3.0.1] Weird jump in tecno level after upgrading

### ISSUE THREAD

**Issue by eX-Arkangel** [XGProyect/XG-Proyect-v3.x.x#132]
i put to upgrade armor tec from lv 19 to 20, when it finished it jumped to lv 23.

**Comment by FedePuratich** [comment]
I have the same problem..

**Comment by LucasKovacs** [comment]
@eX-Arkangel or @FedePuratich can you provide more details about this? I'm not being able to reproduce this issue.

**Comment by BeReal86** [comment]
@LucasKovacs 
I could not find any problem in trial
