### ISSUE TITLE
[v. 3.0.1] battle reports shows wrong damage made/absorved by shields

### ISSUE THREAD

**Issue by eX-Arkangel** [XGProyect/XG-Proyect-v3.x.x#133]
my fleet  tecnos 16-15-16
Light Fighter 	Heavy Fighter 	Cruiser 	Battleship 	Bomber 	Destroyer 	Deathstar 	BC
122703 	             48998 	11456 	82634 	           100 	   1100 	                11 	    11100

vs:  (tecno: 17-15-14)
RL	     LL HL 	Gauss	Ion 	Plasma  SS LS   LF	    BS 	Col 	Esp 	   Sat 	  Dest 	RIP
86539   1   1 	 701 	671 	   718     1   1 	1000   14901 	10 	100 	  23113 	12522 	26
DAMAGE REPORT FIRST ROUND:

The attacking fleet fires a total force of 507'996'060 points of damage. with 339'811 shots on the defender. The defender's shields absorb 25'670'180 points of damage.
The defending fleet fires a total force of 957'873'157 points of damage. with 141'803 shots on the attacker. The attacker's shields absorb 14'467'868 points of damage.

ROUND 5:
Round 5

Attacker eX_Arkangel
SmCargo 	LCargo 	LFighter 	HFighter 	Cruiser 	Battleship 	Bomber 	Destroyer  RIP   BC
75 	         780 	93932 	37621 	9441 	73549 	          94 	           1028 	  11 	10096

Defender sqval
170% - 150% - 140% 
Deathstar
26

The attacking fleet fires a total force of 257'625'225 points of damage. with 226'627 shots on the defender. The defender's shields absorb 3'250'000 points of damage.
The defending fleet fires a total force of 719'280'000 points of damage. with 1'332 shots on the attacker. The attacker's shields absorb 317'300 points of damage.

**Comment by XGProyect** [comment]
@eX-Arkangel can you please elaborate? I don't notice the bug.

**Comment by eX-Arkangel** [comment]
@XGProyect 
its exactly here:
The **attacking fleet** fires a total force of **257'625'225** points of damage. with 226'627 shots on the defender. The **defender's shields** absorb **3'250'000** points of damage.
The **defending fleet** fires a total force of **719'280'000 point**s of damage. with 1'332 shots on the attacker. The **attacker's shields** absorb **317'300 points** of damage.

see the damage my fleet (77k Battleships 11k Bcruiser, 11 Death Starts etc) do and the damage my shields absorb against only 26 DeathStars, wich there it says they do more damage than my fleet and their shield absorb more damage also (way to much diference). 
 And right now i have a report of an attack  made to me, seen some weird stuff as well:
BATTLE REPORT:
http://server.xgproyect.org/game.php?page=combatreport&report=dd818b5d7f7891c6e0f4b526c5acb8711464645809
MOON DESTRUCTION REPORT:
http://server.xgproyect.org/game.php?page=combatreport&report=b7d627e145900c8faaa588735328f6c2
 In the combat report check the amount of ships, and check round by round, you will see that with the entire fleet i don´t destroy even a single RIP, but in the last round with only my RIP´s remaining i do take down some RIP´s of the attacker, then the battle results:

The attacker has won the battle
obtaining 626 392 500 Metal, 341 692 500 Crystal and 101 758 438 Deuterium.
The attacker has lost a total of 5 S. cargo 000 000 units.
The defender has lost a total of 32 131 887 000 units.
A debris field: 6 766 915 Battlecru. Metal 4 433 275 Battlecru. Crystal floating in the orbit of the planet..
The probability that a moon emerge from the rubble is: 20% .

Check here what it says in "the attacker has lost ......"
and in: "a debris field....."

Also check the attacker and defender tecno infos:
Round 3

Attacker kky
**Probes%** - 220% - **Probes%** Deathstar
9377

Defender eX_Arkangel
**Probes%** - 190% - 230% Deathstar
872

it should say tecno names with lvl, but it puts: Probes%, or just the level 190%, and it doesn´t show the sum of weapons/shields/armor, but in the Moon Destruction reports apparently it shows everything as it should (except for the tecno levels):
Type	Deathstar
Aggressor
Weapons: Probes % Shield: 220 % Armor: Probes %
Amount	19
Weapons	502200
Shield	153450
Armor	2880000.
Also just notice checking the battle report again this:
Solar Satellite
F. light00 (this would be the amount of sat´s in my planet at the beginning of the report)

Well i don´t think it actually qualifies as a real bug, its more as a wrong info reporting, maybe its related to the unusual amount of ships/numbers, for what i´ve simulated the battle itself goes as it should be (using trashsim)
