### ISSUE TITLE
[3.0.1] Searcher does not show all search matches

### ISSUE THREAD

**Issue by eX-Arkangel** [XGProyect/XG-Proyect-v3.x.x#135]
since old versions 2.x.x the searcher has never (as far i can remember) work well (unless is intended this way), it only shows 20-25 matches which are random picks of the total, example: you´re searching for planet names, put Colony and search, it will only show 25 matches even if there are 200. From what i´ve seen the admin panel searcher does work well (from 2.10.x versions), showing all results by pages, of course it also shows info like the user ID and registration date and latest activity, but this can be tweaked to be omitted in normal accounts (i think).

Not sure if this qualifies as a bug or enhancement.

**Comment by eX-Arkangel** [comment]
Update: well, just to be more specific, it actually does not show any search result if you search: PLanet Name/ Colony or colony, in fact it does not show any match with the word colony even searching it by only letters example: search "Y" or "C" or "N", so besides only showing 25 search results is completely omitting the colonized planets, it seems as if this planets are not recognized as searchable objects, i even change the name of one of my colonies and nothing showed up either

**Comment by LucasKovacs** [comment]
Fixed, and also added option to set how many results to show. (Default: 25)
