### ISSUE TITLE
[3.0.1] MariaDB SQL Error in UsersLib.php

### ISSUE THREAD

**Issue by Bustux** [XGProyect/XG-Proyect-v3.x.x#136]
I have a new error at the moment but i can not really say what goes wrong:
I know i am using MariaDB instead of a MySql server but the setup does not work on MySql server.
MariaDB version : 10.1.13
Log: 
|[...]|SQL Error|Database query failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELECT COUNT(user_id) AS `ally_members` 
                        FROM `ogm_users' at line 2 Last SQL Query: SELECT a.`alliance_id`, a.`alliance_ranks`
                    (SELECT COUNT(user_id) AS `ally_members` 
                        FROM `ogm_users` 
                        WHERE `user_ally_id` = '2') AS `ally_members`
                FROM ogm_alliance AS a
                WHERE a.`alliance_id` = '2';|Where called: line 146 of application\core\Database <br/>(in [...]application\libraries\UsersLib.php)|2016/06/13 19:07:57||

**Comment by LucasKovacs** [comment]
Relate to commit 08393550b97e0dd053c1039073d2ff951587454f
