### ISSUE TITLE
Battle Report - I can't see it complete

### ISSUE THREAD

**Issue by Jorch95** [XGProyect/XG-Proyect-v3.x.x#137]
The problem i have with the Battle Report is that i can't scroll it to see the full report. It's just a view problem that i can't fix, and I appreciate a lot if you could help me with this.

Thanks.
![captura de pantalla de 2016-06-17 19 26 24](https://cloud.githubusercontent.com/assets/10543128/16166461/ce311ed6-34c1-11e6-9464-513088daa28a.png)

**Comment by FedePuratich** [comment]
This problem happen because the body style of the game declares overflow: hidden and the html template of the report not remplace it

**Comment by FedePuratich** [comment]
We fix it change the atributes at <body> in /aplicattion/views/general/simple_header.php erase all the atributes, this fix not change the view general in game.
