### ISSUE TITLE
[3.0.1] Vacation Mode lets you use galaxy

### ISSUE THREAD

**Issue by eX-Arkangel** [XGProyect/XG-Proyect-v3.x.x#138]
its only that, while in vacation mode you should not be able to use the galaxy view or search different systems/galaxys.

PD: also it does not show any signs you are in V mode unless you try to do something (send fleet, build, research etc), of course this is just for notification purpose only

**Comment by LucasKovacs** [comment]
This issue was related to #146. That part is now fixed, although the galaxy works as expected.
