### ISSUE TITLE
[3.0.0] Flota genera 30% de escombros

### ISSUE THREAD

**Issue by carter15** [XGProyect/XG-Proyect-v3.x.x#141]
Al cambiar el % de flota que va a escombros, dentro del juego no varia: siempre es 30%.

**Comment by FGServers** [comment]
Si no esta declarado la funcion $conf[] en el archivo constant del motor de batalla para cambiarlo tenes q modificar esto

vendor/battle_engine/constants/battle_constants.php entras hay y buscas esto

define('SHIP_DEBRIS_FACTOR', 0.3); //Percentage of debris generated from destroyed defenses.
define('DEFENSE_DEBRIS_FACTOR', 0.3); //Percentage of debris generated from destroyed ships.

el 0.3 equibale al 30% voy a ver si puedo integrar la funcion config en ese archivo
