### ISSUE TITLE
[3.0.0] Puntos no se actualizan

### ISSUE THREAD

**Issue by carter15** [XGProyect/XG-Proyect-v3.x.x#142]
Al usar el editor desde el panel de admin, los puntos al subir investigaciones, edificios, o naves, no generan puntos en la cuenta donde se editaron.

_En las versiones XGP 2.X esto funciona correctamente_.

**Comment by imleyenda** [comment]
El problema es que los puntos se actualizan cada vez que haces algo desde el juego no del panel de admin, para ello en el panel de admin habría que meter una función como la que tengo yo en mi juego.

`private function get_all_time_points() {
	$resource = \Models\Objects::$resource;
	$user_model = new \Models\User();

	$points = 0;
	$planets = $user_model->get_planets($this->current_user['user_id'], true);
	foreach($resource as $id => $name) {
		$price = \Models\Objects::get_price($id);
		$total = $price['metal'] + $price['crystal'] + $price['deuterium'];

		if ($id < 200 && $id > 100) {
			$level = $this->current_user[$name];
			$s = $price['factor'] * $level;

			$points += ($total * $s) / 1000;
		} else {
			foreach($planets as $planet_id => $array) {
				$level = $array[$resource[$id]];
				$total = $price['metal'] + $price['crystal'] + $price['deuterium'];
				if ($price['factor'] > 1) {
					$s = (pow($price['factor'], $level) - 1) / ($price['factor'] - 1);
				} else {
					$s = $price['factor'] * $level;
				}

				$points += ($total * $s) / 1000;
			}
		}
	}

	$points = floor($points);
	print $points;
}`

Claro que esto hay que adaptarlo a xgproyect, pero ahí dejo un indicio por si sirve de algo, saludos :D

**Comment by LucasKovacs** [comment]
Closed as duplicated of #103
