### ISSUE TITLE
[3.0.2] No sale la cantidad en mensajes modo comandante

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#148]
No muestra la cantidad  en el modo comandante

![mensajes](https://cloud.githubusercontent.com/assets/2124810/19029896/7c05b82a-8920-11e6-8d67-59c888082fd6.png)

**Comment by LucasKovacs** [comment]
@FGServers por favor hacete un pull por que no puedo reproducir este error.

**Comment by FGServers** [comment]
Acabo de reniciar el servidor, y active el comandante desde el panel admin
Sin comandate no salen los operadores
![no salen los operador](https://cloud.githubusercontent.com/assets/2124810/19494507/dcc99730-9555-11e6-9cc5-3fe583f6d55b.png)

con comandante
![reinicioe](https://cloud.githubusercontent.com/assets/2124810/19494516/eac57e76-9555-11e6-8114-cc4e39b22a42.png)

si seleccionas el checkbox own alliance y le das ok sin alianza salta este error_


Fatal error: Call to a member function fetch_array() on null in C:\xampp\htdocs\NewGalaxy\application\core\Database.php on line 271

Warning: Invalid callback application\core\Sessions::write, cannot access private method application\core\Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (C:\xampp\tmp) in Unknown on line 0

Warning: Invalid callback application\core\Sessions::close, cannot access private method application\core\Sessions::close() in Unknown on line 0

osea q no toma valores cuando no tenes notas, sin alianza tampoco cuando seleccionas el checkbox de operadores tampoco funciona y tengo la version 3.0.2 solo cambie el skin nomas
