### ISSUE TITLE
[3.0.2] Fatal error al usar los imputs en mesajes

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#149]
Esto sucede cuando seleccionas el checkbox para ver las notas de la pagina de mensaje

Fatal error: Call to a member function fetch_array() on null in C:\xampp\htdocs\XGP3.0.2\application\core\Database.php on line 271

Warning: Invalid callback application\core\Sessions::write, cannot access private method application\core\Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (C:\xampp\tmp) in Unknown on line 0

Warning: Invalid callback application\core\Sessions::close, cannot access private method application\core\Sessions::close() in Unknown on line 0

**Comment by LucasKovacs** [comment]
@FGServers por favor hacete un pull por que no puedo reproducir este error.
