### ISSUE TITLE
[v3.0.2] Messages Ok button

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#160]
Whether address book mark one part of the show you get the memo section, shows that there is pressure on the arrow button information.

Spy reports 
Battle reports 
Reportes de expedición
Messages from alliance  
Messages from players  
Other messages  

but it does not turn the pressure on the arrow button, select any message type that information.

when clicked, it opens directly onto the above message types.

![messages](https://cloud.githubusercontent.com/assets/16218107/19612615/4f8debd0-97f0-11e6-9923-03d8dd1e7fe1.png)

**Comment by LucasKovacs** [comment]
I can't reproduce this issue
