### ISSUE TITLE
[v3.0.2] Budy list send page

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#161]
Opening the page to submit this request is normal. but friendship stops after the next page request is sent and the game stays on there.

wherein the condition is as seen in the pictures.

![budy list](https://cloud.githubusercontent.com/assets/16218107/19620763/612227de-988c-11e6-9033-eae5d18185fd.png)

**Comment by FGServers** [comment]
en la version de ogame aniversario esta sin ventana emergente
![en ogame1304 de](https://cloud.githubusercontent.com/assets/2124810/19631613/12ddab0e-9975-11e6-87d4-8e008d1b5370.png)
