### ISSUE TITLE
[v3.0.2]Agregar skins propios usuarios (Esta funcion deveria volver)

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#162]
No se si va aca, pero deveria volver el apartado de agregar skins, al proyecto estoy tratando de adaptar 

define('DPATH' , ( ( !$user["dpath"] ) ? DEFAULT_SKINPATH : SKIN_PATH . $user["dpath"] . '/' ) );

esta funcion al common.php para que puedan tener su propio skin los usuarios como seria

Lo publico aca por que el foro esta caido

**Comment by LucasKovacs** [comment]
No es algo que sea prioridad en estos momentos.
