### ISSUE TITLE
[v3.0.2] Phalanx error not deuterium

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#164]
Notice: Undefined variable: TargetName in C:\xampp\htdocs\OGLatino\application\controllers\game\phalanx.php on line 202- 

whitout deuterium or deuterium 0.  

Image for the bug
![sin titulo](https://cloud.githubusercontent.com/assets/2124810/19992974/ec33adb4-a220-11e6-8462-435d48b6a8d0.png)

**Comment by BeReal86** [comment]
I just did an experiment and unfortunately did not have any problems

![phalanx](https://cloud.githubusercontent.com/assets/16218107/20011876/21b7130c-a2be-11e6-8e5b-dbda4dbce575.png)

**Comment by MahmutHizal** [comment]
add this variable to [upload/application/controllers/game/phalanx.php Line: 94](https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/master/src/xgp3.0.0/upload/application/controllers/game/phalanx.php#L94)
```php
$TargetName = "";
```

**Comment by BeReal86** [comment]
@MahmutHizal sizinde deneme şansınız oldumu? Ben radar sensöründe herhangi bir hata alamadım.

**Comment by MahmutHizal** [comment]
@BeReal86 malesef deneyemiyorum ancak, tahminimce php versiyonuyla ilgili bir durum. 

Kaynak olarak şurası gösterilebilir: [PHP: Basics - Manual](http://php.net/manual/en/language.variables.basics.php#example-126)
> İlklendirilmemiş bir değişkenin öntanımlı değerine güvenmek, içinde aynı değişken isminin kullanıldığı bir dosyayı betiğe dahil ettiğinizde sorun çıkarır. Bunun aynı zamanda büyük bir güvenlik riski omuşturmaması için register_globals yönergesine 'on' değeri atanmalıdır. İlklendirilmemiş değişken kullanımı E_NOTICE seviyesinde hata oluşturur, ancak ilklendirilmemiş bir diziye eleman eklenmesi halinde hata oluşmaz. isset() dil oluşumu bir değişkenin ilklendirilip ilklendirilmediğini öğrenmek için kullanılabilir. 

Hata, şu şekilde de çözülebilir:
[/upload/application/controllers/game/phalanx.php Satır: 202](https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/master/src/xgp3.0.0/upload/application/controllers/game/phalanx.php#L202)
```php
$parse['phl_pl_name'] = (isset($TargetName) ? $TargetName : "");
```
