### ISSUE TITLE
Planet name doesn't change when tried to rename planet

### ISSUE THREAD

**Issue by MahmutHizal** [XGProyect/XG-Proyect-v3.x.x#165]
Planet name doesn't change when tried to post new planet name
![ekran goruntusu - 2016-11-08 22-40-55](https://cloud.githubusercontent.com/assets/7260763/20114240/2a6ff342-a5fc-11e6-8a61-1966500cbacc.png)

I fixed it like this:
Find file: [/application/controllers/game/renameplanet.php Line 127](https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/master/src/xgp3.0.0/upload/application/controllers/game/renameplanet.php#L127) and add this before line.
```php
return FunctionsLib::message('Planet name changed', "game.php?page=renameplanet", 2);
```

**Comment by BeReal86** [comment]
Thank you for your feedback.

I do not have any problems when I am currently experimenting with the latest files.

**Comment by BeReal86** [comment]
Merhaba bu arada,

Şimdi buldum gözden kaçırmışım. İsim değiştirdiğin zaman sol üstteki sekmedeki isim yenileniyor fakat bulunduğu sayfadaki  aynı kalıyor oda ancak sayfa yenileme yada yeniden oraya girilince değişiyor.

Teşekkürler. Eline sağlık.

**Comment by MahmutHizal** [comment]
Take a look at planet list located topnav
After, look at planet name row where located in rename planet table. This is not an important issue but, still is an issue :)

**Comment by BeReal86** [comment]
A big problem for us. Our goal is to be perfect. 
Thanks for your help. :)
