### ISSUE TITLE
Language select error when tried to select language "list" on installation screen

### ISSUE THREAD

**Issue by MahmutHizal** [XGProyect/XG-Proyect-v3.x.x#166]
Hi,
![ekran goruntusu - 2016-11-09 20-54-55](https://cloud.githubusercontent.com/assets/7260763/20148682/6f776c1c-a6b6-11e6-9f2b-ba5d8e8fd999.png)
If select "Select language", see  this error
![ekran goruntusu - 2016-11-09 20-56-45](https://cloud.githubusercontent.com/assets/7260763/20148743/a92e8cf6-a6b6-11e6-9224-a4c6a39cc22d.png)

**Comment by BeReal86** [comment]
I am using xampp and tried the language option during installation. 
There was no problem.

Thanks for your feedback

**Comment by djlolito** [comment]
MahmutHizal te da el error cuando seleccionas un idioma o cuando pulsas en select language?

**Comment by MahmutHizal** [comment]
Sorry but i do not understand what you said. Please try english

**Comment by djlolito** [comment]
My English is not very good haha, I was wondering if the error comes when you select a language or you press select language

**Comment by MahmutHizal** [comment]
Press to "select language"
