### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by AntidoteEPI** [XGProyect/XG-Proyect-v3.x.x#167]
It seems like there is an error for update when you are on 3.0.0.
The updates files are empty except for 3.0.1.
Am i doing this wrong or is there a way to update ?

**Comment by Antidote78** [comment]
I'm also having issues with registration on the website. I can't confirm my identity with the mail i received.


Estimado $username,

Gracias por registrarte en $vboptions[bbtitle]. Antes de que podamos ativar tu cuenta, un último paso debe tomarse para completar tu registro.

Por favor ten en cuenta que debes completar este último paso para convertirte en un usuario registrado. Necesitarás visitar este enlace solo una vez para activar tu cuenta.

Para completar tu registro, por favor visita este enlace:
$vboptions[bburl]/register.php?a=act&u=$userid&i=$activateid

**** ¿No trabajaron los enlaces anteriores? ****
Si los enlaces de arriba no funcionaron, por favor utiliza tu navegador para dirigirte a:
$vboptions[bburl]/register.php?a=ver

Por favor asegúrate de no agregar espacios extras. Necesitarás escribir tu nombre de usuario y el código de activación en la página que aparece cuando visitas el enlace anterior.

Tu nombre de usuario es: $username
Tu código de Activación es: $activateid

Si aún estás teniendo problemas para activar tu cuenta, por favor contacta un miembro de nuestro personal de soporte en $vboptions[webmasteremail]

Saludos cordiales,
Equipo de $vboptions[bbtitle]


--------------------
Si no deseas seguir recibiendo este correo, por favor visita este enlace:
$vboptions[bburl]/register.php?do=deleteactivation&u=$userid&i=$activateid

**Comment by djlolito** [comment]
En teoría ya está arreglado prueba de nuevo

**Comment by BeReal86** [comment]
@AntidoteEPI  The update section is not complete. 
We have information about the problem.
You can remove the error by running the sql query.

`UPDATE `xgp_options` SET` option_value` = '3.0.3' WHERE option_name = 'version';`
