### ISSUE TITLE
cannot download !!!

### ISSUE THREAD

**Issue by valdros** [XGProyect/XG-Proyect-v3.x.x#169]
i cant download the latest versions  XGP3.0.3
hope it can be fix soon.. thx

**Comment by BeReal86** [comment]
The download of the corresponding version has been successful.

https://github.com/XGProyect/XG-Proyect-v3.x.x/releases

Please try again from the link above.

If you are still having problems please tell us in more detail.

**Comment by BeReal86** [comment]
If you are having problems again do not hesitate to contact us.
