### ISSUE TITLE
Username Change

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#17]
Notice: Undefined index: building_crystal_store in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 39

Notice: Undefined index: building_deuterium_tank in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 40

Notice: Undefined index: planet_temp_max in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 47

Notice: Undefined index: planet_energy_max in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 52

Notice: Undefined index: planet_energy_used in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 53

Notice: Undefined index: planet_building_metal_mine_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_metal_mine in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_crystal_mine_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_crystal_mine in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_deuterium_sintetizer_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_deuterium_sintetizer in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_solar_plant_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_solar_plant in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_fusion_reactor_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_fusion_reactor in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 100

Notice: Undefined index: planet_ship_solar_satellite_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: ship_solar_satellite in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_type in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 111

Notice: Undefined index: planet_last_update in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 130

Notice: Undefined index: planet_metal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 158

Notice: Undefined index: planet_metal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 162

Notice: Undefined index: planet_crystal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 173

Notice: Undefined index: planet_crystal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 177

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 188

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 192

Notice: Undefined index: planet_b_hangar_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 296

Notice: Undefined index: planet_b_tech in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 252

Notice: Undefined index: planet_b_tech_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 252

Notice: Undefined index: planet_b_hangar_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 277

Notice: Undefined index: planet_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 288

Notice: Undefined index: planet_b_building_id in /home/eskiog/public_html/beta6/application/libraries/UpdateLib.php on line 115

Notice: Undefined index: building_crystal_store in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 39

Notice: Undefined index: building_deuterium_tank in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 40

Notice: Undefined index: planet_temp_max in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 47

Notice: Undefined index: planet_energy_max in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 52

Notice: Undefined index: planet_energy_used in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 53

Notice: Undefined index: planet_building_metal_mine_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_metal_mine in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_crystal_mine_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_crystal_mine in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_deuterium_sintetizer_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_deuterium_sintetizer in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_solar_plant_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_solar_plant in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_building_fusion_reactor_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: building_fusion_reactor in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 100

Notice: Undefined index: planet_ship_solar_satellite_porcent in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 64

Notice: Undefined index: ship_solar_satellite in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 65

Notice: Undefined index: planet_type in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 111

Notice: Undefined index: planet_last_update in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 130

Notice: Undefined index: planet_metal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 158

Notice: Undefined index: planet_metal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 162

Notice: Undefined index: planet_crystal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 173

Notice: Undefined index: planet_crystal in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 177

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 188

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 192

Notice: Undefined index: planet_b_hangar_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 296

Notice: Undefined index: planet_b_tech in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 252

Notice: Undefined index: planet_b_tech_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 252

Notice: Undefined index: planet_b_hangar_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 277

Notice: Undefined index: planet_id in /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php on line 288

Notice: Undefined index: planet_b_building_id in /home/eskiog/public_html/beta6/application/libraries/UpdateLib.php on line 115

Warning: Cannot modify header information - headers already sent by (output started at /home/eskiog/public_html/beta6/application/libraries/UpdateResourcesLib.php:177) in /home/eskiog/public_html/beta6/application/libraries/Functions_Lib.php on line 443

**Comment by XGProyect** [comment]
@BeReal86 can you please provide more information about this issue? Thanks.

**Comment by BeReal86** [comment]
Type the new user name in the settings, I click save changes. Settings saved writes doing out of the game. When fully opened the main page, I see errors written above. Of course, it's still at the bottom of the home page. When I log in with the new user name just a white page and error codes is available.

**Comment by XGProyect** [comment]
Fixed
