### ISSUE TITLE
Forum Registration

### ISSUE THREAD

**Issue by trindium** [XGProyect/XG-Proyect-v3.x.x#170]
Confirmation Email is all messed up..

Thx

Juan

**Comment by Antidote78** [comment]
I can confirm it. The email doesnt change the variable for the validation token and the userid

**Comment by Alberolle7** [comment]
Para que narices haces un foro? Para no preocuparte de el? Lucky te contacte por soporte hace 1 semana explicándote el fallo, hay gente en el foro y aquí que te lo dicen.
Me parece una irresponsabilidad de tu parte, si no tienes tiempo para hacer esto, no lo hagas, pasarle el dominio a alguien que tenga ganas macho

**Comment by BeReal86** [comment]
Hello @trindium, @Antidote78, @Alberolle7 

Writing exactly what the problem is more descriptive

**Comment by Alberolle7** [comment]
CANT REGISTER ON FORUM!!!

2017-02-06 15:38 GMT+01:00 Ufuk Avcıoğlu <notifications@github.com>:

**Comment by Alberolle7** [comment]
See the forum, when user register, send email with variables!
OMG!!!

**Comment by BeReal86** [comment]
Hi,

>Registration
Thank you for registering, BeReal2. An email has been dispatched to m**********@gmail.com with details on how to activate your account. Click here to return to where you were previously. 

> You will receive an email in your inbox. You MUST follow the link in that email before you can post on these forums. Until you do that, you will be told that you do not have permission to post.
> OK 


There is no problem in the forum registration process. I did this on the phone right now. Please note the information you entered.

![20170207_072639](https://cloud.githubusercontent.com/assets/16218107/22677839/e0ca0302-ed06-11e6-96c9-fdb50ccecc3f.png)
![screenshot_20170207-072803](https://cloud.githubusercontent.com/assets/16218107/22677866/23d5df04-ed07-11e6-99af-fa1cf76cd456.png)

If an unused user id and verification code is typed correctly, this operation succeeds. Example above.

**Comment by trindium** [comment]
I try to register.... and always get the email with the variables....

**Comment by djlolito** [comment]
Bereal no seas terco, es mucha gente que lo dice, he tenido que registrarme otra cuenta y efectivamente tienen razon aquí te dejo yo el screen de lo que ellos comentan. Chicos no estáis solos en la batalla xD
![screenshot_20170207-192402](https://cloud.githubusercontent.com/assets/5112090/22705293/4335c2b0-ed6b-11e6-8e9d-186fbd415b79.png)

**Comment by BeReal86** [comment]
Yo voy a darle una oportunidad más, tal vez el problema es diferente.

**Comment by BeReal86** [comment]
El origen del problema ha sido encontrado. Resuelva pronto.

**Comment by djlolito** [comment]
El problema no reside en que la web de error, es en el mail que recibe el usuario, me alegro que se haya encontrado el bug y así puedan registrarse nuevos usuarios a la comunidad

**Comment by LucasKovacs** [comment]
Hemos actualizado la version del foro, y del paquete de idioma. Por favor vuelvan a intentar.
