### ISSUE TITLE
Error en pagina de amigos

### ISSUE THREAD

**Issue by MatiasOqui** [XGProyect/XG-Proyect-v3.x.x#171]
Buenas dias.. nose si esto ya ha sido denunciado o no.. pero en la pagina de amigos al enviar mas de una solicitud.. por ejemplo envio 3 solicitudes de amigos y quiero eliminar 1.. la teoria es que deberia eliminar la que yo estoy solicitando.. pero el sistema elimina las 3 solicitudes.. si esta corregido pido disculpas.. pero estoy corriendo la 3.0.3 y tiene ese error..

**Comment by BeReal86** [comment]
Por favor, explique por dar ejemplos, y más información sobre el tema por favor.
