### ISSUE TITLE
Otro error: Mensajes global

### ISSUE THREAD

**Issue by MatiasOqui** [XGProyect/XG-Proyect-v3.x.x#172]
No se visualizan las nuevas lineas al enviar un mensaje global desde el panel de administracion: El mensaje que envie fue el siguiente, se los muestro para que vean el error:

¡Saludos, Emperador!\r\n\r\nHay un tema importante en el foro del que deberias enterarte, ya que influira para la siguiente version del juego y te ayudara a tomar una postura.\r\n\r\nhttp://foro.megaverso.synergows.com/index.php?/topic/7-razas/#comment-7\r\n\r\n¡Mucha suerte!\r\nTu equipo de MegaVerso

El cual se deberia haber visto de la siguiente manera:

¡Saludos, Emperador!

Hay un tema importante en el foro del que deberias enterarte, ya que influira para la siguiente version del juego y te ayudara a tomar una postura.

http://foro.megaverso.synergows.com/index.php?/topic/7-razas/#comment-7

¡Mucha suerte!
Tu equipo de MegaVerso

**Comment by BeReal86** [comment]
Gracias por tus comentarios.

![adsiz](https://user-images.githubusercontent.com/16218107/27246477-8488199e-52fa-11e7-8cd2-af8a11ed69c9.png)
