### ISSUE TITLE
Destroy buildings on completely full planet

### ISSUE THREAD

**Issue by agentcobra** [XGProyect/XG-Proyect-v3.x.x#173]
Hi,

I can't destroy a building on a planet without any field left.
Have you got the same issue ?

best regards
agentcobra

**Comment by BeReal86** [comment]
Hi @agentcobra ,

I will provide some checks. But I will ask for more detailed examples from you.

**Comment by BeReal86** [comment]
Hi @agentcobra,

I made some experiments. 

When the planet area is full. No construction can be done. When the planet area is full, you can break down a unit. (When the planet is not full, the unit can be destroyed.)

In this and similar experiments, he did not encounter any problems.

![11110](https://cloud.githubusercontent.com/assets/16218107/23591062/ae85d61e-01fb-11e7-97f8-8d2ca43edb5d.png)
