### ISSUE TITLE
[v3.1.0] Register bug

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#176]
Fatal error: Class 'application\libraries\MessagesOptions' not found in C:\xampp\htdocs\XGP3.1.0\application\libraries\FunctionsLib.php on line 392

**Comment by BeReal86** [comment]
yes i checked the problem and added the picture as an attachment.
thank you for feedback

![register](https://user-images.githubusercontent.com/16218107/29743999-67c840b8-8aa4-11e7-8b15-e22e0282c7da.png)
