### ISSUE TITLE
[v3.0.4] Instalación nueva me manda a actualizar

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#178]
Cuando haces instalación de 0 siempre me sale actualice la versión y siempre dice 3.0.0 no de vería saltar eso solo cuando ya la tenes instalada a la versión y no cuando la instalas de 0.

(40, 'version', '3.0.0'), esto de vería ya venir con la versión en curso

**Comment by BeReal86** [comment]
Hemos escuchado acerca de esto. Entiendo su malestar por la notificación 

gracias
