### ISSUE TITLE
Time does not appear in the attacks

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#18]
![1](https://cloud.githubusercontent.com/assets/16218107/12698168/9b7fa57e-c79e-11e5-9b4e-3dcc13749eeb.jpg)
![2](https://cloud.githubusercontent.com/assets/16218107/12698169/a0a86d10-c79e-11e5-91fa-c5e1991567af.jpg)

**Comment by athk** [comment]
I can't reproduce. Maybe those attacks are just there and are _supposed_ to be happening, but are not being processed?

**Comment by BeReal86** [comment]
We did try twice. I had the same problem

**Comment by XGProyect** [comment]
I was able to reproduce and fix the bug. Coming out in the next release.
