### ISSUE TITLE
In Time of War

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#19]
To create a wartime month, 4-5 fleet was sent and results.

Notice: Constant OPBEPATH already defined in /home/eskiog/public_html/beta6/application/libraries/battle_engine/utils/includer.php on line 29

Fatal error: Cannot redeclare class GeometricDistribution in /home/eskiog/public_html/beta6/application/libraries/battle_engine/utils/GeometricDistribution.php on line 30

Warning: Invalid callback Sessions::write, cannot access private method Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

Warning: Invalid callback Sessions::close, cannot access private method Sessions::close() in Unknown on line 0

**Comment by XGProyect** [comment]
Fixed
