### ISSUE TITLE
[v3.1.0] Mission Deploy Consumption

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#197]
While other colonies to deploy a mission to a planet, the amount of fuel needed to leave the planet to the half.

I will try to give example

There are fleet from the planet A. I will send deployment planet B.
Deuterium consumption: 10.000

Fleet planet B, with half of this amount of time in the 5,000 deuterium u leave the planet.

before
deuterium content in the planet B / Deut: 20.000

after
The amount of deuterium in the fleet after the planet B / Deut: 25.000

**Comment by MahmutHizal** [comment]
I think this is very important for best game experience

**Comment by LucasKovacs** [comment]
@BeReal86 it's working.

Planet A, deuterium **1.000.000**
Planet B, deuterium **0**

Deploy from A to B, fuel cost **24**.

After deploy:
Deuterium in planet B: **12**

Conclusion: half of the fuel was consumed

**Comment by BeReal86** [comment]
I will clean install and test again

**Comment by BeReal86** [comment]
I checked again. I did not find any problems. it works right
