### ISSUE TITLE
errors i have found so far in this game

### ISSUE THREAD

**Issue by astrobloodknight** [XGProyect/XG-Proyect-v3.x.x#2]
Warning: require

(/home/test/public_html/Game/application/utils/includer.php): 

failed to open stream: No such file 

or directory in 

/home/test/public_html/Game/application/libraries/missions/attack.php on line 42

Fatal error: require(): Failed 

opening required 

'/home/test/public_html/Game/application/utils/includer.php' (include_path='.:/usr/local/lib/php
') in /home/test/public_html/Game/application/libraries/missions/attack.php on line 42

Warning: Invalid callback 

Sessions::write, cannot access 

private method Sessions::write() in 

Unknown on line 0

Warning: Unknown: Failed to write 

session data (user). Please verify 

that the current setting of 

session.save_path is correct () in 

Unknown on line 0

Warning: Invalid callback 

Sessions::close, cannot access 

private method Sessions::close() in 

Unknown on line 0

**Comment by astrobloodknight** [comment]
SQL Error

Database query failed: Last SQL Query: SELECT `user_id`, `user_name`, `user_galaxy`, `user_system`, `user_planet`,`user_ally_id`, `alliance_name` FROM Lot_users WHERE `user_id`='1'

Debug Log:
Query 1:	SELECT `session_data` FROM Lot_sessions WHERE `session_id` = '2b568649a4d6377e242d17a3b23658da' LIMIT 1
Where called: line 111 of Database
(in Sessions.php)
Query 2:	SELECT u.*, pre.*, se.*, usul.user_statistic_total_rank, usul.user_statistic_total_points, r.*, a.alliance_name, (SELECT COUNT(`message_id`) AS `new_message` FROM `Lot_messages` WHERE `message_receiver` = u.`user_id` AND `message_read` = 0) AS `new_message` FROM Lot_users AS u INNER JOIN Lot_settings AS se ON se.setting_user_id = u.user_id INNER JOIN Lot_users_statistics AS usul ON usul.user_statistic_user_id = u.user_id INNER JOIN Lot_premium AS pre ON pre.premium_user_id = u.user_id INNER JOIN Lot_research AS r ON r.research_user_id = u.user_id LEFT JOIN Lot_alliance AS a ON a.alliance_id = u.user_ally_id WHERE (u.user_name = 'vonrath') LIMIT 1;
Where called: line 209 of Database
(in Users_Lib.php)
Query 3:	UPDATE Lot_users SET `user_onlinetime` = '1436921223', `user_current_page` = '/Game/game.php?page=buddy', `user_lastip` = '50.49.18.30', `user_agent` = 'Mozilla/5.0 (Windows NT 5.2; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0' WHERE `user_id` = '6' LIMIT 1;
Where called: line 242 of Database
(in Users_Lib.php)
Query 4:	SELECT p.*, b.*, d.*, s.*, m.planet_id AS moon_id, m.planet_name AS moon_name, m.planet_image AS moon_image, m.planet_destroyed AS moon_destruyed, m.planet_image AS moon_image, (SELECT COUNT(user_statistic_user_id) AS stats_users FROM `Lot_users_statistics`) AS stats_users FROM Lot_planets AS p INNER JOIN Lot_buildings AS b ON b.building_planet_id = p.`planet_id` INNER JOIN Lot_defenses AS d ON d.defense_planet_id = p.`planet_id` INNER JOIN Lot_ships AS s ON s.ship_planet_id = p.`planet_id` LEFT JOIN Lot_planets AS m ON m.planet_id = (SELECT mp.`planet_id` FROM Lot_planets AS mp WHERE (mp.planet_galaxy=p.planet_galaxy AND mp.planet_system=p.planet_system AND mp.planet_planet=p.planet_planet AND mp.planet_type=3)) WHERE p.`planet_id` = '6';
Where called: line 275 of Database
(in Users_Lib.php)
Query 5:	UPDATE Lot_planets AS p INNER JOIN Lot_users_statistics AS us ON us.user_statistic_user_id = p.planet_user_id INNER JOIN Lot_defenses AS d ON d.defense_planet_id = p.`planet_id` INNER JOIN Lot_ships AS s ON s.ship_planet_id = p.`planet_id` INNER JOIN Lot_research AS r ON r.research_user_id = p.planet_user_id SET `planet_metal` = '106698.42666665', `planet_crystal` = '125798.85666665', `planet_deuterium` = '145360.4', `planet_last_update` = '1436921223', `planet_b_hangar_id` = '', `planet_metal_perhour` = '778122', `planet_crystal_perhour` = '518748', `planet_deuterium_perhour` = '321624', `planet_energy_used` = '-1039', `planet_energy_max` = '1553', `user_statistic_ships_points` = `user_statistic_ships_points` + '0', `user_statistic_defenses_points` = `user_statistic_defenses_points` + '0', `planet_b_hangar` = '0' WHERE `planet_id` = '6';
Where called: line 257 of Database
(in UpdateResources_Lib.php)
Query 6:	SELECT fleet_start_galaxy, fleet_start_system, fleet_start_planet, fleet_start_type FROM Lot_fleets WHERE `fleet_start_time` <= '1436921223' AND `fleet_mess` ='0' ORDER BY fleet_id ASC;
Where called: line 132 of Database
(in Update_Lib.php)
Query 7:	SELECT fleet_end_galaxy, fleet_end_system, fleet_end_planet, fleet_end_type FROM Lot_fleets WHERE `fleet_end_time` <= '1436921223 ORDER BY fleet_id ASC';
Where called: line 152 of Database
(in Update_Lib.php)
Query 8:	SELECT `user_statistic_user_id`, `user_statistic_technology_rank`, `user_statistic_technology_points`, `user_statistic_buildings_rank`, `user_statistic_buildings_points`, `user_statistic_defenses_rank`, `user_statistic_defenses_points`, `user_statistic_ships_rank`, `user_statistic_ships_points`, `user_statistic_total_rank`, (user_statistic_buildings_points + user_statistic_defenses_points + user_statistic_ships_points + user_statistic_technology_points) AS total_points FROM Lot_users_statistics ORDER BY `user_statistic_user_id` ASC;
Where called: line 104 of Database
(in Statistics_Lib.php)
Query 9:	INSERT INTO Lot_users_statistics (user_statistic_user_id, user_statistic_buildings_old_rank, user_statistic_buildings_rank, user_statistic_defenses_old_rank, user_statistic_defenses_rank, user_statistic_ships_old_rank, user_statistic_ships_rank, user_statistic_technology_old_rank, user_statistic_technology_rank, user_statistic_total_points, user_statistic_total_old_rank, user_statistic_total_rank, user_statistic_update_time) VALUES (1, 1, 1, 1, 1, 1, 1, 1, 1, 1062.99983196, 1, 1, 1436921223),(6, 2, 2, 2, 2, 2, 2, 2, 2, 634.26063581, 2, 2, 1436921223),(5, 3, 3, 3, 3, 3, 3, 3, 3, 63.02259697, 3, 3, 1436921223),(2, 4, 4, 5, 5, 5, 5, 5, 5, 1.62500000, 4, 4, 1436921223),(3, 5, 5, 4, 4, 4, 4, 4, 4, 0.00000000, 5, 5, 1436921223),(4, 6, 6, 6, 6, 6, 6, 6, 6, 0.00000000, 6, 6, 1436921223) ON DUPLICATE KEY UPDATE user_statistic_buildings_old_rank = VALUES(user_statistic_buildings_old_rank), user_statistic_buildings_rank = VALUES(user_statistic_buildings_rank), user_statistic_defenses_old_rank = VALUES(user_statistic_defenses_old_rank), user_statistic_defenses_rank = VALUES(user_statistic_defenses_rank), user_statistic_ships_old_rank = VALUES(user_statistic_ships_old_rank), user_statistic_ships_rank = VALUES(user_statistic_ships_rank), user_statistic_technology_old_rank = VALUES(user_statistic_technology_old_rank), user_statistic_technology_rank = VALUES(user_statistic_technology_rank), user_statistic_total_points = VALUES(user_statistic_total_points), user_statistic_total_old_rank = VALUES(user_statistic_total_old_rank), user_statistic_total_rank = VALUES(user_statistic_total_rank), user_statistic_update_time = VALUES(user_statistic_update_time);
Where called: line 252 of Database
(in Statistics_Lib.php)
Query 10:	SELECT a.`alliance_id`, ass.alliance_statistic_technology_rank, ass.alliance_statistic_buildings_rank, ass.alliance_statistic_defenses_rank, ass.alliance_statistic_ships_rank, ass.alliance_statistic_total_rank, SUM(us.user_statistic_buildings_points) AS buildings_points, SUM(us.user_statistic_defenses_points) AS defenses_points, SUM(us.user_statistic_ships_points) AS ships_points, SUM(us.user_statistic_technology_points) AS technology_points, SUM(us.user_statistic_total_points) AS total_points FROM Lot_alliance AS a LEFT JOIN Lot_users AS u ON a.`alliance_id` = u.`user_ally_id` LEFT JOIN Lot_users_statistics AS us ON us.`user_statistic_user_id` = u.`user_id` LEFT JOIN Lot_alliance_statistics AS ass ON ass.`alliance_statistic_alliance_id` = a.`alliance_id` GROUP BY alliance_id
Where called: line 281 of Database
(in Statistics_Lib.php)
Query 11:	SELECT u.*, pre.*, se.*, usul.user_statistic_total_rank, usul.user_statistic_total_points, r.*, a.alliance_name, (SELECT COUNT(`message_id`) AS `new_message` FROM `Lot_messages` WHERE `message_receiver` = u.`user_id` AND `message_read` = 0) AS `new_message` FROM Lot_users AS u INNER JOIN Lot_settings AS se ON se.setting_user_id = u.user_id INNER JOIN Lot_users_statistics AS usul ON usul.user_statistic_user_id = u.user_id INNER JOIN Lot_premium AS pre ON pre.premium_user_id = u.user_id INNER JOIN Lot_research AS r ON r.research_user_id = u.user_id LEFT JOIN Lot_alliance AS a ON a.alliance_id = u.user_ally_id WHERE (u.user_name = 'vonrath') LIMIT 1;
Where called: line 209 of Database
(in Users_Lib.php)
Query 12:	UPDATE Lot_users SET `user_onlinetime` = '1436921223', `user_current_page` = '/Game/game.php?page=buddy', `user_lastip` = '50.49.18.30', `user_agent` = 'Mozilla/5.0 (Windows NT 5.2; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0' WHERE `user_id` = '6' LIMIT 1;
Where called: line 242 of Database
(in Users_Lib.php)
Query 13:	SELECT p.*, b.*, d.*, s.*, m.planet_id AS moon_id, m.planet_name AS moon_name, m.planet_image AS moon_image, m.planet_destroyed AS moon_destruyed, m.planet_image AS moon_image, (SELECT COUNT(user_statistic_user_id) AS stats_users FROM `Lot_users_statistics`) AS stats_users FROM Lot_planets AS p INNER JOIN Lot_buildings AS b ON b.building_planet_id = p.`planet_id` INNER JOIN Lot_defenses AS d ON d.defense_planet_id = p.`planet_id` INNER JOIN Lot_ships AS s ON s.ship_planet_id = p.`planet_id` LEFT JOIN Lot_planets AS m ON m.planet_id = (SELECT mp.`planet_id` FROM Lot_planets AS mp WHERE (mp.planet_galaxy=p.planet_galaxy AND mp.planet_system=p.planet_system AND mp.planet_planet=p.planet_planet AND mp.planet_type=3)) WHERE p.`planet_id` = '6';
Where called: line 275 of Database
(in Users_Lib.php)
Query 14:	UPDATE Lot_planets AS p INNER JOIN Lot_users_statistics AS us ON us.user_statistic_user_id = p.planet_user_id INNER JOIN Lot_defenses AS d ON d.defense_planet_id = p.`planet_id` INNER JOIN Lot_ships AS s ON s.ship_planet_id = p.`planet_id` INNER JOIN Lot_research AS r ON r.research_user_id = p.planet_user_id SET `planet_metal` = '106698.42666665', `planet_crystal` = '125798.85666665', `planet_deuterium` = '145360.4', `planet_last_update` = '1436921223', `planet_b_hangar_id` = '', `planet_metal_perhour` = '778122', `planet_crystal_perhour` = '518748', `planet_deuterium_perhour` = '321624', `planet_energy_used` = '-1039', `planet_energy_max` = '1553', `user_statistic_ships_points` = `user_statistic_ships_points` + '0', `user_statistic_defenses_points` = `user_statistic_defenses_points` + '0', `planet_b_hangar` = '0' WHERE `planet_id` = '6';
Where called: line 257 of Database
(in UpdateResources_Lib.php)
Query 15:	SELECT * FROM Lot_buddys WHERE `buddy_sender`='6' OR `buddy_receiver`='6'
Where called: line 205 of Database
(in buddy.php)
Where called: line 236 of Database
(in buddy.php)

**Comment by astrobloodknight** [comment]
Notice: Undefined index: ship203 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 140

Notice: Undefined index: ship204 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 141

Notice: Undefined index: ship205 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 142

Notice: Undefined index: ship206 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 143

Notice: Undefined index: ship207 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 144

Notice: Undefined index: ship210 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 145

Notice: Undefined index: ship211 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 146

Notice: Undefined index: ship213 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 147

Notice: Undefined index: ship214 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 148

Notice: Undefined index: ship215 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 149

Notice: Undefined offset: 5 in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 314

Notice: Undefined variable: StayBlock in /home/test/public_html/Game/application/controllers/game/fleet3.php on line 333

**Comment by athk** [comment]
I'd split things into several issues, as you're mixing different things and that means this issue will get nowhere.

**Comment by XGProyect** [comment]
All fixed
