### ISSUE TITLE
In Time of War #2

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#20]
war report did not. Players enemy's ships did not disappear. but it went to war with the mining fleet coming back

Note:We bought some mistakes before this problem. On traders. Then these problems

Notice: Undefined index: sd in /home/eskiog/public_html/beta6/application/libraries/missions/attack.php on line 259

Warning: mail() has been disabled for security reasons in /home/eskiog/public_html/beta6/application/libraries/Debug_Lib.php on line 112
XG Proyect

500. That’s an error.

The requested URL throw an error. Contact the game Administrator. That’s all we know. 

and some DB error records
![3](https://cloud.githubusercontent.com/assets/16218107/12698386/e2f62266-c7a3-11e5-9d30-aa8333da7426.png)

**Comment by XGProyect** [comment]
Several fixes were applied to attacks.
