### ISSUE TITLE
[Improve] Chage username only seven day

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#203]
Change username every 7 days anything published my code

`if ($this->_current_user['user_name'] != $_POST['db_character']) {
                $query = parent::$db->queryFetch(
                    "SELECT `user_id`
                    FROM `" . USERS . "`
                    WHERE user_name = '" . parent::$db->escapeValue($_POST['db_character']) . "'"
                );

                if (!$query) {
                    if($this->_current_user['user_name_time_change'] == '0' && $this->_current_user['user_name_time_change'] < time()){
                        $change_time_username = FunctionsLib::getDefaultChangeUsernameTime();
                        parent::$db->query(
                            "UPDATE `" . USERS . "` SET
                            `user_name_time_change` = '" . $change_time_username . "'
                            WHERE `user_id` = '" . $this->_current_user['user_id'] . "'
                            LIMIT 1"
                        );

                        if ($this->_current_user['user_name_time_change'] < time() && $this->_current_user['user_name_time_change'] != '0'){
                            parent::$db->query(
                                "UPDATE `" . USERS . "` SET
                                `user_name_time_change` = '0'
                                WHERE `user_id` = '" . $this->_current_user['user_id'] . "'
                                LIMIT 1"
                            );
                        }

                        parent::$db->query(
                            "UPDATE `" . USERS . "` SET
                            `user_name` = '" . parent::$db->escapeValue($username) . "'
                            WHERE `user_id` = '" . $this->_current_user['user_id'] . "'
                            LIMIT 1"
                        );
                        
                        session_destroy();
                        FunctionsLib::message($this->_lang['op_username_changed'], "game.php?page=preferences", 1);
                    } else {
                        FunctionsLib::message($this->_lang['op_change_username_error'], "game.php?page=preferences", 1);
                    }
                }
            }`

`ALTER TABLE `xgp_users` ADD `user_name_time_change` INT(11) NOT NULL;` la DB SQL

Text English

`You can change your username once per week. To do so, click on your name or the settings at the top of the screen.`

text Spanish

`uedes cambiar tu nombre de jugador una vez por semana. Para ello, haz clic sobre tu nombre en la parte superior de la pantalla o en Opciones.`

**Comment by FGServers** [comment]
Esto lo pueden cerrar... lucky ya lo terminaste con el refractor de las preferencias

**Comment by LucasKovacs** [comment]
Completed during the preferences refactor 0e55390e
