### ISSUE TITLE
[v3.1.0] Trader Errors

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#207]
- the text that should be in the first picture group is missing.
- In the second group of images, swapping is performed without entering a value. 3500 dark matter has been wasted.

![trader](https://user-images.githubusercontent.com/16218107/31588842-7ac59ea8-b200-11e7-8bdf-0255a41650fa.png)

**Comment by LucasKovacs** [comment]
Closed since the trader it's being refactor.
