### ISSUE TITLE
 [v3.1.0] Mission ACS

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#209]
![acs](https://user-images.githubusercontent.com/16218107/31589051-6ddbf0b8-b203-11e7-8053-19f8e8226476.png)

Another problem with acs. Only one fleet appears on the screen.

**Comment by canaydemir** [comment]
same problem


Where called: line 61 of application\controllers\game\Fleet4 (in fleet4.php)
Undefined index: user_authlevel

**Comment by BeReal86** [comment]
Hi @canaydemir

Exactly where this problem comes out and how it is occurring. If you give us more detailed information, please. Thank you.

**Comment by canaydemir** [comment]
Hi @BeReal86 

download yesterday 3.1.0

i try php 5.5 7.0 7.1 7.2 all same error

i choose colony ships and enter targer coord. than send for mission colonize 

![xg02](https://user-images.githubusercontent.com/22556717/41808167-46f30b9a-76e2-11e8-9eb1-973d27bb6765.JPG)
![xg03](https://user-images.githubusercontent.com/22556717/41808168-4719ba74-76e2-11e8-8abd-1d89cc40be4d.JPG)
![xg04](https://user-images.githubusercontent.com/22556717/41808169-473ec15c-76e2-11e8-840c-5227493957c9.JPG)

**Comment by canaydemir** [comment]
Ufuk bey selam oyunu bir hostinge kurdum (güzel host) 3.0.4 de saldırı kısmında da hata alıyordum arada bina yükseltirkende hata veriyordu 3.1.0 ı yükledim saldırıda ve diğer yerlerde bir sorun yok nakliyede de sorun yok geri dönüşümde gidiyor ama koloni gemisini koloni kurmak için boş yere gönderince bu hatayı veriyor. php ya da mysql sürümü ile ilgili olabilir mi eğer öyleyse tavsiye edeceğiniz hosting var mı

**Comment by MahmutHizal** [comment]
Php versiyonunu 5.5 yaptığınızda sorunun ortadan kalkması gerekiyor. 3.1.0 sürümünde 5.5 denediniz mi?

**Comment by canaydemir** [comment]
3.1.0 sürümünde php 5.5 i de seçince aynı hatayı almaktayım xampp ile bilgisayarda da denedim aynı sorun oldu yine

guzel host 5.5 sürümü PHP Version 5.5.38

![xg05](https://user-images.githubusercontent.com/22556717/41808737-9d6ca082-76ea-11e8-8548-12e9a7b65364.JPG)
![xg06](https://user-images.githubusercontent.com/22556717/41808738-9db4bbc4-76ea-11e8-8d01-de6f27836df2.JPG)

**Comment by BeReal86** [comment]
Merhaba Can bey, öncelik ile eskiden test yaparken php 5.6 sürümune göre test ederdim. Lakin hangi sürümde denerseniz deneyin bazı filo hareketlerinde çeşitli hatalar ile karşilaşabilirsiniz. Şuanki listemizin ikinci kısmında filo ve filo görevleri ile ilgili sorunları gidermeye çalışacağız. Bu son bahsettiğiniz sorunuda not almış bulunmaktayım. İlginize teşekkür ederim.

**Comment by canaydemir** [comment]
önerebileceğiniz sağlıklı çalıştığı bir hosting varsa çok sevinirim.

ilginiz için ben teşekkür ederim kolaylıklar dilerim.

**Comment by BeReal86** [comment]
Yazılımsal hatalar giderilince her hosting şirketinde sorunsuz çalışır. Daha once pek çok host firmasında denemeler yaptımdı. Daha önce tabi 3.0 sürümünde denemelee yapmıştım. Yinede dilerseniz birkac yeri yazabilirim.

**Comment by LucasKovacs** [comment]
guys please! english .... :/

**Comment by canaydemir** [comment]
@LucasKovacs hi its my bad we talk about which hosting best for this script i have some problem like pic. :(

@BeReal86 can you tell me which hosting you work fine before thank you

**Comment by BeReal86** [comment]
@canaydemir some of the hosting companies that i used until this time
Byethost
sadecehosting
megatr
natro
radore

**Comment by LucasKovacs** [comment]
@canaydemir all the issues that you've are because you're using PHP7+, if you downgrade to PHP 5.5 or 5.6 it will work fine. We're on a long process of converting the game to PHP7 which will take a while.

The hosts above should work.

**Comment by agentcobra** [comment]
@LucasKovacs, I'm under PHP 7.2.7-1+0~20180622080745.23+stretch~1.gbpfd8e2e (cli) (built: Jun 22 2018 08:07:48) ( NTS )
it works !

**Comment by LucasKovacs** [comment]
Next phase 2 will cover all the fleets pages and missions, hope to get that fully working.

**Comment by canaydemir** [comment]
@BeReal86 by the way megatr same issue php 5.6

we waiting :)

**Comment by LucasKovacs** [comment]
Fixed on v3.1.0 - phase 2
