### ISSUE TITLE
[v3.1.0] outer space number in galaxy view

### ISSUE THREAD

**Issue by agentcobra** [XGProyect/XG-Proyect-v3.x.x#214]
Hi,
I've got a problem with the outerspace
![c214ab4a-4f3e-4842-b4b1-dd02307082be](https://user-images.githubusercontent.com/1831853/32362564-a9574b54-c06a-11e7-8637-c0f45541f6b1.png)
the number isn't correct
-
(I'm using XG Proyect® Version 3.1.0)

**Comment by FGServers** [comment]
this change in application/views/galaxy/galaxy_body.php

`<tr>
                    <th width="30">16</th>
                    <th colspan="7">
                        <a href="game.php?page=fleet1&galaxy={galaxy}&amp;system={system}&amp;planet=16&amp;planettype=1&amp;target_mission=15">{gl_out_space}</a>
                    </th>
                </tr>`

this not bug

**Comment by agentcobra** [comment]
Is it possible to calculate it automatically?

**Comment by MahmutHizal** [comment]
Yes it is, like this: use MAX_PLANET_IN_SYSTEM constant +1. For example, MAX_PLANET_IN_SYSTEM defined to 12, outer space planet number is 13 because formule = (MAX_PLANET_IN_SYSTEM + 1). Of course, define this formula to the template file like {galaxy} thing :)

**Comment by agentcobra** [comment]
Do I need to do a PR?
