### ISSUE TITLE
bcrypt instead of sha1

### ISSUE THREAD

**Issue by danieluyo** [XGProyect/XG-Proyect-v3.x.x#215]
Actually SHA-1 has been "officially insecure" for a longer time, since an attack method was published in 2011. The 2017 collisions was just the first known case of actually running the attack. 

Why bcrypt? https://rietta.com/blog/2016/02/05/bcrypt-not-sha-for-passwords/
+Info: http://codahale.com/how-to-safely-store-a-password/

```php
<?php
$value = 'Hello World!';
$hash  = password_hash($value, PASSWORD_BCRYPT, ['cost' => 10]);
// The result: '$2y$10$VlcvON9JVs/LHQpL/1eoM.p4RsniGAmWs4btzK/GsWcBR/O32yUb'
if (password_verify($value, $hash)) {
    echo 'Success!';
} else {
    echo 'Failed!';
}
```
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/master/src/upload/application/controllers/home/register.php#L102

**Comment by LucasKovacs** [comment]
@danieluyo this is great, but we already went through a migration from md5 to sha-1.

We'll push this back until another mayor release

**Comment by LucasKovacs** [comment]
@BeReal86 this required quality check

**Comment by BeReal86** [comment]
encryption works fine. I just registered I tried encrypting from the admin section. No problem
