### ISSUE TITLE
[v3.1.0] Error Phalanx

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#217]
It works fine when there is no fleet movement. However, any fleet motion is faulty. The example is the same as the picture.

![phalanx](https://user-images.githubusercontent.com/16218107/35198918-2393d89e-ff07-11e7-9a23-a49a669ddabc.png)

**Comment by Juge-Gabranth-15** [comment]
I personnally change XXXX function because Phalanx can Only be used on Moon

> private function isPhalanxActive()
>     {
>         if (($this->currentplanet['building_phalanx'] != 0)
>             && ($this->row_data['user_id'] != $this->current_user['user_id'])
>             && ($this->row_data['planet_galaxy'] == $this->currentplanet['planet_galaxy'])
> 			&& ($this->currentplanet['planet_type']) == 3) {
> 
>             return $this->isInRange($this->formula->phalanxRange($this->currentplanet['building_phalanx']));
>         }
>     }

**Comment by BeReal86** [comment]
@Juge-Gabranth-15  thanks for help we will try it
