### ISSUE TITLE
Error en los enlace, del panel administrativo.

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#222]
http://localhost/xgproyect//admin.phpadmin.php?page=reset

Se duplican la pagina en los enlace.

Opinión: Eliminar la carpeta, public y llevar los archivos al root como estaba antes..

**Comment by agentcobra** [comment]
see https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/219c516e6cb96e36ab5b06fb82c43599f5e3aae1/src/upload/application/config/constants.php#L62-L63

**Comment by LucasKovacs** [comment]
This problem is with windows... the public folder has nothing to do with this. This issues is happening because of the DIRECTORY_SEPARATOR constant. It's working fine for me, some problem with windows users.

**Comment by LucasKovacs** [comment]
@FGServers this commit 45929e1dc2f15db83ba6b95f0aa3c043f5159fae should fix this

**Comment by FGServers** [comment]
si se soluciono el error de las url pero te pide actualizar y si no actualizas te tira error cuando queres entrar a otra pagina
