### ISSUE TITLE
Error en el panel administrativo

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#223]
![image](https://user-images.githubusercontent.com/2124810/41015823-5b6040e8-6922-11e8-87c2-bf93e0b0cdbe.png)
este es el error cuando queres entrar a una pagina

**Comment by agentcobra** [comment]
No problem for me (15dbff2, same on 219c516)
![image](https://user-images.githubusercontent.com/1831853/41017718-7ccb7fd4-6956-11e8-83b4-4e89faed26a8.png)

**Comment by LucasKovacs** [comment]
@FGServers this commit 45929e1dc2f15db83ba6b95f0aa3c043f5159fae should fix this, please let me know
