### ISSUE TITLE
Error url

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#226]
Error url y direccion de la barra 

```
<link rel="stylesheet" type="text/css" href="public\css\home/all.css">
--
  | <script type="text/javascript" src="public\js\home/jquery.tools.min.js"></script><style type="text/css"></style>
  | <script type="text/javascript" src="public\js\home/jquery.easing-1.3.pack.js"></script>
  | <script type="text/javascript" src="public\js\home/jquery.jparallax.js"></script>
  | <script type="text/javascript" src="public\js\home/jquery.fancybox-1.3.1.pack.js"></script>
  | <script type="text/javascript" src="public\js\home/jquery.validationEngine.modified.js"></script>
  | <script type="text/javascript" src="public\js\home/xgproyect.js"></script>
  | <script type="text/javascript" src="public\js\home/test.js"></script>
```
y la carpeta public se visualiza tambien deberia estar bloqueada

![image](https://user-images.githubusercontent.com/2124810/41266463-54000dce-6dcd-11e8-9955-01771b408e3c.png)

**Comment by BeReal86** [comment]
@FGServers Hi,
I installed the game after clean installation, there is no problem.
![111](https://user-images.githubusercontent.com/16218107/41290670-41fffa92-6e56-11e8-9950-64288b06824b.png)

**Comment by FGServers** [comment]
escribi /public/ en el enlace

**Comment by LucasKovacs** [comment]
@FGServers you're modifying the code, that's why it's breaking. Only bugs with clean installation are valid. I will close this.
