### ISSUE TITLE
[Consulta] como se puede integrar un bonus a estas variables

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#227]
`ProductionLib::productionAmount($metal_prod, $geologe_boost, $game_resource_multiplier), $post_percent`

**Comment by LucasKovacs** [comment]
El boost se lo das con el geologo... $geologe_boost

**Comment by FGServers** [comment]
Cierren ya descubrí como hacerlo saludos y muchas gracias
