### ISSUE TITLE
Preparar versión para el re diseño

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#228]
Hola estoy haciendo el re diseño con la versión 3.1.0 aca les dejo una muestra
![image](https://user-images.githubusercontent.com/2124810/41379474-6bf28aa8-6f38-11e8-85d3-b970e6fb543c.png)

Estoy teniendo problemas en integrar los almacenes a la otra sección ejemplo tuve que eliminar esto 
```
//DELETE CODE NO SIRVE
    /**
     * Build each building block
     * 
     */
    /*private function setListOfBuildingsItem($building_id)
    {
        
    }*/// DELETE CODE
```

por que el rediseño lleva una funcion count para que funcione el Slider

aca un ejemplo de que funciona 
![image](https://user-images.githubusercontent.com/2124810/41379548-a10bd802-6f38-11e8-9a14-b99e7ba7e669.png)

a que voy esto esta muy bien programada la versión pero debería estar preparada para un futuro re diseño.

tambien ya se deberia agregar el satelite solar a los recursos pero eso ya lo hice yo

**Comment by MahmutHizal** [comment]
Absolutely I agree. This functions like this mustn’t placed in class as for me. I think this functions is placed in an another template file.

**Comment by FGServers** [comment]
ya lo hice separando esto
`private function getAllowedBuildings()
    {
        $allowed_buildings = [
            'resources' => [
                1 => [1, 2, 3, 4, 12, 212],
                3 => [12]
            ],
            'station' => [
                1 => [14, 15, 21, 31, 33, 34, 44],
                3 => [14, 21, 41, 42, 43]
            ]
        ];

        return array_filter($allowed_buildings[$this->getCurrentPage()][$this->_planet['planet_type']], function($value) {
            return DevelopmentsLib::isDevelopmentAllowedStatus(
                    $this->_user, $this->_planet, $value
            );
        });
    }`

agregando esto
`private function getAllowedStorage()
    {
        $allowed_storage = [
            'resources' => [
                1 => [22, 23, 24],
                3 => [22, 23, 24]
            ],
            'station' => [
                1 => [],
                3 => []
            ]
        ];
        
        return array_filter($allowed_storage[$this->getCurrentPage()][$this->_planet['planet_type']], function($value) {
            return DevelopmentsLib::isDevelopmentAllowedStatus(
                    $this->_user, $this->_planet, $value
            );
        });
    }`

pueden cerrar trankilamente

**Comment by LucasKovacs** [comment]
XGP va a seguir su curso independientemente del rediseño. Esa función que quieren eliminar es parte de la lógica del controlador y no deberia ser modificada. Tal función esta allí porque construye la página, osea cumple la función de controller.
