### ISSUE TITLE
[v3.1.0] Mission Recycle error 500

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#233]
**Describe the bug**
Error in 500 after fleet 4 mission recycling

**To Reproduce**

**Expected behavior**
When I get to the fleet4 I get error 500 and it leaves me a log of errors that I leave attached

**Screenshots**
![image](https://user-images.githubusercontent.com/2124810/41816280-20a73770-7757-11e8-8486-01463e2871dc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - 1803 Compilacion 17134.112
 - Browser Chrome
 - Version Versión 67.0.3396.87 (Build oficial) (64 bits)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s9
 - OS: Android 8.1.1
 - Browser Chrome
 - Version 67.0.3396.87

**Comment by canaydemir** [comment]
:(

**Comment by FGServers** [comment]
mini fix in fleet4.php

search
`$MyDBRec = $this->_db->queryFetch(
            "SELECT u.`user_id`, u.`user_onlinetime`, u.`user_ally_id`, s.`setting_vacations_status`
            FROM " . USERS . " AS u, " . SETTINGS . " AS s
            WHERE u.`user_id` = '" . $this->_current_user['user_id'] . "'
                    AND s.`setting_user_id` = '" . $this->_current_user['user_id'] . "';"
        );`
and change for

`$MyDBRec = $this->_db->queryFetch(
            "SELECT u.`user_id`, u.`user_onlinetime`, u.`user_ally_id`, u.`user_authlevel`, s.`setting_vacations_status`
            FROM " . USERS . " AS u, " . SETTINGS . " AS s
            WHERE u.`user_id` = '" . $this->_current_user['user_id'] . "'
                    AND s.`setting_user_id` = '" . $this->_current_user['user_id'] . "';"
        );`

**Comment by LucasKovacs** [comment]
Fixed on v3.1 phase 2. The PR will be ignored until phase 2 is merged.
