### ISSUE TITLE
[v.3.0.4] Denfence and Shipyard Page After Install and Statistics Changes

### ISSUE THREAD

**Issue by MrSimh** [XGProyect/XG-Proyect-v3.x.x#235]
**Describe the bug**
After installing I changed some stats in admin and i see that.
(Just for having something to see in Defence and ship, i've changed buildings values)

### Possible solving :
` if (!empty($Element))`  where i see ` if ($Element != '')`
Line 262 Shipyard.php and 322 defense.php

**To Reproduce**
1. Go to Defense
2. See error

1. Go to Shipyard
2. See error

**Expected behavior**
I see some php error.

**Screenshots**
https://nsa39.casimages.com/img/2018/07/27/180727082722105261.png

**Desktop (please complete the following information):**
 - OS: WIn 10
 - Browser Chrome
 - Version latest

**Comment by MrSimh** [comment]
Ok , thank you.
I had trouble installing the 3.1

**Comment by LucasKovacs** [comment]
This issue was fixed on 3.1
