### ISSUE TITLE
[v3.1.0] Error 500  in the installation

### ISSUE THREAD

**Issue by MrSimh** [XGProyect/XG-Proyect-v3.x.x#236]
**Describe the bug**
Error 500 here : http://localhost/xgp3_1/xgp3.1.0b1/upload/public/install/index.php?page=installation&mode=step3

**To Reproduce**
1. Try to installing
2. Step 3 => error 500

**Screenshots**
The requested URL throw an error. Contact the game Administrator. That’s all we know.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version last

**Comment by MrSimh** [comment]
Works when i drop the table and i retry.
Very weird, i dont found the bug.

**Comment by BeReal86** [comment]
Hi,  I have done more than one experiment and used more than one internet browser. As a result I finished the installation without any errors.

please be sure to use php version 5.6+. The xampp we use when we test is 7.1.

<img width="948" alt="installing complete" src="https://user-images.githubusercontent.com/16218107/43551689-909f2580-95f0-11e8-823f-2dc541da1c78.png">
