### ISSUE TITLE
[v3.0.4] Can't build a ship

### ISSUE THREAD

**Issue by MrSimh** [XGProyect/XG-Proyect-v3.x.x#237]
**Describe the bug**
Can't build anything

Solution found : 
`$element = (int)$element;` Line 264 of UpdateResourceLib.php
He can find$element = '0202' and we need : 202 who is light cargo ID

**To Reproduce**
1. Go to shipyard
2. build something

**Expected behavior**

**Screenshots**
Undefined index: : 0202 in librairie DevelpmentLib 
and UpdateRessourceLib
I can see 10 error php likle that

**Additional context**
I feel anything i do i take a 500, is it realy 'stable' ?

**Comment by BeReal86** [comment]
Hi,

this and similar problems have been fixed in the next version. The issue will continue to be fixed.

**Comment by MrSimh** [comment]
Ok , thank you.
I had trouble installing the 3.1

**Comment by LucasKovacs** [comment]
This issue was fixed on 3.1
