### ISSUE TITLE
[v3.0.4] [v3.1.0] Galaxy error

### ISSUE THREAD

**Issue by MrSimh** [XGProyect/XG-Proyect-v3.x.x#238]
**Describe the bug**
Quote probelm 👎 
Right code : 
view, galaxy_body.php, Line 281
`onmouseover="return overlib('<table width=240><tr><td class=c colspan=2>{gl_legend}</td></tr><tr><td width=220>{gl_strong_player}</td><td><span class=strong>{gl_s}</span></td></tr><tr><td width=220>{gl_week_player}</td><td><span class=noob>{gl_w}</span></td></tr><tr><td width=220>{gl_vacation}</td><td><span class=vacation>{gl_v}</span></td></tr><tr><td width=220>{gl_banned}</td><td><span class=banned>{gl_b}</span></td></tr><tr><td width=220>{gl_inactive_seven}</td><td><span class=inactive>{gl_i}</span></td></tr><tr><td width=220>{gl_inactive_twentyeight}</td><td><span class=longinactive>{gl_I}</span></td></tr></table>', STICKY, MOUSEOFF, DELAY, 750, CENTER, OFFSETX, -150, OFFSETY, -150 );" onmouseout='return nd();'>`

**To Reproduce**
1. Go to Galaxy
2. See error

**Screenshots**
https://nsa39.casimages.com/img/2018/07/28/180728102731892392.png

**Comment by MrSimh** [comment]
was a bug with my french trad : 

<td width=220>7j d'inactivité</td><t

the ' here : 
d'inactivité

**Comment by agentcobra** [comment]
@MrSimh can you share your french translation files with me ? https://github.com/agentcobra/XG-Proyect-v3.x.x/tree/feature/french_translation

**Comment by MrSimh** [comment]
Yes, it's almost over and it needs testing. 
[french.zip](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/2243875/french.zip)

**Comment by FGServers** [comment]
this error its duplicate https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/231

fix Delete DIRETECTORY_SEPARATE

**Comment by FGServers** [comment]
Test de overlib 3.1.0 en English lang

**Comment by MrSimh** [comment]
True, Sorry for that

**Comment by BeReal86** [comment]
Hi, I've done a few tests, but as you said, there has not been an error.

There are two languages officially supporting English and Spanish. and we do the tests on them.

<img width="740" alt="galaxy" src="https://user-images.githubusercontent.com/16218107/43551928-7a6423fa-95f1-11e8-9ecd-8520b08c7470.png">
