### ISSUE TITLE
Bug with French Translation

### ISSUE THREAD

**Issue by MrSimh** [XGProyect/XG-Proyect-v3.x.x#239]
**Describe the bug**
Espionnage give an other big 500 **For those who have some french translation**

**Solution**
add addslashes in the subject var on the SQL query
upload\application\libraries\messenger\Messenger.php

**To Reproduce**
1. Launch an espionnage
2. go to overview
3. click on overview link to refresh after the probe arrived oin the planet targeted
4.see the error

**Expected behavior**

**Screenshots**
Error 500
Logs : 

`|::1|db|SQL Error|Database query failed: Erreur de syntaxe près de 'espionnage',
            `message_text` 	= '<table width="440"><tr><td class="c"' à la ligne 7 Last SQL Query: INSERT INTO xgp_messages SET
            `message_receiver` = '1',
            `message_sender` = '',
            `message_time` = '1532983507',
            `message_type` = '5',
            `message_from` = 'Quartiers gÃ©nÃ©raux',
            `message_subject` = 'Rapport d'espionnage',
            `message_text` 	= '<table width="440"><tr><td class="c" colspan="5">Ressources PlanÃ¨te mÃ¨re <a href="game.php?page=galaxy&mode=3&galaxy=1&system=1">[1:1:7]</a> le 30.07.2018 17:57:20</td></tr><tr><td width=220>MÃ©tal</td><td width=220 align=right>881</td><td>&nbsp;</td><td width=220>Cristal</td></td><td width=220 align=right>690</td></tr><tr><td width=220>DeutÃ©rium</td><td width=220 align=right>0</td><td>&nbsp;</td><td width=220>Energie</td><td width=220 align=right>0</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">Flotte</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">DÃ©fense</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">Batiments</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">Recherches</td></tr></table><br /><center><a href="game.php?page=fleet1&galaxy=1&system=1&planet=7&planettype=1&target_mission=1 ">Attaquer</a></center><center>Chance de dÃ©tection : 0 % </center>';|Where called: line 59 of application\core\Database <br/>(in C:\wamp\www\xgp31\upload\application\libraries\messenger\Messenger.php)|2018/07/30 17:57:20|
`

`|::1|db|SQL Error|Database query failed: Erreur de syntaxe près de 'espionnage',
            `message_text` 	= '<table width="440"><tr><td class="c"' à la ligne 7 Last SQL Query: INSERT INTO xgp_messages SET
            `message_receiver` = '1',
            `message_sender` = '',
            `message_time` = '1532983507',
            `message_type` = '5',
            `message_from` = 'Quartiers gÃ©nÃ©raux',
            `message_subject` = 'Rapport d'espionnage',
            `message_text` 	= '<table width="440"><tr><td class="c" colspan="5">Ressources PlanÃ¨te mÃ¨re <a href="game.php?page=galaxy&mode=3&galaxy=1&system=1">[1:1:7]</a> le 30.07.2018 17:57:20</td></tr><tr><td width=220>MÃ©tal</td><td width=220 align=right>884</td><td>&nbsp;</td><td width=220>Cristal</td></td><td width=220 align=right>692</td></tr><tr><td width=220>DeutÃ©rium</td><td width=220 align=right>0</td><td>&nbsp;</td><td width=220>Energie</td><td width=220 align=right>0</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">Flotte</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">DÃ©fense</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">Batiments</td></tr></table><table width="440" cellspacing="1"><tr><td class="c" colspan="5">Recherches</td></tr></table><br /><center><a href="game.php?page=fleet1&galaxy=1&system=1&planet=7&planettype=1&target_mission=1 ">Attaquer</a></center><center>Chance de dÃ©tection : 0 % </center>';|Where called: line 59 of application\core\Database <br/>(in C:\wamp\www\xgp31\upload\application\libraries\messenger\Messenger.php)|2018/07/30 17:57:20|
`

**Comment by MrSimh** [comment]
Found : 

Any accent in traduction is give very bad result.

**Comment by MrSimh** [comment]
addslashes every where ?

**Comment by BeReal86** [comment]
Hi, this is not a bug
Here 'you get the error because of this reagent.

```
$lang['gl_inactive_seven']					= '7j d\'inactivité';
$lang['gl_inactive_twentyeight']			= '28j d\'inactivité';
```

i think change to

```
$lang['gl_inactive_seven']					= '7j d\ inactivité';
$lang['gl_inactive_twentyeight']			= '28j d\ inactivité';
```

<img width="532" alt="french" src="https://user-images.githubusercontent.com/16218107/43552705-449b4e9e-95f4-11e8-986a-259e02b52858.png">
