### ISSUE TITLE
[v.3.1.0] Alliance menu

### ISSUE THREAD

**Issue by MrSimh** [XGProyect/XG-Proyect-v3.x.x#240]
**Describe the bug**
Cant define a constant like that in alliance.php
use const DPATH;
use const JS_PATH;

**To Reproduce**
1. Go to Alliance
2..see error

**Screenshots**
 Parse error: syntax error, unexpected 'const' (T_CONST), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in C:\wamp\www\xgp31\upload\application\controllers\game\alliance.php on line 24

**Additional context**
Delete 
use const DPATH;
use const JS_PATH;
Seems to work

**Comment by BeReal86** [comment]
Hi, I did not get any errors when I tried to install 3.1 beta 1 clean and enter the alliance page. I made an alliance and tried to see no problem. Could you please give more examples?

<img width="432" alt="alliance" src="https://user-images.githubusercontent.com/16218107/43552787-aade0764-95f4-11e8-9f0e-0f6f8f3e5ca9.png">

**Comment by MrSimh** [comment]
This can be a problem with the version of php, which version do you use?
Apparently this thing happen for  php <  5.6
it is correct ?

**Comment by BeReal86** [comment]
Yeah. Our version 7.1

We perform all our tests in this version.

**Comment by MrSimh** [comment]
Ok i have to update then. Thank you.

**Comment by MrSimh** [comment]
Same as
https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/236
It was the version which was a problem
