### ISSUE TITLE
[v3.1.0] No Messages sender

### ISSUE THREAD

**Issue by MrSimh** [XGProyect/XG-Proyect-v3.x.x#241]
**Describe the bug**
Dont know if its already know or not, so i ask;
Colonize a planet and see 

|::1|db|SQL Error|Database query failed: Incorrect integer value: '' for column 'message_sender' at row 1 Last SQL Query: INSERT INTO xgp_messages SET
            `message_receiver` = '1',
            `message_sender` = '',
            `message_time` = '1533303231',
            `message_type` = '5',
            `message_from` = 'Colonisation',
            `message_subject` = 'Rapport de colonisation',
            `message_text` 	= 'Les colons arrivent sur la planète [1:1:2], 	les colons commencent a construire la nouvelle colonie';|Where called: line 59 of application\core\Database <br/>(in C:\wamp64\www\XGP\src\upload\application\libraries\messenger\Messenger.php)|2018/08/03 10:35:07|

**To Reproduce**
Colonize a planet
See error

**Screenshots**
Error 500

**Additional context**
Can be solve by :
`if(empty($sender)){$sender = 0;}` in MessageOption.php

**Comment by LucasKovacs** [comment]
This issue was already fixed on 3.1.0 - phase 2, with a similar solution.
