### ISSUE TITLE
[v3.1.0] Changelog undefined index

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#246]
**Describe the bug**
Changelog error undefined index on line  on line 64 not detected IN_CHANGELOG this bug its reproduce on localhost a new instalation 

**To Reproduce**
1. Go to 'changelog'

**Expected behavior**
Notice: Undefined index: changelog in C:\xampp\htdocs\game\application\controllers\game\changelog.php on line 64

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\game\application\controllers\game\changelog.php on line 64

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1809
 - Browser Google Chrome 

 - Version Versión 70.0.3538.102 (Build oficial) (64 bits)

**Additional context**
Xampp php version 7.2

**Comment by LucasKovacs** [comment]
Fixed - it requires two new tables xgp_languages + xgp_changelog.

TODO: provide a way to edit the changelog
