### ISSUE TITLE
[v3.1.0 Beta 2] Solar plant consuming resources regardless if it's built or not

### ISSUE THREAD

**Issue by Urbanshenkie** [XGProyect/XG-Proyect-v3.x.x#247]
When building a solor plant when you resources are low , the resources are taken but the plant is not upgrading. speed everything x10

**Comment by djlolito** [comment]
+1

**Comment by BeReal86** [comment]
Please be more specific about the subject.

Thanks

**Comment by LucasKovacs** [comment]
Issue fixed
