### ISSUE TITLE
[Future Improvement] Bomber Ship New Settings

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#251]
**Bomber Ship New Settings:**
* Deuterium consumption will be 700 instead of 1000.
* New Fast Fire
* Gaus Ball (5)
* Plasma thrower (5)

<img width="605" alt="bomber" src="https://user-images.githubusercontent.com/16218107/66876029-f8e09700-efb8-11e9-8113-c83a9d2648c2.png">

**Comment by FGServers** [comment]
object_collection.php

` 211 => array('metal' => 50000, 'crystal' => 25000, 'deuterium' => 15000, 'energy' => 0, 'factor' => 1, 'consumption' => 700, 'consumption2' => 700, 'speed' => 17000, 'speed2' => 17000, 'capacity' => 580),`

`212 => array('shield' => 1, 'attack' => 1, 'sd' => array(202 => 0, 203 => 0, 204 => 0, 205 => 0, 206 => 0, 207 => 0, 208 => 0, 209 => 0, 210 => 1, 211 => 0, 212 => 0, 213 => 0, 214 => 0, 215 => 0, 401 => 0, 402 => 0, 403 => 0, 404 => 0, 405 => 0, 406 => 0, 407 => 0, 408 => 0)),`

**Comment by LucasKovacs** [comment]
Approved!
