### ISSUE TITLE
[Future Improvement] New Marketplace

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#253]
<img width="502" alt="Screenshot_10" src="https://user-images.githubusercontent.com/16218107/89738040-39485e80-da7e-11ea-822f-bf02b5d1bf16.png">
<img width="504" alt="Screenshot_11" src="https://user-images.githubusercontent.com/16218107/89738041-3b122200-da7e-11ea-83a4-442fec9f8c70.png">
<img width="488" alt="Screenshot_13" src="https://user-images.githubusercontent.com/16218107/89738042-3cdbe580-da7e-11ea-9676-de5f24b924d3.png">
<img width="498" alt="Screenshot_14" src="https://user-images.githubusercontent.com/16218107/89738043-3e0d1280-da7e-11ea-9cac-93abb1b4b66f.png">
<img width="499" alt="Screenshot_15" src="https://user-images.githubusercontent.com/16218107/89738045-3fd6d600-da7e-11ea-8ce2-bd9143dbb941.png">
<img width="503" alt="Screenshot_16" src="https://user-images.githubusercontent.com/16218107/89738046-41080300-da7e-11ea-945f-4d4f7051b49a.png">

**Comment by BeReal86** [comment]
It has been updated.

**Comment by BeReal86** [comment]
This feature has been removed on many OGame servers. It is available in very few. Let's leave this feature for last. It can be decided according to the situation.

**Comment by FGServers** [comment]
> This feature has been removed on many OGame servers. It is available in very few. Let's leave this feature for last. It can be decided according to the situation.

Fue removido en los nuevos universos, pero en los viejos universo esta activo.

**Comment by LucasKovacs** [comment]
Was it removed for good? Gone for ever, adios!. Or just until they refactor it?

**Comment by BeReal86** [comment]
Such a statement came from the team leader in our OGameTR forum.

`Hello OGameTR family,

The market will be closed at Quasar 169 ES on Monday, 23 November 2020.
We will share the calendar for marketplace closure in other countries / universes if it yields positive results.

Good games.`

According to a friend, abuse can be very comfortable. They say the same thing with fleet breaking. For example, you can sell all ships for 1k unit. This wouldn't be fair. and it says that when complained, it is removed in other universes.

There is no clear information at the moment. the only information is trying to be removed. Perhaps it will be modified later.

Therefore, this feature should be left last in the ranking.

**Comment by FGServers** [comment]
> Such a statement came from the team leader in our OGameTR forum.
> 
> `Hello OGameTR family,
> 
> The market will be closed at Quasar 169 ES on Monday, 23 November 2020.
> We will share the calendar for marketplace closure in other countries / universes if it yields positive results.
> 
> Good games.`
> 
> According to a friend, abuse can be very comfortable. They say the same thing with fleet breaking. For example, you can sell all ships for 1k unit. This wouldn't be fair. and it says that when complained, it is removed in other universes.
> 
> There is no clear information at the moment. the only information is trying to be removed. Perhaps it will be modified later.
> 
> Therefore, this feature should be left last in the ranking.

si al parecer lo van a eliminar pero seguramente lo van a mejorar para que no abusen de eso..

**Comment by LucasKovacs** [comment]
Closing this then. Since if new things will come and will be improved, this is no longer valid.

**Comment by BeReal86** [comment]
Yes, it is finalized with the new news below. The marketplace is closed in all universes.

<img width="1279" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/100086220-2ce5e700-2e5e-11eb-845c-b1b692e984e7.png">
