### ISSUE TITLE
[Future Improvement] Hyperspace technology linked to cargo capacity

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#257]
1. Small Cargo
2. Large Cargo
3. Recycler

- OGame Pioneers / Bermuda

Hyperspace Technology level 1 = %2 add capacity
Hyperspace Technology level 2 = %4 add capacity
Hyperspace Technology level 3 = %6 add capacity

<img width="626" alt="Hyperspace Technology" src="https://user-images.githubusercontent.com/16218107/67059000-ee143680-f15f-11e9-82da-0535b183143d.png">

- OGameUK/TR   Quasar/Octans

Hyperspace Technology level 1 = %5 add capacity
Hyperspace Technology level 2 = %10 add capacity
Hyperspace Technology level 3 = %15 add capacity

<img width="620" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/90806075-36265b80-e325-11ea-8410-b78990362718.png">
<img width="609" alt="Screenshot_2" src="https://user-images.githubusercontent.com/16218107/90806085-37f01f00-e325-11ea-8115-6c69003e576b.png">

Date of update:20.08.2020
The rate is set as 5% in games other than the test server.

**Comment by FGServers** [comment]
> Hyperspace Technology

Creo que lo cambiaron eso por 5% para todos si no me equivoco. 
En el rediseño que anterior se hizo la formula
`$this->_fleet_storage += $amount * ($price[$ship_id]['capacity'] * (1 + 0.05 *      $this->_research->getCurrentResearch()->getResearchHyperspaceTechnology()));`

en el infos

**Comment by BeReal86** [comment]
no, the last time I looked at it while testing it was a few months ago. It continues as I mentioned above.

**Comment by LucasKovacs** [comment]
@BeReal86 @FGServers this feature has been implemented. Requires a lot of testing since I had to modify missions, fleet movements and galaxy.

**Comment by BeReal86** [comment]
It's like in OGame. There was no problem with this feature. But I will post issues related to fleet missions in a moment.
