### ISSUE TITLE
[v3.1.0] Admin panel Warning

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#260]
**Describe the bug**

**To Reproduce**
1. Go to 'users'

**Expected behavior**
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\htdocs\XGPRoyect\application\controllers\adm\users.php on line 960

**Screenshots**
![image](https://user-images.githubusercontent.com/2124810/66967703-3d6f3f80-f058-11e9-93b0-c0222931823d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version Last

**Additional context**
Fix default
`case 'send_data':
continue ;
break;`

change for-
`case 'send_data':
continue 2;
break;`

**Comment by BeReal86** [comment]
in which version has this problem occurred

**Comment by BeReal86** [comment]
I didn't encounter any problems

<img width="1046" alt="ttt" src="https://user-images.githubusercontent.com/16218107/66968120-4548d700-f08c-11e9-9c8b-28d78d431550.png">

**Comment by FGServers** [comment]
i have php last version php 7.3.6 I already tried it with several installations

**Comment by BeReal86** [comment]
ok i test with php 7.3.10

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\htdocs\310-phase3\application\controllers\adm\users.php on line 960

**Comment by FGServers** [comment]
Small Fix
`case 'send_data': continue ;break;`

change for
`case 'send_data': continue 2; break;`
