### ISSUE TITLE
[v3.1.0] Messages Ok button error

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#262]
**Describe the bug**
ok button in messages problem

**To Reproduce**
1. Go to 'Messages'
2. Click on 'OK button'

**Screenshots**
<img width="827" alt="messages-e" src="https://user-images.githubusercontent.com/16218107/67055991-f6b24000-f152-11e9-8c1d-ea45b2ec81db.png">

**Desktop:**
 - OS: Windows 10 64bit
 - Browser Firefox, edge, chrome
 - Version lastest
Xampp PHP 7.3.10

**Comment by FGServers** [comment]
![image](https://user-images.githubusercontent.com/2124810/67056919-b340dd00-f124-11e9-9726-e51d5c61a40b.png)
Work fine for me last version message refractor
![image](https://user-images.githubusercontent.com/2124810/67056940-c5228000-f124-11e9-98dd-b9c8e4a87dd7.png)

**Comment by BeReal86** [comment]
No problem when Commander is active. Problem when commander is not active. Related images attached in the first message

**Comment by FGServers** [comment]
The error throws it at me when there is no message to delete

**Comment by LucasKovacs** [comment]
Fixed in commit  https://github.com/XGProyect/XG-Proyect-v3.x.x/commit/367817167c1de028bfc3f5c57eae665e80d4cfbd
