### ISSUE TITLE
[v3.1.0] Bug javascript overlib in galaxy

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#263]
**Describe the bug**
Bug javascript overlib in galaxy

**To Reproduce**
1. Go to 'galaxy'
2. Click on 'planet to overlib'

**Expected behavior**
Uncaught SyntaxError: Invalid Unicode escape sequence

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/2124810/67057863-a2926600-f128-11e9-80f4-4e958727b1ff.png)

**Comment by FGServers** [comment]
En el hosting lo acabo de testear funciona perfectamente

**Comment by LucasKovacs** [comment]
Entonces lo cierro?
