### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by djlolito** [XGProyect/XG-Proyect-v3.x.x#266]
Buenas tardes
Adjunto los bugs que he encontrado al bajarme la ultima rev de xgp.

game.php?page=changelog - en idioma español genera un error 500
creando este error:
Database query failed: Table 'xgp_changelog' doesn't exist Last SQL Query: SELECT c.`changelog_version`, c.`changelog_date`, c.`changelog_description` FROM `xgp_changelog` c LEFT JOIN `xgp_languages` l ON l.`language_id` = c.`changelog_lang_id` WHERE l.`language_name` = ( SELECT o.`option_value` FROM `xgp_options` o WHERE `option_name` = 'lang' ) ORDER BY c.`changelog_date` DESC

El problema reside en que en el instalador he marcado otro prefijo, y no lo ha configurado, si no que ha mantenido el xgp_

Estos errores se generaron despues de la instalacion de XGP:

| db | SQL Error | 2019/10/23 09:27:12 | Where called: line 85 of application\core\Database(in Options.php)
-- | -- | -- | -- | --
Database query failed: Table 'xgp_options' doesn't exist Last SQL Query: SELECT * FROM `xgp_options` WHERE `option_name` = 'lang';
| db | SQL Error | 2019/10/23 09:28:02 | Where called: line 85 of application\core\Database(in Options.php)
Database query failed: Table 'xgp_options' doesn't exist Last SQL Query: SELECT * FROM `xgp_options` WHERE `option_name` = 'lang';
 | php | 2 | 2019/10/23 06:28:04 | Where called: line 205 of(in Statistics_library.php)
arsort() expects parameter 1 to be array, null given
 | php | 2 | 2019/10/23 06:28:06 | Where called: line 205 of(in Statistics_library.php)
arsort() expects parameter 1 to be array, null given

**Comment by BeReal86** [comment]
exactly which version did you download and install? XGP v3.1.0 Beta 2?
Which PHP version do you use?

thanks for your feedback

**Comment by FGServers** [comment]
Me funciona bien con el ultimo comits instala de de 0 con el ultimo comits

**Comment by djlolito** [comment]
php version 7.1 
Version phase-3

**Comment by BeReal86** [comment]
thanks for your feedback.  
A series of adjustments are made in phase 3, so it is normal for some errors to occur.
