### ISSUE TITLE
[3.1.0] Vacation  mode

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#267]
In vacation mode, all production is 0.

<img width="929" alt="f-4" src="https://user-images.githubusercontent.com/16218107/67803742-b631bb00-fa9e-11e9-922c-775d0785268a.png">

 - OS: Windows
 - Browser: Firefox  v70
 - Version php 7.3.10

**Comment by FGServers** [comment]
mi solucion seria meter un if pero no es la idea 

pero agregando 

```
 if ($this->_current_planet['planet_type'] == 3 || $this->_current_user['preference_vacation_mode'] >= 0) {
            $game_metal_basic_income = 0;
            $game_crystal_basic_income = 0;
            $game_deuterium_basic_income = 0;
        }
```

se solucionaria pero no es la idea hacer if ahora

**Comment by LucasKovacs** [comment]
@BeReal86 this one is ready for test.

@FGServers fue la solución más simple. Y de paso hice algunas mejoras

**Comment by BeReal86** [comment]
works fine. I did not encounter any problems.
<img width="809" alt="Screenshot_9" src="https://user-images.githubusercontent.com/16218107/89644204-15d7b500-d8c0-11ea-8fbf-c1a52e4f46c7.png">
