### ISSUE TITLE
[Help wanted] Scraper Merchant language lines

### ISSUE THREAD

**Issue by LucasKovacs** [XGProyect/XG-Proyect-v3.x.x#268]
We need the original language lines for the scraper merchant in both English and Spanish, mostly in Spanish.

Initial research shows that for 35% and 75% there's a fixed language line while mixes many between those percentages. 

Here's a preliminary list, we also need the % offered when the message appeared so we can create some logic around the messages.
```
35%: Then let`s see what you`re willing to give out. > Veamos entonces qué está dispuesto a pagar.
45%: You won`t get a better offer in any other galaxy.
50%: I`m going to have to deduct the bullet holes from the price.
45% / 49% / 55% / 59% / 72%: You should be paying me to take this rubbish from you.
50% / 55%: I can`t give you much more for this rusty junk.
57% / 66%: My wife`s going to kill me...
40% / 44% / 60%: Do you want to bankrupt me?
44% / 61%: This offer is an absolute one-off exception.
65%: I`m a businessman, and not one of the welfare kind.
47% / 67% / 68% / 72% / 73%: But I`m already hardly making a profit out of this deal!
75%: That is my final word on the matter!
49%: I`ve got a family to feed!
71%: I can already hear the gloating jeers of my competitors.
```
Anyone can participate and collaborate.

**Comment by FGServers** [comment]
`41%` => En ninguna galaxia conseguirá una oferta mejor.

**Comment by FGServers** [comment]
en 57% me salio otra cosa 

![image](https://user-images.githubusercontent.com/2124810/67902504-1a5c8980-fb48-11e9-8bf1-0d5c6ad3d012.png)

**Comment by BeReal86** [comment]
`35%: Then let`s see what you`re willing to give out.
45% / 43% / 42% / 44% / 46% / 40%: You won`t get a better offer in any other galaxy.
47% / 58% / 65%: I`m going to have to deduct the bullet holes from the price.
66%: You should be paying me to take this rubbish from you.
50% / 55%: I can`t give you much more for this rusty junk.
67% / 55% / 59%: My wife`s going to kill me...
56% / 66% / 70% / 71%: Do you want to bankrupt me?
57% / 59%: This offer is an absolute one-off exception.
49% / 62% / 64% / 54%: I`m a businessman, and not one of the welfare kind.
47% / 67% / 68% / 72% / 73%: But I`m already hardly making a profit out of this deal!
75%: That is my final word on the matter!
46% / 63% / 49% / 65%: I`ve got a family to feed!
74% / %52: I can already hear the gloating jeers of my competitors.
59% / 50% / 46% / 56% / 41% / 72%: But I`m already hardly making a profit out of this deal! 
70% / 51%: I can’t give you much more for this rusty junk.
`

**Comment by LucasKovacs** [comment]
Language lines added to latest commit aa21a5d - v3.1.0 phase 3. Please fell free to add or make any corrections on those lines.

**Comment by FGServers** [comment]
TE confirmo 2 por ahora
![Sin título](https://user-images.githubusercontent.com/2124810/67948319-3d2c8380-fbc4-11e9-8773-a9c1274023aa.png)

**Comment by LucasKovacs** [comment]
@FGServers @BeReal86 I still need further verification on the Spanish Lines :)

**Comment by BeReal86** [comment]
I will start the necessary work :)

**Comment by FGServers** [comment]
ya no me quedan servidores donde registrarme jajajajajaj bueno voy a tener que registrarme en otros y scarles scans

**Comment by FGServers** [comment]
Te mando imágenes por mas q revise varias salen esas mismas ire publicando mas

![En ninguna galaxia conseguira una oferta mejor](https://user-images.githubusercontent.com/2124810/68515681-98174800-0260-11ea-8af2-4fd35bf5cbd1.png)
![Esta oferta es una excepcion absolutamente unica](https://user-images.githubusercontent.com/2124810/68515682-98174800-0260-11ea-9725-5d066026817b.png)
![Me tendrias que estar pagando usted a mi por quedarme con su chatarra](https://user-images.githubusercontent.com/2124810/68515683-98174800-0260-11ea-8096-c31b4aa5158c.png)
![No te puedo nada más por esta basura oxidada 2d](https://user-images.githubusercontent.com/2124810/68515686-98174800-0260-11ea-8544-ef76724bb7e7.png)
![No te puedo nada más por esta basura oxidada](https://user-images.githubusercontent.com/2124810/68515688-98afde80-0260-11ea-924d-5a999c86edb0.png)
![Veamos entonces qué está dispuesto a pagar](https://user-images.githubusercontent.com/2124810/68515690-98afde80-0260-11ea-89ad-72c4b20dfae1.png)

**Comment by LucasKovacs** [comment]
Gran trabajo @FGServers ! Creo que estamos bien. Voy a cerrar
