### ISSUE TITLE
[v3.1.0] Permisos al config.php

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#269]
**Describe the bug**
Como dice acabo de cambiar los permisos del config.php a 640 pero el mensaje en el administrador sigue apareciendo estoy haciendo algo mal
![1](https://user-images.githubusercontent.com/2124810/67894140-b382a480-fb36-11e9-84f4-adf3081b35c7.png)

![2](https://user-images.githubusercontent.com/2124810/67894168-c5644780-fb36-11e9-97cf-6d631a2c0d49.png)

**Comment by LucasKovacs** [comment]
Es un error que esta hace rato, tengo que revisarlo para ver cual es la numeración correcta

**Comment by FGServers** [comment]
Te juro que recién me di cuenta como no trabajaba con el hosting..

**Comment by LucasKovacs** [comment]
@FGServers listo corregido... cualquier permiso que bloquee escritura lo toma. Como 440, 400. asa
