### ISSUE TITLE
Planet Fields

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#27]
It Is the problem?
if you look at the stage, it is estimated there is no problem in the area.
if you add the building unit of the admin control panel. field does not appear on the planet
I raise two building units. I added two building units from the admin control panel.

![2-2](https://cloud.githubusercontent.com/assets/16218107/12705169/ac449050-c874-11e5-8627-25ea0e2a4356.png)

**Comment by XGProyect** [comment]
Fixed! It was an admin cp problem when you add stuff.
