### ISSUE TITLE
[v3.1.0] Changelog error

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#270]
**Describe the bug**
`Uncaught TypeError: Argument 1 passed to application\libraries\DebugLib::error() must be of the type integer, string given, called in /application/core/Database.php on line 447 and defined in /application/libraries/DebugLib.php:126 Stack trace: 
#0 /application/core/Database.php(447): application\libraries\DebugLib->error('Database query ...', 'SQL Error') 
#1 /application/core/Database.php(256): application\core\Database->confirmQuery(false) 
#2 /application/models/game/changelog.php(60): application\core\Database->queryFetchAll('SELECT\n ...') 
#3 //application/controllers/game/changelog.php(65): application\models\game\Changelog->getAllChangelogEntries() 
#4 /application/controllers in /application/libraries/DebugLib.php on line 126`

Versión ultimo commits idioma del juego activado ingles.

**Comment by LucasKovacs** [comment]
@FGServers el error ese parece que es por que te falta alguna de las nuevas tablas. Fijate corriendo el script the upgrade o instalando de 0. De todas formas envie un fix para que no salga el error del tipo de dato.
