### ISSUE TITLE
[Mejora Futura] Boton max construir con comandante

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#273]
Agregar el boton max con el comandante
![image](https://user-images.githubusercontent.com/2124810/67907915-5f88b780-fb58-11e9-8428-7ea05605c88c.png)

**Comment by BeReal86** [comment]
this feature will already be in the original ogame new officers.
Covers all functions

https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/250
