### ISSUE TITLE
[Panel de administración/Bug] Página Usuario

### ISSUE THREAD

**Issue by Dokman** [XGProyect/XG-Proyect-v3.x.x#279]
**Describe the bug**
Si clicas a la página de usuarios para poder modificar eliminar o insertar usuarios, me da error 500

**To Reproduce**
1. Go to 'admin panel'
2. Click on 'users'
3. See error

**Expected behavior**
Se espera que te deje gestionar los usuarios.

**Screenshots**
![image](https://user-images.githubusercontent.com/2290904/68372983-2a74fa00-0142-11ea-91bb-2b9c68bd30cc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest

**Comment by BeReal86** [comment]
Que version de XGP estas usando?

**Comment by Dokman** [comment]
la 3.10-phase-4

**Comment by LucasKovacs** [comment]
@Dokman gracias por tu reporte, lo investigaremos

**Comment by LucasKovacs** [comment]
@Dokman que version de PHP usas?

**Comment by Dokman** [comment]
7.3.9

**Comment by LucasKovacs** [comment]
@Dokman puedes probar esta solución?

https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/260

**Comment by LucasKovacs** [comment]
@Dokman puedes probar esta solución?  Commit 16ea4e5

**Comment by Dokman** [comment]
claro ahora mismo

**Comment by Dokman** [comment]
Sigue el bug, he entrado con el Chrome mobile y sigue dándome error 500

**Comment by LucasKovacs** [comment]
@Dokman 

Abre tu archivo common.php ubicado en application/core

Cambia en la siguiente linea el 0 por 1.
`ini_set('display_errors', 0);`

Vuelve a intentar y pega aquí el error que ves por favor

También busca en application/logs y envía cualquier log de errores que tengas allí

**Comment by Dokman** [comment]
|::1|db|SQL Error|Database query failed: Table 'xgproyect.xgp_options' doesn't exist Last SQL Query: SELECT * 
                    FROM `xgp_options` 
                    WHERE `option_name` = 'lang';|Where called: line 85 of application\core\Database <br/>(in C:\xampp\htdocs\ogame\application\core\Options.php)|2019/10/23 21:45:03|

php|2|"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?|Where called: line 43 of  <br/>(in C:\xampp\htdocs\ogame\public\admin.php)|2019/10/25 15:33:17|

**Comment by LucasKovacs** [comment]
Tenes 2 problemas. El primero se soluciona actualizando los archivos a lo más reciente del branch 3.10-phase-4.

El segundo problema parece estar en tu instalación. No esta encontrando la tabla  xgp_options. Vas a tener que revisar si la instalación se completo bien

**Comment by Dokman** [comment]
ok, entonces hare otra clean install despues

**Comment by BeReal86** [comment]
I did a clean installation with the last updated phase 4 and tested it. not have bug.  working solution.

**Comment by FGServers** [comment]
Probé la phase 4 en mi hosting y funciona bien la edición.. de usuario, también crear nuevos usuarios

**Comment by Dokman** [comment]
ya esta funcionando hago un close de esto

**Comment by LucasKovacs** [comment]
duplicated #260
