### ISSUE TITLE
[3.1.0] Buildings sometimes do not rise.

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#280]
When a unit upgrade time expires on the building page, the page does not refresh, and it says finish / continue.

Other than that, as shown in the pictures below. The level is raised but sometimes the level does not rise and remains the same.

As this problem is happening when the building cannot be upgraded again when resources are generally low.

**Desktop (please complete the following information):**
 - OS: Windows 10 / smartphone
 - Browser: Firefox
 - Version lastest

php 7.3.10
MySQL Version  5.5.5-10.3.18-MariaDB-cll-lve
XGP 3.1.0 Phase 4

![WhatsApp Image 2019-11-07 at 22 19 16](https://user-images.githubusercontent.com/16218107/68424791-d4da3500-01b5-11ea-85a7-fce35d7d78a8.jpeg)
![WhatsApp Image 2019-11-07 at 22 19 22](https://user-images.githubusercontent.com/16218107/68424792-d4da3500-01b5-11ea-9865-40a95375688a.jpeg)

**Comment by LucasKovacs** [comment]
@BeReal86 fixed on v31 phase 4.
