### ISSUE TITLE
[v3.0.4 to v3.1.0] Update Error

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#281]
**Describe the bug**
This error occurs when the v3.0.4 version update attempts

**To Reproduce**
1. Go to 'Admin panel'
2. Click on 'Left Menu and Update'
3. 'update start'

<img width="1920" alt="update error2" src="https://user-images.githubusercontent.com/16218107/68497018-a6fff980-0264-11ea-9e0f-bdb573769580.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version Lastest

PHP 7.3.10

**Comment by BeReal86** [comment]
<img width="1920" alt="update error" src="https://user-images.githubusercontent.com/16218107/68530040-9bb8d680-0315-11ea-8c41-be9910cd1feb.png">

**Comment by LucasKovacs** [comment]
@BeReal86 this issue has been fixed, although version 3.0.4 has a problem so I have created this guide https://github.com/XGProyect/XG-Proyect-v3.x.x/wiki/How-to-update-from-v3.0.4-to-v3.1.x

**Comment by BeReal86** [comment]
After replacing all files, the error will appear when you enter the url as below.

http://{your-site}.com/admin.php?page=update

<img width="1920" alt="aaa" src="https://user-images.githubusercontent.com/16218107/68547603-751d9d00-03f4-11ea-98fd-98e8ae2beec9.png">

**Comment by LucasKovacs** [comment]
I'm seeing your url... you're not in admin.php... you have to be there

**Comment by BeReal86** [comment]
I was there. but the url returns here and errors occur.

**Comment by LucasKovacs** [comment]
1. Replace all files
2. Follow the guide
3. Go to admin.php not admin.php?page=update

**Comment by BeReal86** [comment]
@LucasKovacs  Yeah, like you said, I did everything. Please check I sent a few files.

**Comment by LucasKovacs** [comment]
@BeReal86 please check the updated guide https://github.com/XGProyect/XG-Proyect-v3.x.x/wiki/How-to-update-from-v3.0.4-to-v3.1.x

**Comment by BeReal86** [comment]
transactions successful.

<img width="1920" alt="asd" src="https://user-images.githubusercontent.com/16218107/68549490-8624d900-0409-11ea-8f1f-b42ae1a309dd.png">
