### ISSUE TITLE
[v3.1.0] Install Select Language

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#282]
**Describe the bug**
An error occurs when the language option is selected as shown in the illustration on the installation screen.

**To Reproduce**
1. Go to 'install'
2. Click on 'select language'
3. click select language and select

**Screenshots**
<img width="1920" alt="install language select error-" src="https://user-images.githubusercontent.com/16218107/68497685-2e01a180-0266-11ea-9cb6-f62f9fe9554d.png">

<img width="1920" alt="install language select error" src="https://user-images.githubusercontent.com/16218107/68497684-2e01a180-0266-11ea-9d74-9b3f271e7a7e.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version Lastest

PHP 7.3.10

**Comment by FGServers** [comment]
yo vi un error que no toma la carpeta osea si lo pongo en una carpeta al instalador me tira error de ruta ejemplo si selecciono idioma español

me queda asi localhost/install

**Comment by LucasKovacs** [comment]
@FGServers no entendi el error que tenes. De todas formas la carpeta install no deberias cambiarla de lugar

**Comment by FGServers** [comment]
> @FGServers no entendi el error que tenes. De todas formas la carpeta install no deberías cambiarla de lugar

si lo pones en el root funciona bien, si lo pones en el root/carpeta/codigo el juego cuando apretas para seleccionar el lenguaje se vuelve al root/install en ves de localhost/xgp/install vuelve a localhost/install no detecta la carpeta de donde esta el codigo

**Comment by FGServers** [comment]
Prueba esta solucion....
Busca en FunctionsLibs
`setcookie('current_lang', $lang);`

y debajo agrega esto

`self::redirect(SYSTEM_ROOT);`

hay que probarlo también fuera de un carpeta o folder

**Comment by MahmutHizal** [comment]
https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/166

**Comment by LucasKovacs** [comment]
Fixed! @FGServers aun quiero buscar una mejor forma para manejar sub directorios. Por eso no inclui el redirect.

**Comment by FGServers** [comment]
> 
> 
> Fixed! @FGServers aun quiero buscar una mejor forma para manejar sub directorios. Por eso no inclui el redirect.

no te procupes yo solo estaba probando jajajaja
