### ISSUE TITLE
[Mejora Futura] Regalar materia oscura a todos los users

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#283]
Se podría agregar alguna opción de agregar materia oscura a todos los usuarios... como hacen en en el server beta de ogame.

**Comment by MahmutHizal** [comment]
I think it's not just like that. With a little bit more advanced coding, more detailed user editing can be made. 
For example: A separate page should be created in the Admin panel and certain conditions must be defined. Example: If the member has been with us for over a month, text user Or give to member 2000 metal. 
This idea may seem like a difficult coding at first, but if the system is developing in the future for this idea, many codes in the system can be added and personalized from this section.

**Comment by BeReal86** [comment]
That's a good idea. Actually, there's something similar. An award system at the original OGame can be developed in this.
As shown in the picture, it gives an award day by day after the registration date.
<img width="492" alt="rewards" src="https://user-images.githubusercontent.com/16218107/68534923-a8582180-034b-11ea-88e0-911cd5fcdf0a.png">

**Comment by MahmutHizal** [comment]
> That's a good idea. Actually, there's something similar. An award system at the original OGame can be developed in this.
> As shown in the picture, it gives an award day by day after the registration date.
> <img alt="rewards" width="492" src="https://user-images.githubusercontent.com/16218107/68534923-a8582180-034b-11ea-88e0-911cd5fcdf0a.png">

Yes true. Such a system should be set up logically rather than coding.

**Comment by FGServers** [comment]
Rewards only active in pionners servers on oficial serves its not active. they are confusing things I am saying to add a section in the amins section of adding dark matter when registering or pressing a button to give as a gift as does the test server that resets the mo to all users giving 10 million .. they are confusing

**Comment by BeReal86** [comment]
nobody is confusing.  @FGServers admin You're talking about adding darl matter to all players from the admin panel.  @MahmutHizal , on the other hand, talks about giving some kind of reward in the game for a certain period of time.  and I have expressed a similar system. mahmut hizal probably knows all the players to add mineral or dark matter XGP v2.9 version we used.

**Comment by LucasKovacs** [comment]
I think both are good ideas... @BeReal86 can you please set this issue one on a Milestone based on what we discussed before :)

**Comment by BeReal86** [comment]
@LucasKovacs 
It is written on the road map. I have some examples of code to add to all players.

**Comment by LucasKovacs** [comment]
@FGServers this feature has been implemented. From the premium section of the admin panel you can set any amount of dark matter that you want to give to new players.

@BeReal86 reopen is there's any issue
