### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by Nykus** [XGProyect/XG-Proyect-v3.x.x#284]
Hello friends I am Portuguese I am a member of xgproyct for many years, I have a question how do I change the files I have in Portuguese language to work in version v.3.x.x 

need help thanks friends

**Comment by BeReal86** [comment]
I recommend using XGP v3.1.0 for the language file. But the more stable version has not been released.

If you already look at the language files, some changes are available. You can find and replace the terms in the old version in the new language file. Of course, I suggest you quote the Original OGame when writing the terms. It's more accurate.

**Comment by LucasKovacs** [comment]
@Nykus as BeReal86 already said the languages files on 3.1.0 are pretty much the same as v3.0.4 and below. But that will be slowly changing. The idea is to move the language lines from the current files to individual smaller files corresponding to their controller own controller.

So for example the overview will have its own language file, the same the buildings controller, or the galaxy controller and so on.

I recommend you to read the following two Wiki articles, which might help:
https://github.com/XGProyect/XG-Proyect-v3.x.x/wiki/How-to-create-or-edit-a-Language-file
https://github.com/XGProyect/XG-Proyect-v3.x.x/wiki/How-to-include-and-use-language-files-into-your-project

**Comment by Nykus** [comment]
Thank you very much I was glad not to let xg proyect disappear
