### ISSUE TITLE
[v3.1.0-phase 4] Modo vacaciones

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#288]
**Describe the bug**
Al activar el modo vacaciones con el ultimo comits tira este error

**To Reproduce**
1. Go to 'overview'

**Expected behavior**
Uncaught Error: Class 'application\libraries\Timing_library' not found in C:\wamp64\www\XGProyect\application\libraries\TemplateLib.php:359 Stack trace: #0 C:\wamp64\www\XGProyect\application\libraries\TemplateLib.php(99): application\libraries\TemplateLib->gameNavbar() #1 C:\wamp64\www\XGProyect\application\controllers\game\overview.php(123): application\libraries\TemplateLib->display('
\r\n
build_page() #3 C:\wamp64\www\XGProyect\public\game.php(59): application\controllers\game\Overview->__construct() #4 {main} thrown
in C:\wamp64\www\XGProyect\application\libraries\TemplateLib.php on line 359

**Screenshots**

PHP 7.3.6
MySQL: 5.6

Fix change in templatelib.php
`use application\libraries\Timing_library as Timing;`

for
`use application\libraries\TimingLibrary as Timing;`

**Comment by LucasKovacs** [comment]
Cierro debido a que no me diste tiempo de mandar todos los commits del día.
