### ISSUE TITLE
[3.1.0 Beta3] mines are not upgrading although the resources are paid

### ISSUE THREAD

**Issue by Meatroach** [XGProyect/XG-Proyect-v3.x.x#290]
Hi. Im a fan of this project and were finally able to install the latest build. i encountered an issue when testing the game

**Describe the bug**
if i build an mine it sometimes wont increase a level although i paid the resources

**To Reproduce**

for testing purpose I increased the tempo (100/100/100)

1. Go to Resources-Tab
2. Click on "build" on any mine
3. wait for the time to pass
4. click on "continue" (where you could click on build beforehand)
5. level of mine is still the same as before although the resources got paid

**Expected behavior**
level should increase when paid for upgrade

tested on Firefox Webbrowser
 
 **Server (please complete the following information):**
 - PHP Version: 7.1
 - MySQL Version: 10.1.38-MariaDB

**Comment by Meatroach** [comment]
this does not happen every time and was a problem at the beginning of setting up the base. maybe the tempo was to fast?

**Comment by Meatroach** [comment]
I just saw the closed-tab on github with this exact issue, sorry im new to this :-)

**Comment by BeReal86** [comment]
Thank you for your feedback. Yes, this issue was fixed before. We continue to work. Thank you for following us. Please feel free to report whatever happens.
Thanks
XGP Team
