### ISSUE TITLE
New Starsystem for New Players

### ISSUE THREAD

**Issue by Meatroach** [XGProyect/XG-Proyect-v3.x.x#291]
It would be very nice if we had an option for new players to spawn in a new, uncolonized star system!

3 of my Friends tried my new server and we were all in one star system. although this isnt as bad it would be great to start in an brand new system :)

**Comment by LucasKovacs** [comment]
@BeReal86 / @FGServers any of you know how does OGame works in this matter? I thought our logic was correct and new players were placed closed to each other. This is a feature that to me does not make any sense, unless OGame do works like this.

**Comment by BeReal86** [comment]
![resim](https://user-images.githubusercontent.com/16218107/234078849-8efbef1f-cb3c-4c6e-8eaa-f41ed74312e8.png)

![resim](https://user-images.githubusercontent.com/16218107/234078777-46348209-3e9e-4bcc-ad12-43cf1329eaad.png)

![resim](https://user-images.githubusercontent.com/16218107/234078953-bd6c4573-90ae-4183-abc2-a8c100f85047.png)

![resim](https://user-images.githubusercontent.com/16218107/234079124-61df7983-ac2a-42af-8626-a1fc1c686c80.png)

![resim](https://user-images.githubusercontent.com/16218107/234079192-b0f6dc25-d9f0-48a9-a6d1-d1039178c345.png)

![resim](https://user-images.githubusercontent.com/16218107/234079228-e6072496-31e7-4202-9d30-590420aab47d.png)

@LucasKovacs  I observed 1-2 days of newly opened universes. In general, a maximum of 5 players are assigned to each system, as seen in the pictures. There are at least 2 people in the system,  the next systems and galaxies are empty. While reviewing, a new player registered and the number of players in the last system increased to 3.

![resim](https://user-images.githubusercontent.com/16218107/234079709-bef1570d-e2d2-4407-a8f9-d45afd89977e.png)

**Comment by LucasKovacs** [comment]
Good stuff

**Comment by FGServers** [comment]
Ya me voy a fijar en las api por que creo q almanecena como genera eso

**Comment by LucasKovacs** [comment]
The logic has been improved to work like OGame does, I know the user here was asking something different, but this way it will get the result faster. Now only 5 planets maximum will be occupied per system. And if by any reason all planets in all systems and all galaxies are occupied the script will start again from the beginning until it finds a free position.

Also, related to what @Meatroach asked, three new constants have been introduced which can scattered planets a bit more. By default planet location works like OGame occuping positions 4, 6, 8, 10 and 12, then continuing to the next system and finally to the next galaxy.

```
/**
 * New accounts planet position separation
 * By default new players are separated by just 1 galaxy and/or 1 system
 * Changing these factors can increase the initial separation
 */
define('GALAXY_SEPARATION_FACTOR', 1);
define('SYSTEM_SEPARATION_FACTOR', 1);
define('PLANET_SEPARATION_FACTOR', 1);
```

These constants will allow to increase the amount of galaxies and systems between new players.
