### ISSUE TITLE
I offer my help

### ISSUE THREAD

**Issue by GrandNuageDeMagellan** [XGProyect/XG-Proyect-v3.x.x#292]
@LucasKovacs  I find your project really cool, and I want to give you my help.

- I can deliver an FR translation to you within 7 days if you wish to start.
- Then set up a server with a few players for the bug report.
- Then offer you a skin with some image changes in .gif (I have already tested this to have for example planets that rotate).

- And finally help you on the development (php, java etc).

I await your consent so as not to work for nothing.

Cordially.

**Comment by GrandNuageDeMagellan** [comment]
I have 50% of the full fr translation, and i have a prototype for a new design, But I don't want to touch the code without knowing what you're working on.

**Comment by FGServers** [comment]
Multilang it's bad idea

**Comment by GrandNuageDeMagellan** [comment]
Technicaly i have 1500 french players, if the game is in english 50 players max , and i have many idea to present in this good project ;)

**Comment by GrandNuageDeMagellan** [comment]
https://github.com/GrandNuageDeMagellan/XG-Proyect-v3.x.x I lunch this, if you want merge dont hesite ;)

**Comment by FGServers** [comment]
This is old code the new it's files separete in many

**Comment by GrandNuageDeMagellan** [comment]
Yes I saw my push error ^^

**Comment by BeReal86** [comment]
If you have any questions, please open it again.
