### ISSUE TITLE
admin.php?

### ISSUE THREAD

**Issue by Nykus** [XGProyect/XG-Proyect-v3.x.x#294]
Alert!
The config.php file can be written, it is recommended to be placed in chmod 440 (read only).
A new version is available. Click here to download it.
install/ directory detected. For safety reasons you must rename or delete it.
Your system and DB versions are different, Update now! to avoid issues.

Update from version v3.0.0 to v3.0.4

Ok! Update completed!
Update

                Array
(
    [0] => ALTER TABLE `xgp_fleets`  ADD `fleet_fuel` BIGINT(11) NOT NULL DEFAULT '0'  AFTER `fleet_resource_deuterium`;
    [1] => UPDATE `xgp_options` SET `option_value` = '3.0.4' WHERE option_name = 'version';
)

This is v3.0.4 version    

I update but I always have the same page

**Comment by FGServers** [comment]
uncheck the checkbox and test

**Comment by BeReal86** [comment]
Hi, @Nykus 

as he said in his friend  _uncheck the checkbox and test_

I suggest you wait for v3.1 version for a more stable version.
