### ISSUE TITLE
[NEED HELP] Error 500 during install

### ISSUE THREAD

**Issue by KasperDL** [XGProyect/XG-Proyect-v3.x.x#295]
Hi! I'm very new to using PHP & SQL, and I am having some issues installing my XGP server. During Step 3, no matter what I do, I get error 500 and can't proceed. 

This is my current PHP version:
Current PHP version: 7.3.10

What can I do to fix this?

Thanks!

**Comment by FGServers** [comment]
Version

**Comment by KasperDL** [comment]
Ah, sorry! The version of XGP I am using is 3.0.4

**Comment by FGServers** [comment]
use 3.1.0 release beta

**Comment by KasperDL** [comment]
Is there something different I need to do to install that version? I'm not getting the an installer, and instead I get sent to a directory overview of the upload folder when I'm trying it via AppServ.

Sorry for the noob questions!

**Comment by BeReal86** [comment]
Hi, @KasperDL 

Nothing extra is required to install.  Just as you have installed the version before, you can easily install it.
