### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by franyo78** [XGProyect/XG-Proyect-v3.x.x#297]
Dear Lucas!

I would need your help, I have downloaded your XG Proyect v3.x.x. But now i didn't find any help to install this on Linux, could you help me step-by-step?

Thanks for helping: franyo78!

(Because of your Name, are you maybe Hungarian?)

**Comment by Nykus** [comment]
Hello use PHP 5.4 5.6 
only

**Comment by BeReal86** [comment]
@franyo78 Hi,
Upload the contents of the upload file in the version you downloaded

Lucas is not hungarian :))

**Comment by LucasKovacs** [comment]
@franyo78 I'm not Hungarian, but my family was :) so I'm 50% Hungarian haha

Please use php 7.1+ to install XGP
