### ISSUE TITLE
[Help needed] How to install XG-Proyect-v3.x.x-310-phase-4

### ISSUE THREAD

**Issue by DaPike** [XGProyect/XG-Proyect-v3.x.x#298]
Hi to all,

I hope there is still support for this script.
I've tried version 3.04 but on PHP 7.4.3 it isn't working very well.
So I read that the new phase 4 could work.

But I don't how to install this version.

Can someone help me please?
I really love this great work and I will also try to translate the whole game to german if possible.

Thanks a lot for support.

**Comment by MahmutHizal** [comment]
what kind of problem did you encountered

**Comment by DaPike** [comment]
The problem is, I don't know how to install the XG-Proyect-v3.x.x-310-phase-4 version.

With version 3.0.4 I get ERROR500 after building the first spy satelite.
Nothing is working any more.

So I want to make a fresh install and try verison 310 phase 4. But I don't know how I can do this.

**Comment by MahmutHizal** [comment]
Have you tried to access /install directory from your browser?

**Comment by DaPike** [comment]
XG-Proyect-v3.x.x-310-phase-4 has no install!
And when I copy the contend over the version 3.0.4 error 500 appears.

So how can I install this version the right way?

**Comment by MahmutHizal** [comment]
Okay. I don’t understand you(you means, your problem about installation, triggered errors, etc) for now because of I cannot access any pc. Please wait for a while. Im gonna help you friend.

**Comment by MahmutHizal** [comment]
> 
> 
> Have you tried to access /install directory from your browser?

I am access `/install` directory. Directly.
and installed very clearly on my testing server(linux).
![Ek Açıklama 2020-05-25 142736](https://user-images.githubusercontent.com/7260763/82809094-fd94f400-9e93-11ea-894d-b5ab8eac0caf.png)

**Comment by DaPike** [comment]
XG-Proyect-v3.x.x-310-phase-4 has no install!

**Comment by MahmutHizal** [comment]
> 
> 
> XG-Proyect-v3.x.x-310-phase-4 has no install!
> 
> Can you give me a download link for this verison that you are using?
> Because I have only this:
> 
> ![ogame](https://user-images.githubusercontent.com/6161720/82809873-62991b80-9e8d-11ea-816a-f3f1213dea42.jpg)

you have only one thing to do. `localhost/[your xgp directory]/install`. 
I'm gonna explain that clearly as i can.

XGP has a file that named `.htaccess`. If you open this file, you will show this:
```html
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule  ^$ public/    [L]
    RewriteRule  (.*) public/$1 [L]
</IfModule>
```

> Resource: https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/310-phase-4/src/upload/.htaccess

So, if you know what is .htaccess, you understand what i am talking about. And the other hand if you dont know .htaccess file, i'll explain that too.

This file is an apache configuration file as simply exlpained. `RewriteRule` THING is like a mirror directory or url. Well, `RewriteRule  (.*) public/$1 [L]` means; if you want to access any file where located in `/public` directory, you can just use root directory to access this file. For example: The `/install` directory was located in `/public` directory. Okay. We want to access xgp installation, right?
We have to open a browser (like Chrome) and write this url to their address bar. 

`localhost/[your xgp directory]/install`

I am waiting your installation 😄

**Comment by DaPike** [comment]
Thanks a lot for support.
But everything I try ends here:

![ogame3](https://user-images.githubusercontent.com/6161720/82822176-a1d36680-9ea5-11ea-9d07-3865b0f2086c.jpg)

I entered following adress in the browser (tested with FF and Chrome)

http://planetwars.ddnss.de/pw

Then the browser try to open

http://planetwars.ddnss.de/pw/install

and it ends with ERROR 500.

**Comment by MahmutHizal** [comment]
Downgrade your  php version like 7.1. 

Source: https://stackoverflow.com/questions/61054418/php-7-4-deprecated-get-magic-quotes-gpc-function-alternative

**Comment by FGServers** [comment]
I'm tried fixing this bug

**Comment by BeReal86** [comment]
Hi @DaPike ,
Thank you for choosing us. Our advice to you is to use 7.1 as php version.

but generally there is no problem with the installation

**Comment by DaPike** [comment]
Ok. And thanks for help.
But I cannot downgrade to PHP 7.1.

So I'm not able to use this script.

I'm very sad about this.

**Comment by MahmutHizal** [comment]
> Ok. And thanks for help.
> I'm now on php 7.1
> 
> But same error!!
> 
> ![ogame4](https://user-images.githubusercontent.com/6161720/82878254-887cf980-9f3b-11ea-8e1e-b684194119c1.jpg)
> 
> So what can I do?

May you send log file

**Comment by DaPike** [comment]
The same error:

`|MY_IP_ADRESS|php|8192|Function get_magic_quotes_gpc() is deprecated|Where called: line 69 of application\libraries\Users_library (in XGPCore.php)<br>Where called: line 40 of  (in Users_library.php)<br>Where called: line 79 of application\core\Database (in FunctionsLib.php)<br>Where called: line 69 of application\core\ErrorHandler (in Database.php)<br>Where called: line 75 of application\libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 146 of application\libraries\DebugLib (in DebugLib.php)|2020/05/26 10:25:18|
`

**Comment by MahmutHizal** [comment]
> The same error:
> 
> `|MY_IP_ADRESS|php|8192|Function get_magic_quotes_gpc() is deprecated|Where called: line 69 of application\libraries\Users_library (in XGPCore.php)<br>Where called: line 40 of (in Users_library.php)<br>Where called: line 79 of application\core\Database (in FunctionsLib.php)<br>Where called: line 69 of application\core\ErrorHandler (in Database.php)<br>Where called: line 75 of application\libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 146 of application\libraries\DebugLib (in DebugLib.php)|2020/05/26 10:25:18|`

This is my xgp data. 
![C10809B0-8715-488C-AF81-FECC58A40F70](https://user-images.githubusercontent.com/7260763/82880862-a81a1f00-9f47-11ea-8e93-7ae47417710e.png)

Use my php version that i used if you can do

**Comment by DaPike** [comment]
Ok. Now I'm on php 7.3.18.

![ogame5](https://user-images.githubusercontent.com/6161720/82885944-1c53c300-9f46-11ea-8495-dbd7160fceb5.jpg)

**Comment by MahmutHizal** [comment]
Please create a file into install directory that named php.php. And write this:
```php
<?php

// Tüm bilgiyi gösterelim (INFO_ALL sabitine eşdeğer)
phpinfo();
```
And send screenshot

**Comment by DaPike** [comment]
Ok. You're right!
PHP Info tells me that I'm still on PHP 7.4.6.

In this case I don't know other things to change to a lower version.
I'm using Ubunutu 20.04 as server. PHP versions installed: 7.1, 7.2, 7.3 and 7.4.

With 
` sudo update-alternatives --config php`
I can choose my wanted version. But phpinfo is still 7.4.6.

Any ideas?

**Comment by MahmutHizal** [comment]
I am so happy for you did solving your problem. 
Your answer of the other question is you have to some coding for that. So, I can help you about that if you're waiting for me while I'm going home about 00:00 utc+3

**Comment by DaPike** [comment]
Many thanks to you!
Of course I can wait.
And you don't have to hurry up.

**Comment by MahmutHizal** [comment]
> Ok. You're right!
> PHP Info tells me that I'm still on PHP 7.4.6.
> 
> In this case I don't know other things to change to a lower version.
> I'm using Ubunutu 20.04 as server. PHP versions installed: 7.1, 7.2, 7.3 and 7.4.
> 
> With
> ` sudo update-alternatives --config php`
> I can choose my wanted version. But phpinfo is still 7.4.6.
> 
> Any ideas?
> 
> I could change to php 7.3.
> Script is up an running!!!
> I will test and translate!
> 
> Thanks to MahmutHizal!!
> Wonderful support!
> 
> EDIT:
> One more question please!
> 
> How can I get DARK METAL?
> What I have to do, that players can get it for free.
> Or do they have to pay?

> You can use this SQL code:
> 
> ```sql
> ALTER TABLE `xgp_premium` CHANGE `premium_dark_matter` `premium_dark_matter` INT(10) NOT NULL DEFAULT '100000';
> ```
> 
> 100.000 means starter darkmatter. You can change that what you want.
> You must change `xgp_` prefix if you did used another prefix

**Comment by FGServers** [comment]
FIX MAGIC CUOTES INSTALL

Ramplace this for
`$this->magic_quotes_active = get_magic_quotes_gpc();`

This
`if (version_compare(PHP_VERSION, '5.3.0', '<')) {
            $this->magic_quotes_active = get_magic_quotes_gpc();
            get_magic_quotes_gpc(0);
        }`
