### ISSUE TITLE
[Help needed] How to get Dark Metal in version 3.1.0?

### ISSUE THREAD

**Issue by DaPike** [XGProyect/XG-Proyect-v3.x.x#299]
I decided to make a new request

How can I get DARK METAL for players?
What I have to do, that players can get it for free.
Or do they have to pay?

I'm on version 3.1.0.

I can edit mysql database to get DM, but the player should solve a task or something like that to earn DM.

But I don't know what I have to do for this.

Thanks a lot for advise.

**Comment by MahmutHizal** [comment]
You can use this SQL code:
```sql
ALTER TABLE `xgp_premium` CHANGE `premium_dark_matter` `premium_dark_matter` INT(10) NOT NULL DEFAULT '100000';
```
100.000 means starter darkmatter. You can change that what you want. 
You must change `xgp_` prefix if you did used another prefix

**Comment by MahmutHizal** [comment]
But you dont forget. This is not an suggested solution by me.

**Comment by DaPike** [comment]
I know that I can insert via sql.
But how can a player get dark metal?

Is there a way to 'pay' for it?
First of all I don't want to earn money with the game.
But the player must have a chance to earn DM with solving a task or any other solution.

**Comment by MahmutHizal** [comment]
Users can send fleets to expedition for find some dark matter. If you want to another way like me, you can check #283 brainstorming issue about your question :)

**Comment by DaPike** [comment]
OK. That are bad news.
In this case the game is not really full usable.
I have no time to send every player DM once a week or once a month.

I'm very sad about this.
I spend a lot of time now to get everything running, and then, one of the heart of the game (DM) can not be used by the players.
I also finished the german translation now by ca. 85%.
I hoped I could give you the present of the language files (for game!) till two weeks.
Admin language needs to be translated later.

**Comment by LucasKovacs** [comment]
@DaPike you can customize the payment URL from the admin panel
