### ISSUE TITLE
config.php still uses INSIDE

### ISSUE THREAD

**Issue by athk** [XGProyect/XG-Proyect-v3.x.x#3]
`if(!defined("INSIDE")){ header("location:./../"); }`

But inside is no longer defined as of beta 6. So I keep getting redirected back.
Has an easy fix, I'd personally go with `!defined('IN_GAME') && !defined('IN_LOGIN')`

**Comment by athk** [comment]
The problem seems to actually be that config.php should not be versioned at all, as it's created on install.

**Comment by XGProyect** [comment]
You should not have this issue any longer. Those INSIDE validations were removed.

**Comment by XGProyect** [comment]
Implemented in one of the last commits. The files config.php, config.xml and ErrorLog.php were removed from the repository and are created automatically during the installation process.
