### ISSUE TITLE
Alliance application and search

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#30]
Alliance Search
Notice: Undefined index: ally_tag in /home/eskiog/public_html/beta6/application/controllers/game/alliance.php on line 287

Alliance Application
` Click here to send your application to the alliance`
I clicked to apply and led me to create alliance/search

![5-5](https://cloud.githubusercontent.com/assets/16218107/12705714/8e4e7746-c87e-11e5-9e3d-60bbbbf311c6.png)

**Comment by athk** [comment]
Hmm, @XGProyect that you assign it means you're working on it? Or is it otherwise free for anyone to take a shot at solving it?

**Comment by XGProyect** [comment]
@athk anyone can take a look at it ;)

**Comment by XGProyect** [comment]
Several bugs were fixed.
