### ISSUE TITLE
[Solución Temporal / Temporary Solution] Error en la instalación de la fase 4 / Phase 4 installation failed

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#301]
**Español/Spanish:** 
Para solucionar este erro de instalación solo deberán poner un comparador de versión, no es una solución para armar un juego hay q esperar hasta que lucky vuelva y la solucione.

**Instrucciones**
Abrir archivo /core/Database,php y localizar esto

` $this->magic_quotes_active = get_magic_quotes_gpc();`

Remplazar por esto
```
if (version_compare(PHP_VERSION, '7.3.0', '<')) {
       $this->magic_quotes_active = get_magic_quotes_gpc();
       get_magic_quotes_gpc(0);
}
```

Abrir archivo /libraries/SecurePageLib.php y buscar esto

```
if (get_magic_quotes_gpc()) {
      $value = htmlentities(stripslashes($value), ENT_QUOTES, 'UTF-8', false);
} else {
      $value = htmlentities($value, ENT_QUOTES, 'UTF-8', false);
}
```

Remplazar por esto

```
if (version_compare(PHP_VERSION, '7.3.0', '<')) {
                
      if (get_magic_quotes_gpc()) {
              $value = htmlentities(stripslashes($value), ENT_QUOTES, 'UTF-8', false);
      } else {
              $value = htmlentities($value, ENT_QUOTES, 'UTF-8', false);
     }
                
     get_magic_quotes_gpc(0);
}
```

**Ingles/English**
To solve this installation error, they only have to put a version comparator, it is not a solution to build a game, you have to wait until lucky returns and solves it.

Instructions
Open /core/Database file, php and locate this
` $this->magic_quotes_active = get_magic_quotes_gpc();`

Replace with this
```
if (version_compare(PHP_VERSION, '7.3.0', '<')) {
       $this->magic_quotes_active = get_magic_quotes_gpc();
       get_magic_quotes_gpc(0);
}
```

Open /libraries/SecurePageLib.php file and look for this

```
if (get_magic_quotes_gpc()) {
      $value = htmlentities(stripslashes($value), ENT_QUOTES, 'UTF-8', false);
} else {
      $value = htmlentities($value, ENT_QUOTES, 'UTF-8', false);
}
```

Replace with this
```
if (version_compare(PHP_VERSION, '7.3.0', '<')) {
                
      if (get_magic_quotes_gpc()) {
              $value = htmlentities(stripslashes($value), ENT_QUOTES, 'UTF-8', false);
      } else {
              $value = htmlentities($value, ENT_QUOTES, 'UTF-8', false);
     }
                
     get_magic_quotes_gpc(0);
}
```

**Comment by LucasKovacs** [comment]
Removed 
`get_magic_quotes_gpc(0);`

Another improvements were made
