### ISSUE TITLE
footer.php template is missing

### ISSUE THREAD

**Issue by Nipis** [XGProyect/XG-Proyect-v3.x.x#303]
On installer wizard, the footer.php template file is missing.

To solve, reeplace in this file:
/application/libraries/TemplateLib.php on line 124:
                'general/simple_footer',

For this:
                'general/footer',

**Comment by FGServers** [comment]
Tambien creo que el die de Template.php

```
die('Template not found or empty: <strong>' . $template_name . '</strong><br />
                Location: <strong>' . $route . '</strong>');
```

deberia ser asi

```
die('Template not found or empty: <strong>' . $template. '</strong><br />
                Location: <strong>' . $route . '</strong>');
```

**Comment by BeReal86** [comment]
Hi,

Thank you for your feedback.  What version of XGP are you using?  What is the php version?

**Comment by FGServers** [comment]
phase 5

**Comment by Nipis** [comment]
> Hi,
> 
> Thank you for your feedback. What version of XGP are you using? What is the php version?

PHP 7.2.31
