### ISSUE TITLE
It is not possible to send a fleet

### ISSUE THREAD

**Issue by Nipis** [XGProyect/XG-Proyect-v3.x.x#304]
When you get to fleet 3 sending fleet, it gives error 500
The log says this:

```
Cannot modify header information - headers already sent by (output started at /home/ogp/public_html/ogp/application/libraries/DebugLib.php:130)

in /home/ogp/public_html/ogp/application/libraries/FunctionsLib.php on line 597

Where called: line 219 of application\controllers\game\Fleet3 (in fleet3.php)
Where called: line 439 of (in fleet3.php)
Where called: line 597 of (in FunctionsLib.php)

```
Apparently the error occurs because it cannot find ships to send.
I did some research, and saw that the selected ships calls them from a $_SESSION variable and actually passes them through $_POST

If I find something else I will communicate it

**Comment by Nipis** [comment]
The problem is in the fleet1.php file.
Line 372:
`$_SESSION['fleet_data'] = [];`
This clean the fleet_data variable and the fleet2 and fleet3 files can't read fleetarray

**Comment by BeReal86** [comment]
Hi,

Thank you for your feedback.  What version of XGP are you using?  What is the php version?

**Comment by FGServers** [comment]
> Hi,
> 
> Thank you for your feedback. What version of XGP are you using? What is the php version?

phase 5 Bereal86

**Comment by Nipis** [comment]
> Hi,
> 
> Thank you for your feedback. What version of XGP are you using? What is the php version?

PHP 7.2.31

**Comment by BeReal86** [comment]
Hi @Nipis 

I made several attempts to better understand the situation and the fleet attack mission was successful and I tried several missions. I wonder which task you have problems with?

<img width="427" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/87858934-3b654480-c93a-11ea-8be8-101dfd446ad5.png">

**Comment by Nipis** [comment]
I tried send fleet and I get this error when go to fleet3

`Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\ogp\application\libraries\DebugLib.php:139)
in D:\xampp\htdocs\ogp\application\libraries\FunctionsLib.php on line 1182
Error code: 2
Trace (Debug Log):
Where called: line 219 of application\controllers\game\Fleet3 (in D:\xampp\htdocs\ogp\application\controllers\game\fleet3.php)
Where called: line 439 of (in D:\xampp\htdocs\ogp\application\controllers\game\fleet3.php)
Where called: line 1182 of (in D:\xampp\htdocs\ogp\application\libraries\FunctionsLib.php)
Where called: line of application\core\ErrorHandler (in )
Where called: line 75 of application\libraries\DebugLib (in D:\xampp\htdocs\ogp\application\core\ErrorHandler.php)
Where called: line 139 of application\libraries\DebugLib (in D:\xampp\htdocs\ogp\application\libraries\DebugLib.php)`

A var_dump of $_SESSION returns fleet_data empty

**Comment by MahmutHizal** [comment]
I think this issue may triggered because of operation system.

**Comment by BeReal86** [comment]
Hello, I downloaded it without any changes and made a clean installation and trial. The result is successful as seen

PHP Version: 7.3.20 
MySQL Version 5.0.12
10.4.13-MariaDB
localhost with XAMPP

<img width="1099" alt="Screenshot_3" src="https://user-images.githubusercontent.com/16218107/88319425-cec8bc00-cd24-11ea-967c-f799cd0d811a.png">

<img width="446" alt="Screenshot_2" src="https://user-images.githubusercontent.com/16218107/88319181-7a254100-cd24-11ea-8e15-c532a38b40c3.png">

**Comment by Nipis** [comment]
![image](https://user-images.githubusercontent.com/13924099/88321394-7c23db80-ccf5-11ea-9090-12e869a33eb8.png)

Any ship with a fresh install. In this case I tried to send an expedition

**Comment by BeReal86** [comment]
strange situation i am not getting an error. Are there any other testers?

<img width="938" alt="Screenshot_5" src="https://user-images.githubusercontent.com/16218107/88322110-e5711200-cd28-11ea-9535-7e2a4cd2d71a.png">
<img width="936" alt="Screenshot_6" src="https://user-images.githubusercontent.com/16218107/88322112-e609a880-cd28-11ea-91d0-e3529b819ca1.png">
<img width="956" alt="Screenshot_7" src="https://user-images.githubusercontent.com/16218107/88322113-e6a23f00-cd28-11ea-888a-0915460fabfa.png">
<img width="469" alt="Screenshot_8" src="https://user-images.githubusercontent.com/16218107/88322117-e6a23f00-cd28-11ea-9d69-ef18b38fbbe7.png">

**Comment by Nipis** [comment]
@FGServers have the same problem too

**Comment by Nipis** [comment]
I discovered that the variable $_SESSION['fleet_data'] is empty on fleet3.

**Comment by FGServers** [comment]
PHP Version: 7.4.0
MySQL Version 8.0.8.12
10.4.13-MariaDB
localhost with Wamp64

Lo probe en Wamp y el erro no me lo tira pero tengo otro con la galaxia q no me sale el overlib del planeta

**Comment by BeReal86** [comment]
I installed more than one XAMPP and tried. I have not received any errors regarding the fleet.

Could modifications be made to the files?

**Comment by FGServers** [comment]
> the

no yo no modifique nada hice instalación de 0 de la beta 5 y funciono lo del fleet pasa q el xampp ya me andaba mal así q lo cambie..

**Comment by Nipis** [comment]
Xampp is the problem
