### ISSUE TITLE
[Feature Request] Eliminar el consummo de deuterio al ver la galaxia

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#305]
Viendo el changelog de ogame, se ve que le quitaron el consumo de deuterio al ver las galaxias... 
[Feature Request] Remove of deuterium consumption by viewing galaxy
![image](https://user-images.githubusercontent.com/2124810/88004683-e6faca00-cadd-11ea-95d0-d28353fe578b.png)
Imagen del server de pruebas de ogame.

**Comment by BeReal86** [comment]
Hi, @FGServers 

Thank you for the feedback. This feature has been around for a while, but we forgot to add it to the stem. Thanks for your attention.
