### ISSUE TITLE
Mission Hold Position #2

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#31]
players have the opportunity to stand out and you're not an alliance and friend. it should be avoided.

but any kind of error stands out as follows:

XG Proyect

500. That’s an error.

The requested URL throw an error. Contact the game Administrator. That’s all we know. 

![4-4](https://cloud.githubusercontent.com/assets/16218107/12705710/7a961cb8-c87e-11e5-9123-9da25315bc69.png)

![4-4-4](https://cloud.githubusercontent.com/assets/16218107/12705712/822b62c6-c87e-11e5-9d20-4e7e8201c21a.png)

**Comment by XGProyect** [comment]
Fixed
