### ISSUE TITLE
Is it still in implementation ?

### ISSUE THREAD

**Issue by ExileNG** [XGProyect/XG-Proyect-v3.x.x#310]
Hello. I would like to know if XGP is still in implementation. I would like to port source code to Django/Python. Please give me news. See you. Freddec

**Comment by BeReal86** [comment]
Hi, @ExileNG 

Yeah it's still active

**Comment by LucasKovacs** [comment]
@ExileNG it is still supported and being actively developed. Django/Python support is not provided

**Comment by ExileNG** [comment]
Do you plan to update look'n feel/skin to the modern one ?

**Comment by LucasKovacs** [comment]
Not in the short term. I want to add a framework to it, so then we can start building an API. From there anyone will be able to build their own frontend

**Comment by ExileNG** [comment]
You mean that you will turn this project into a REST API ? Then everybody who wants to build a front will be free to do it. It will be smart ;)

**Comment by LucasKovacs** [comment]
You got it right 👍

**Comment by BeReal86** [comment]
If you have any questions, please open it again.
