### ISSUE TITLE
[Pregunta] Viendo el Resources.php

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#311]
Estuve viendo los archivos del resources.php que maneja la configuración de los recursos y quería saber para que sirven estas líneas

`  $BuildTemp = $this->_current_planet['planet_temp_max'];`

```
 $BuildLevelFactor = $this->_current_planet['planet_' . $this->_resource[$ProdID] . '_percent'];
                $BuildLevel = $this->_current_planet[$this->_resource[$ProdID]];
                $BuildEnergy = $this->_current_user['research_energy_technology'];
```

Por que el visual code studio me dice q esas líneas no están declaradas.. quería saber si las puedo eliminar...

**Comment by LucasKovacs** [comment]
Son usadas más abajo por la function eval. Por ejemplo aca:

`$metal_prod = eval($this->_prod_grid[$ProdID]['formule']['metal']);`

La siguiente linea
`$this->_prod_grid[$ProdID]['formule']['metal']`

obtiene los datos de $ProdGrid en objects_collection.php


Eval interpreta lo siguiente 

`return   (30 * $BuildLevel * pow((1.1), $BuildLevel)) * (0.1 * $BuildLevelFactor);`

Como antes no existían funciones anónimas, esa era la solución. Lo podes pensar como una especie de callback. La realidad es que necesita un buen refactor eso.

En definitiva, no, no se pueden borrar.

**Comment by BeReal86** [comment]
If you have any questions, please open it again.
