### ISSUE TITLE
[Modificación] Oficiales tiempo restante como el rediseño

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#312]
**OGAME OFICIAL ESPAÑOL**
![image](https://user-images.githubusercontent.com/2124810/88855095-bcd59600-d1c8-11ea-929b-344dedabd4f3.png)
**OGAME OFICIAL INGLES**
![image](https://user-images.githubusercontent.com/2124810/88855149-ce1ea280-d1c8-11ea-9415-243a4c4bfe32.png)

**XGPROYECT VERSIÓN BETA 5**
![image](https://user-images.githubusercontent.com/2124810/88855209-e098dc00-d1c8-11ea-880f-9e0d8782b698.png)

Código Versión - 1:

Agregar al FormatLib.php
```
  /**
     * prettyTimeAgo
     *
     * @param int $datetime DateTime
     * @param $full
     *
     * @return string
     */
    public static function prettyTimeAgo($datetime, $full = false)
    {
        $now = new DateTime;
        $ago = new DateTime($datetime);
        $diff = $now->diff($ago);
        $diff->w = floor($diff->d / 7);
        $diff->d -= $diff->w * 7;
    
       // Me olvide de agregar al lenguaje - versión 2 lo cambio
        $string = array(
            'y' => 'year',
            'm' => 'month',
            'w' => 'week',
            'd' => 'day',
            'h' => 'hour',
            'i' => 'minute',
            's' => 'second',
        );
        foreach ($string as $k => &$v) {
            if ($diff->$k) {
                $v = $diff->$k . ' ' . $v . ($diff->$k > 1 ? 's' : '');
            } else {
                unset($string[$k]);
            }
        }
    
        if (!$full) $string = array_slice($string, 0, 1);
        return $string ? implode(', ', $string) . '' : 'just now';
    }
```

Officier_lang.php / Español
buscar la linea 'of_active' => y remplazarla poir esta
`'of_active' => 'Activo durante otros %d',`
Officier_lang.php / Ingles.
`'of_active' => 'Still active for more than %d',`

en ingame.php ingles
`'tn_active' => 'Still active for more than %d',`
Ingame Español
'tn_active' => 'Activo durante otros %d',

en Officiers.php / Controllers
buscar la función  private function setOfficierStatusWithFormat(int $item_id): string

remplazarla por esta
 ```
private function setOfficierStatusWithFormat(int $item_id): string
    {
        if (OfficiersLib::isOfficierActive($this->user[$this->getObjects()->getObjects($item_id)])) {

            return FormatLib::customColor(
                strtr(
                    $this->langs->language['of_active'], [
                        '%d' => FormatLib::prettyTimeAgo(
                            Timing::formatShortDate(
                                $this->user[$this->getObjects()->getObjects($item_id)]
                            )
                        )
                    ]
                ), 'lime'
            );
        }

        return FormatLib::colorRed($this->langs->line('of_inactive'));
    }
```

y en templatelib.php
private function gameNavbar()

agregar debajo de los oficiales
```
$commander_status = $this->langs['tn_add_commander'];

        if ($this->current_user['premium_officier_commander'] > 0) {

            $commander_status = strtr(
                $this->langs['tn_active'], [
                    '%d' => FormatLib::prettyTimeAgo(
                        Timing::formatShortDate(
                            $this->current_user['premium_officier_commander']
                        )
                    )
                ]
            );
        }
```
mas abajo o debajo de las imagenes

```
// New
$parse['status_commnader'] = $commander_status;
```

y en la plantilla topnav.php buscar  {tn_add_commander} y remplazarlo por {status_commnader}

Estaré agregando mas cosas pero mas o menos quedaría algo asi

**Comment by BeReal86** [comment]
#250

**Comment by BeReal86** [comment]
#250 
In fact, as he wrote here, officers will be rearranged.

**Comment by LucasKovacs** [comment]
@FGServers no tenes el template por casualidad? del topbar

**Comment by FGServers** [comment]
Creo que si después te lo mando

**Comment by BeReal86** [comment]
![resim](https://user-images.githubusercontent.com/16218107/98440788-cd70a300-210b-11eb-9915-23447023c88d.png)
![resim](https://user-images.githubusercontent.com/16218107/98440810-fbee7e00-210b-11eb-8daa-db7e877c9f16.png)
![resim](https://user-images.githubusercontent.com/16218107/98440821-11fc3e80-210c-11eb-968d-82ae79508778.png)

When I click on the officers, there is no problem, the page opens. But if you click on the officers above on the officers page again, the text scrolls there as in the last picture. This may be related to the monitor and resolution I am using. I am using a 4K monitor.

**Comment by LucasKovacs** [comment]
@BeReal86 i've sent a fix, you will have to tell me if it works because I don't have a screen that big

**Comment by BeReal86** [comment]
@LucasKovacs 
sorry it doesn't work. I think it is not a problem. I just wanted to state that it does not constitute a big problem.

the rest works fine i am adding pictures.
<img width="463" alt="Screenshot_14" src="https://user-images.githubusercontent.com/16218107/98447907-9b763580-2139-11eb-8008-0b7c06675796.png">
<img width="367" alt="Screenshot_15" src="https://user-images.githubusercontent.com/16218107/98447908-9d3ff900-2139-11eb-9922-35037f7f60e4.png">
<img width="471" alt="Screenshot_16" src="https://user-images.githubusercontent.com/16218107/98447909-9dd88f80-2139-11eb-9234-eeaf21adc6ea.png">
<img width="257" alt="Screenshot_17" src="https://user-images.githubusercontent.com/16218107/98447912-9f09bc80-2139-11eb-83c6-86c06d68a658.png">

**Comment by BeReal86** [comment]
As I said before, the problem continues, but I think this is not an obstacle. If you wish, we can open the report again.

**Comment by LucasKovacs** [comment]
@BeReal86 leave it closed. I won't fix it
