### ISSUE TITLE
Finalizacion de Contruccion

### ISSUE THREAD

**Issue by Skylon2** [XGProyect/XG-Proyect-v3.x.x#315]
**Describe the bug**
Al momento de construir un mina se descuenta correctamente los recursos necesarios, pero si al momento de concluir esta construccion no cuentas con estos recursos, dicha construccion no se mejora y muestra el mensaje de recursos insuficientes.

**To Reproduce**
1. Click mejorar planta solar
2. se descuenta los recursos y te quedas sin suficientes para esa planta que mejoraste.
3. concluye la mejora de la planta, continuas sin recursos suficientes.
4. Error: No mejora la planta solar (no level up) y muestra mensaje de recursos insuficientes.

**Expected behavior**
Deberia subir el nivel mejorado sin importar que en ese momento no cuentes con los recursos ya empleados para mejorar
![Screenshot_2020-08-06 XG Proyect(1)](https://user-images.githubusercontent.com/15383493/89563828-1140cd00-d7ea-11ea-882b-79fe8c68671c.png)
![Screenshot_2020-08-06 XG Proyect(2)](https://user-images.githubusercontent.com/15383493/89563815-0ede7300-d7ea-11ea-9c05-5fb1776ba587.png)
![Screenshot_2020-08-06 XG Proyect(3)](https://user-images.githubusercontent.com/15383493/89563819-100fa000-d7ea-11ea-8fd0-6a7e286d9d2a.png)
![Screenshot_2020-08-06 XG Proyect(4)](https://user-images.githubusercontent.com/15383493/89563822-100fa000-d7ea-11ea-8cbb-00558bd2d964.png)
![Screenshot_2020-08-06 XG Proyect](https://user-images.githubusercontent.com/15383493/89563827-10a83680-d7ea-11ea-980a-e75a8c38569e.png)

.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser Mozilla Firefox
 - Version 79.0

**Smartphone (please complete the following information):**
 
 **Server (please complete the following information):**
 - PHP Version: 7.2.24
 - MySQL Version: 5.5.5-10.1.29-MariaDB

**Additional context**

**Comment by BeReal86** [comment]
Hi @Skylon2  Thank you for your feedback.

When adding the building to the building list you mean, the transaction list should be obtained without looking for the required mining requirement.

**Comment by LucasKovacs** [comment]
@BeReal86 are you able to reproduce this issue? On phase 5

**Comment by LucasKovacs** [comment]
@Skylon2 que version del juego usas?

**Comment by BeReal86** [comment]
@LucasKovacs sorry I was not quite sure I provided the new controls. There is nothing wrong.

Even if the requirements are not met, the building list can be added.

<img width="1004" alt="Screenshot_5" src="https://user-images.githubusercontent.com/16218107/89638238-24b86a80-d8b4-11ea-8b6e-5becd0b77b04.png">

**Comment by BeReal86** [comment]
<img width="714" alt="Screenshot_7" src="https://user-images.githubusercontent.com/16218107/89638730-f6875a80-d8b4-11ea-9cbb-c4e97c7d861f.png">
<img width="611" alt="Screenshot_8" src="https://user-images.githubusercontent.com/16218107/89638734-f8511e00-d8b4-11ea-96f0-aa86fa047355.png">

**Comment by LucasKovacs** [comment]
@Skylon2 intenta utilizar el codigo del branch phase 5 https://github.com/XGProyect/XG-Proyect-v3.x.x/tree/310-phase-5

**Comment by Skylon2** [comment]
Version: XG Proyect ( 3.1.0) 

Estoy probando esta version liberada como estable.
Contiene mas errores que no he reportando.

**Comment by Skylon2** [comment]
> 
> 
> @Skylon2 intenta utilizar el codigo del branch phase 5 https://github.com/XGProyect/XG-Proyect-v3.x.x/tree/310-phase-5
> 
> Si aun tienes problemas, por favor reabre el issue

Voy a probar ese y le digo luego.

**Comment by BeReal86** [comment]
@Skylon2  Hello, I hope you have English. My spanish is so bad

Of course if you find any more bugs or issues, please let us know. v3.1 stable version get better. However, I would like to point out that you must clearly indicate the version you are testing. sample; Our version 3.1 has not been created yet. Instead, there are versions of v3.1 going in the direction of Beta 1-2-3-4-5. If you used one of these, I would appreciate it if you specify it as the subject or [v3.1 Beta 1] for the subject.

thanks for your interest

**Comment by Skylon2** [comment]
> 
> 
> @Skylon2 Hello, I hope you have English. My spanish is so bad
> 
> Of course if you find any more bugs or issues, please let us know. v3.1 stable version get better. However, I would like to point out that you must clearly indicate the version you are testing. sample; Our version 3.1 has not been created yet. Instead, there are versions of v3.1 going in the direction of Beta 1-2-3-4-5. If you used one of these, I would appreciate it if you specify it as the subject or [v3.1 Beta 1] for the subject.
> 
> thanks for your interest

OK, I cant write in English.
In my next's post i will follow your recommendation.

I have followed the project since its version 1 back in 2008.
I have the game in my hosting provider with others of the same genre.

**Comment by LucasKovacs** [comment]
@Skylon2 la version 3.0.4 es la más reciente estable. La 3.1.0 se encuentra en etapas finales de desarrollo. Si tienes un juego en producción es recomendable la versión 3.0.4. Si estas haciendo pruebas puedes utilizar el branch phase 5.
