### ISSUE TITLE
[3.1.0-P5] No pasa la tercera fase de instalación

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#316]
Cuando quiero instalar el ultimo comits (906 commits) del repositorio no pasa de la tercera fase en la parte de instalación de la base de datos queda en pantalla negro y arroja el error numero 500..
![image](https://user-images.githubusercontent.com/2124810/89725783-8cbc9d00-d9e9-11ea-8e27-1169cde43f30.png)

Habrá alguna manera de implementar un sistema para saber esos errores sin que tire error 500 así ayudamos en los errores.. 
Tampoco arroja log de error y eso.

PHP: 7.4
Mysql: 5.6 y 8.0.8
Wamp64
Microsft Edge 64

**Comment by LucasKovacs** [comment]
En localhost funciona asi. Tengo que mejorarlo. Pero si fuera en producción registraria correctamente todos los errores

**Comment by LucasKovacs** [comment]
@FGServers corregido. @BeReal86 ready for quality

**Comment by BeReal86** [comment]
works well. installation completed without any problems.
