### ISSUE TITLE
[3.1.0.5 Comit 925] Bug en el buscador

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#318]
Error al entrar al buscador
*Trying to access array offset on value of type null*

![image](https://user-images.githubusercontent.com/2124810/89747130-aaded780-da93-11ea-8c76-03d5beb0b01a.png)

PHP Version: 7.4.0
MySQL Version: 8.0.8
Browser: Microsoft Edge
System: Wamp64

**Comment by LucasKovacs** [comment]
@BeReal86 quality check pending
