### ISSUE TITLE
[3.1.0.5 Comit 925] Ban error

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#319]
En el administrador en la sección ban al seleccionar un usuario y querer darle ban tira este erro

*Trying to access array offset on value of type null*

![image](https://user-images.githubusercontent.com/2124810/89748291-e039f400-da98-11ea-9e97-ccabba2fa08e.png)

**Comment by BeReal86** [comment]
<img width="1909" alt="Screenshot_2" src="https://user-images.githubusercontent.com/16218107/89750691-bd7a0080-dad5-11ea-8a6a-2f8f1fd2c9ae.png">

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality

**Comment by BeReal86** [comment]
I selected the player to be banned and after completing the necessary information, I clicked the Ban User button and the error in the picture

<img width="1610" alt="Screenshot_20" src="https://user-images.githubusercontent.com/16218107/89774427-81af5d00-db0e-11ea-8780-150d8f4bf42e.png">

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality
