### ISSUE TITLE
[3.1.0-5 ] Chat Error

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#320]
<img width="1764" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/89750581-4f353e00-dad5-11ea-830c-5dbc2bf504bc.png">

PHP 7.4.8
MYSQL 5.5.5-10.4.13-MariaDB
Firefox v79
Windows 10

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality

**Comment by BeReal86** [comment]
works smoothly
