### ISSUE TITLE
[3.1.0-5 ] ACS Invitation page

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#321]
<img width="1047" alt="Screenshot_4" src="https://user-images.githubusercontent.com/16218107/89751448-c3251580-dad8-11ea-804b-f46ef609057b.png">

<img width="508" alt="Screenshot_5" src="https://user-images.githubusercontent.com/16218107/89751923-d3d68b00-dada-11ea-8112-f28816517929.png">

PHP 7.4.8
MYSQL 5.5.5-10.4.13-MariaDB
Firefox v79
Windows 10

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality
