### ISSUE TITLE
[3.1.0-5 ] ACS Attack

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#322]
While the ACS goes to war, the friendly forces do not see each other. Normally, all friendly fleets participating in the battle appear in the Outgoing fleet section.

As ACS, all incoming fleets appear in the attacked person. In other words, a single hour and time of the players participating against it

<img width="532" alt="Screenshot_6" src="https://user-images.githubusercontent.com/16218107/89751960-f7013a80-dada-11ea-92fd-7b11c05074b1.png">
<img width="460" alt="Screenshot_7" src="https://user-images.githubusercontent.com/16218107/89751963-f9639480-dada-11ea-86f0-170ca33a39be.png">
<img width="492" alt="Screenshot_8" src="https://user-images.githubusercontent.com/16218107/89751964-fa94c180-dada-11ea-9490-d7dbadd19b47.png">
<img width="1064" alt="Screenshot_9" src="https://user-images.githubusercontent.com/16218107/89751965-fc5e8500-dada-11ea-9043-ea14053fa42a.png">
no defensive ships in the war report
<img width="591" alt="Screenshot_10" src="https://user-images.githubusercontent.com/16218107/89752319-97a42a00-dadc-11ea-8e34-6df1fe91401b.png">

for example

<img width="492" alt="Screenshot_8" src="https://user-images.githubusercontent.com/16218107/89752164-e7cebc80-dadb-11ea-9a7f-523a4779de7b.png">

<img width="532" alt="asd" src="https://user-images.githubusercontent.com/16218107/89752246-38deb080-dadc-11ea-8712-0449ccc30923.png">

PHP 7.4.8
MYSQL 5.5.5-10.4.13-MariaDB
Firefox v79
Windows 10

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality

**Comment by BeReal86** [comment]
error after war occurred

<img width="732" alt="Screenshot_21" src="https://user-images.githubusercontent.com/16218107/89775236-149cc700-db10-11ea-8ee8-3a16551d2f84.png">

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality
