### ISSUE TITLE
[3.1.0-5 ] Statistics

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#323]
There is a problem with the alliance display section in statistics

<img width="607" alt="Screenshot_11" src="https://user-images.githubusercontent.com/16218107/89752591-b656f080-dadd-11ea-82d2-42052e0ef403.png">

**Comment by LucasKovacs** [comment]
@BeReal86 that's not a bug. Try to create a second player for that alliance. That's the average points. First one total, second one below the top one the average.

**Comment by BeReal86** [comment]
yes i see now

<img width="433" alt="Screenshot_25" src="https://user-images.githubusercontent.com/16218107/89777837-22a11680-db15-11ea-88fc-4db63933a01d.png">

**Comment by LucasKovacs** [comment]
Closed since it's not a bug
