### ISSUE TITLE
[3.1.0-5 ] Alliance

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#324]
<img width="857" alt="Screenshot_24" src="https://user-images.githubusercontent.com/16218107/89778770-bcb58e80-db16-11ea-97c6-5e7bf2790ceb.png">

https://drive.google.com/file/d/1j1d0dUikJEeGfi5LILXL6rsw2e2DQi4R/view?usp=sharing

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality

**Comment by BeReal86** [comment]
<img width="487" alt="a1" src="https://user-images.githubusercontent.com/16218107/89818366-4df62680-db52-11ea-9564-de702b5285cb.png">
left menu Alliance and Search for alliances write xgp click search
and finding an alliance.
When I click on the alliance, the application page opens and gives an error.
<img width="959" alt="Screenshot_2" src="https://user-images.githubusercontent.com/16218107/89818377-50f11700-db52-11ea-9582-6ece7ea0de30.png">



<img width="908" alt="aaa2" src="https://user-images.githubusercontent.com/16218107/89818828-176cdb80-db53-11ea-9db3-188c7194dc13.png">

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality
