### ISSUE TITLE
[3.1.0-5] Galaxy view

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#325]
<img width="729" alt="Screenshot_23" src="https://user-images.githubusercontent.com/16218107/89778780-c0e1ac00-db16-11ea-81f3-06533d19b1b6.png">

no shortcuts appear on planets in the galaxy. The commander is active.
<img width="1040" alt="Screenshot_26" src="https://user-images.githubusercontent.com/16218107/89778991-259d0680-db17-11ea-9fb6-a3936ea0ce23.png">

**Comment by LucasKovacs** [comment]
@BeReal86 the tag error was fixed. All officers are active and the popup over the planet is displayed

**Comment by BeReal86** [comment]
<img width="653" alt="Screenshot_3" src="https://user-images.githubusercontent.com/16218107/89820859-52bcd980-db56-11ea-9756-2cd7b1766b4f.png">

**Comment by FGServers** [comment]
@BeReal86 te consulto el overlib en localhost en el planeta funciona? por que a mi en localhost el overlib me tira error unicode

**Comment by LucasKovacs** [comment]
@FGServers BeReal tiene el mismo problema. Podes tratar de debuguearlo? Yo no estoy teniendo ese problema. Quizas sea un problema de PHP 7.4 pero necesito que alguno de uds. dos pruebe en PHP 7.3

**Comment by BeReal86** [comment]
<img width="641" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/89888822-40d04a80-dbd9-11ea-9695-543c7ecb754f.png">

I provided a hosting setup to try it out. and there was no problem. The problem may be caused by xampp or something different. but it looks ok on the server

**Comment by FGServers** [comment]
Siii yo el problema se cual es es el directory_separator se ve que falta alguna librería para Windows , ll probé en producción y no tengo ese problemas.

**Comment by LucasKovacs** [comment]
@FGServers es porque la forma en que Windows y Linux arman la estructura de directorios es distinta. Linux usa / y windows usa \

Localmente usas Windows, y los hostings usan Linux. Gracias por el dato, voy a ver si puedo hacerlo compatible para Windows.

**Comment by LucasKovacs** [comment]
@BeReal86 please check again on localhost with xampp, using Windows.

I think @FGServers was right!

**Comment by FGServers** [comment]
Me tira este error
https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/332

**Comment by BeReal86** [comment]
tests were done on Xampp and windows 10. the problem continues.

![resim](https://user-images.githubusercontent.com/16218107/90342343-269ad000-e010-11ea-8931-9827f34d911c.png)

**Comment by LucasKovacs** [comment]
@FGServers te funciono con ese cambio?

**Comment by FGServers** [comment]
Sigue el error pero mientras funcione en producción..
![image](https://user-images.githubusercontent.com/2124810/90345698-45da3300-dff9-11ea-8df0-74444f2a150d.png)

**Comment by LucasKovacs** [comment]
@FGServers podras conseguirme una screenshot del HTML? Justo donde se genera el overlib

**Comment by FGServers** [comment]
![image](https://user-images.githubusercontent.com/2124810/90404637-0d7a3980-e079-11ea-9465-135d6d4e4fcd.png)
hay me tira el error no se por que sera el navegador ahora lo voy a cambiar a wamp64 poner xampp y usar Chrome

**Comment by LucasKovacs** [comment]
@FGServers on entonces ya se cual es el problema. Habia cambiado los / por \ 

Antes era obvio que fallara por que habia una mezcla entre \/ en la misma URL. La última prueba es entonces poner todos con /

**Comment by LucasKovacs** [comment]
@BeReal86 can you try again on windows? xampp and wampp

**Comment by BeReal86** [comment]
Xampp and Wampp testing is ok
