### ISSUE TITLE
[3.1.0-5] Install Error

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#328]
It gives an error before going to the download section.

![resim](https://user-images.githubusercontent.com/16218107/90321492-00632a80-df53-11ea-90bc-b2ce14e9581c.png)

PHP 7.4.9
Mysql 5.7.31

**Comment by FGServers** [comment]
si le agregas debajo del 

**use AutoLoader;**

esto 
**use Exception;**

**Comment by LucasKovacs** [comment]
No, no hay que crearlo. El archivo sigue estando

**Comment by BeReal86** [comment]
The problem goes away when I create the config file.

<img width="617" alt="Screenshot_3" src="https://user-images.githubusercontent.com/16218107/90329433-87dd8780-dfad-11ea-8857-61136d9ecafe.png">
