### ISSUE TITLE
[3.1.0.-5 Comit 1027] Galaxia error

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#332]
Error cuando entro a la galaxia
![image](https://user-images.githubusercontent.com/2124810/90340624-f29fba80-dfcf-11ea-8f5c-2e0649241b34.png)

**Comment by BeReal86** [comment]
I reinstalled and tested the galaxy is running
The test will come soon from the installation on the hosting server.

![resim](https://user-images.githubusercontent.com/16218107/90340715-d5d0aa80-e002-11ea-99c5-e02c7c5cc145.png)

**Comment by FGServers** [comment]
Galaxy Work fresh instalation
Overlib not working

![image](https://user-images.githubusercontent.com/2124810/90341249-6c39a780-dfd4-11ea-9996-c66ca551f6d1.png)

**Comment by LucasKovacs** [comment]
@FGServers @BeReal86 acabo de mandar nuevo código. Efectivamente habían errores.

**Comment by FGServers** [comment]
Esto fixiado baje el ultimo comit

**Comment by BeReal86** [comment]
![resim](https://user-images.githubusercontent.com/16218107/90341846-d6217380-e00b-11ea-9599-6511c58827e0.png)

**Comment by FGServers** [comment]
El overlib proba pasa el mouse sobre el planeta.

**Comment by BeReal86** [comment]
There was already an issue with the overlib error. Here is another error that occurred on you looking at

**Comment by FGServers** [comment]
funciona perfecto ahora

![image](https://user-images.githubusercontent.com/2124810/90660517-6e8e4280-e21c-11ea-9c04-1025bdcce7ea.png)

**Comment by LucasKovacs** [comment]
Gracias por reverificar @FGServers
