### ISSUE TITLE
[3.1.0-5] Language problem / Users General Information

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#333]
Language deficiency is present in both languages.

![resim](https://user-images.githubusercontent.com/16218107/90342319-f0f5e700-e00f-11ea-9d25-7b6b9d5f2f85.png)

**Comment by FGServers** [comment]
Dejo otor mas 
![image](https://user-images.githubusercontent.com/2124810/90344056-82ebf880-dfec-11ea-942c-fea510a421a7.png)
