### ISSUE TITLE
[3.1.0-5] Bug aparece la luna en la sección de planetas al editar el planeta o esta echo así

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#334]
Bug de duplicidad al editar el planeta de un usuario o Duda
![image](https://user-images.githubusercontent.com/2124810/90343618-a0b75e80-dfe8-11ea-9929-0b7ccafb2845.png)

Pregunto es así para saber q el planeta tiene esa luna..? xD si es asi como que me di cuenta recién jajajaj XD

**Comment by LucasKovacs** [comment]
No es un error. Aparece duplicado por que la luna se llama Moon. Es nombre (tipo), en este caso Moon (Moon). Si la renombras va a ser nuevo-nombre (Moon)
