### ISSUE TITLE
[3.1.0-5] Admin Panel Alliance

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#336]
Error when searching for a wrong name or a name that does not exist on the alliance page in the administration panel

<img width="1910" alt="Screenshot_6" src="https://user-images.githubusercontent.com/16218107/90344102-20f8b680-e01f-11ea-8ecf-d99ba58f0411.png">

**Comment by BeReal86** [comment]
Sending messages such as coordinates and url is no longer a problem. I tested it several times

**Comment by BeReal86** [comment]
<img width="1845" alt="Screenshot_10" src="https://user-images.githubusercontent.com/16218107/90386089-baaa7d00-e08c-11ea-8a7a-4316f24c9a24.png">

**Comment by BeReal86** [comment]
The problem continues in the member

![resim](https://user-images.githubusercontent.com/16218107/90574921-d0ba5980-e1c2-11ea-8d46-d4726454e769.png)

**Comment by LucasKovacs** [comment]
@BeReal86 it is ready
