### ISSUE TITLE
[3.1.0-5] Error SQL al enviar un msj privado

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#338]
Error al enviar un msj privado
![image](https://user-images.githubusercontent.com/2124810/90351710-6d3ff880-e017-11ea-9898-69891de9edd0.png)

**Comment by FGServers** [comment]
Cerrar no es un bug tenia la mysql en modo estricto no se por que hace esto wampp voy a cambiar a xampp por las dudas

**SET @@global.sql_mode= 'NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';**

**Comment by BeReal86** [comment]
wamp seems a bit problematic. I have tested it with xampp no problem.


<img width="796" alt="Adsız" src="https://user-images.githubusercontent.com/16218107/90355440-06413480-e055-11ea-92af-060ae9b9ab03.png">

**Comment by BeReal86** [comment]
Sending messages such as coordinates and url is no longer a problem. I tested it several times
