### ISSUE TITLE
[3.1.0-5] ACS defense

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#345]
I sent fleet for ACS defense. This error appeared when I clicked on the overview section

<img width="1920" alt="Screenshot_21" src="https://user-images.githubusercontent.com/16218107/90556201-2b42be00-e1a1-11ea-95f4-efe67313d288.png">

**Comment by LucasKovacs** [comment]
Duplicated of https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/343
