### ISSUE TITLE
[3.1.0-5] Disabled server

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#349]
error when the server shuts down while the player is in the game
<img width="1821" alt="Screenshot_23" src="https://user-images.githubusercontent.com/16218107/90567226-84ffb400-e1b2-11ea-93b9-dc8414d8a905.png">

Error when another player looks at the home page while the game is closed
Note: I had reset the statistics.
<img width="1905" alt="Screenshot_24" src="https://user-images.githubusercontent.com/16218107/90567287-96e15700-e1b2-11ea-9ac1-7d8fe603e250.png">

**Comment by BeReal86** [comment]
<img width="1896" alt="Screenshot_26" src="https://user-images.githubusercontent.com/16218107/90569428-8af79400-e1b6-11ea-8752-69ad9eed84de.png">

**Comment by LucasKovacs** [comment]
@BeReal86 ready to test
