### ISSUE TITLE
[3.1.0-5] Destroy Buildings

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#350]
The times on the level destruction side are different. It does not collapse in the time shown. There is destruction during the upgrade period.

<img width="905" alt="destroy-build" src="https://user-images.githubusercontent.com/16218107/90577412-84bee300-e1c9-11ea-91b5-86b383475507.png">

**Comment by LucasKovacs** [comment]
@BeReal86 this one is ready
