### ISSUE TITLE
[3.1.0-5] ACS invitation and fleet view

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#354]
ACS invited and fleets are participating. there is a slight problem with the view on the events screen

<img width="766" alt="Screenshot_29" src="https://user-images.githubusercontent.com/16218107/90635632-18c49500-e232-11ea-88a9-ff1543db22bc.png">
<img width="1335" alt="Screenshot_30" src="https://user-images.githubusercontent.com/16218107/90635641-1cf0b280-e232-11ea-9f7a-ffe5000db5fa.png">

**Comment by LucasKovacs** [comment]
@BeReal86 ready to test
