### ISSUE TITLE
ACS

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#36]
does not work ACS.
I press the send button after ACS battle fleet.It opens a new page where you can send me the coordinates that you want, select the warships.
No invitation code to ACS. ACS had joined the fleet with different time

![6-6](https://cloud.githubusercontent.com/assets/16218107/12707005/a136fe92-c896-11e5-8ecb-e292f7a987e3.png)
![6-6-6](https://cloud.githubusercontent.com/assets/16218107/12707009/ae4496f8-c896-11e5-863f-0da68b1b57af.png)
![6-6-6-6](https://cloud.githubusercontent.com/assets/16218107/12707017/c0b9d79e-c896-11e5-861f-c757c91f6e04.png)

**Comment by XGProyect** [comment]
I was able to reproduce and fix the bug. Coming out in the next release.
