### ISSUE TITLE
[3.1.0.5] Calculo erróneo formula deuterio

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#374]
Investigando un poco decidí replicar todos mis datos de uno de los universos con velocidades x4 de ogame y subiendo todos los edificios, e investigaciones al mismo nivel, colocando el planeta en la posición que esta originalmente y con las temperaturas correspondientes y vi que hay unos pequeños errores en algunas formulas..

Acá dejo unas imágenes
![1](https://user-images.githubusercontent.com/2124810/91672074-5bc01b80-eb02-11ea-9642-38eb69ac8514.png)

Entonces decidí a investigar las formulas de ogame en el mismo foro y calcadoras y vi esto

```
Sintetizador de Deuterio:
Produccion = redondeando (10 * nivel * 1,1 ^ nivel * (1,44 - 0,004 * temperatura máxima) * velocidad del universo * bonificación del geólogo)
```
[Calaculadora proxyforgame](https://proxyforgame.com/es/ogame/calc/production.php)
```
10.0 * techLevel * Math.pow(1.1, techLevel) * (1.44 - 0.004 * maxTemp) * productionFactor * powerFactor
```

Entonces decidí cambiar la formula y porcentajes por que la que tenemos en estos momentos es esta
```
'deuterium' => 'return  ((10 * $BuildLevel * pow((1.1), $BuildLevel)) * (-0.002 * $BuildTemp + 1.28))  * (0.1 * $BuildLevelFactor);',
```
La cambie por esta
```
'deuterium' => 'return  ((10 * $BuildLevel * pow((1.1), $BuildLevel)) * (-0.004 * $BuildTemp + 1.44))  * (0.1 * $BuildLevelFactor);',
```

Usando la calculadora se optiene los valores. sera que ogame tambien tiene un bug en su produccion
![image](https://user-images.githubusercontent.com/2124810/91672338-5794fd80-eb04-11ea-9369-6b62ef5ca1ac.png)

y mas o menos los valores se acerco
![Sin título](https://user-images.githubusercontent.com/2124810/91672164-0f291000-eb03-11ea-96f9-d09c5f717449.png)

PD: Lo puse como bug pero no creo que sea un bug por que hay q ver que factores mas afectan... por eso lo voy a seguir investigando.
Aca la post del foro: https://board.es.ogame.gameforge.com/index.php/Thread/208304-CAP%C3%8DTULO-20-Recopilaci%C3%B3n-de-f%C3%B3rmulas-y-Glosario-de-t%C3%A9rminos/

**Comment by FGServers** [comment]
* Dejo el ghitub de Jstar88 que tambien hace las formulas de ogame

https://github.com/jstar88/Ogame-algorithms

**Comment by LucasKovacs** [comment]
Pero quizas sean formulas viejas. Las de jstar tienen 8 años ya

**Comment by FGServers** [comment]
Si también igual me fijé por lo de la calculadora proyecto y tira la que está hay es raro habrá que seguir investigando más y darncon la formula original. De ogame

**Comment by LucasKovacs** [comment]
@FGServers la formula tenia errores. Los mismos fueron corregidos y se hicieron mejoras en todas las tablas de producción (deuterio, solar, fusión).

**Comment by FGServers** [comment]
Calidad perfecta funciona bien solo por ese bug de la diferencia de nivel.

![qualyti](https://user-images.githubusercontent.com/2124810/97118321-4978ed00-1701-11eb-9206-926b08e548c6.png)

**Comment by LucasKovacs** [comment]
@FGServers ese error me va a llevar mas tiempo, prácticamente tengo que re escribir todo infos. El código esta horrible. Si podes abri otro ticket para trackear este error.

**Comment by BeReal86** [comment]
@LucasKovacs 
Except for the issue that @FGServers stated. There is only 1 unit of difference in the Energy balance part.

<img width="1002" alt="metal" src="https://user-images.githubusercontent.com/16218107/97239146-02bbed80-17fc-11eb-9aa5-9273fd109bc4.png">
<img width="1015" alt="Crystal" src="https://user-images.githubusercontent.com/16218107/97239153-064f7480-17fc-11eb-8c27-c33052b6129f.png">
<img width="1007" alt="deu" src="https://user-images.githubusercontent.com/16218107/97239158-08193800-17fc-11eb-8dbf-a1508234f737.png">
<img width="1060" alt="fusion" src="https://user-images.githubusercontent.com/16218107/97239163-0bacbf00-17fc-11eb-86ee-3ec3f55ed50d.png">
<img width="995" alt="solar" src="https://user-images.githubusercontent.com/16218107/97239228-267f3380-17fc-11eb-8f08-b4eccb7746ce.png">
a

**Comment by LucasKovacs** [comment]
@BeReal86 as I said, create a new bug for this
