### ISSUE TITLE
[3.1.0-5] mail not work

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#376]
Sending mail from password reset or announcement section does not work. We did the experiments on hosting.

![resim](https://user-images.githubusercontent.com/16218107/92504357-3bcbde80-f20b-11ea-95ee-5ed72e7e88c1.png)
![resim](https://user-images.githubusercontent.com/16218107/92504413-4d14eb00-f20b-11ea-9f2c-5075741cc2e9.png)

**Comment by FGServers** [comment]
Confirmo el bug en hosting y al recuperar la clave si pones un email falso tira como null

**Comment by BeReal86** [comment]
We made the smtp settings in the files. it doesn't work for me. But Jonamix worked successfully.
But, I set up woltlab forum and smtp settings are working. I can send mail.

hosting 
php 7.3.19

**Comment by duhow** [comment]
I can also send mail with PHP 7.4.10 and postfix 3.3.0.
Despite this I have issues with mail going to spam folder, but got fixed with proper DNS settings and PTR (rDNS).
As small recommendation for the register mail, SpamAssasin claims there's very few text.
> -1.781 | HTML_IMAGE_ONLY_08 | HTML: images with 400-800 bytes of words

Plus - password reset mail is HTML-broken.

![image](https://user-images.githubusercontent.com/1145001/94999245-80ebf200-05b8-11eb-84da-3913f6f867ef.png)
![image](https://user-images.githubusercontent.com/1145001/94999258-8f3a0e00-05b8-11eb-8375-da8335dedaa4.png)
![image](https://user-images.githubusercontent.com/1145001/94999263-97924900-05b8-11eb-945e-c2d1fb273634.png)

**Comment by BeReal86** [comment]
It has been tried on two different hosting accounts and just a game trial.  different programs have been tried.  The only problem is xgp mail can also be a problem.  However, I have no chance to upgrade the php version. I have reported it to the hosting company and I am waiting for it to be updated.  And of course em big factor is the proper installation and operation of php plugins.  But sending e-mails in other forums etc.

Thanks for help

**Comment by duhow** [comment]
In fact I was going to suggest to use PHPMailer lib for sending emails instead of the CodeIgniter default one.
AFAIK there are also some wrappers for replacing it if it's easier :)

**Comment by BeReal86** [comment]
Thanks for your interest and suggestion. :))

**Comment by BeReal86** [comment]
I am getting an error in sending mail. I tried the smtp mail function on Woltlab suite forum version 5.2.9 and prestashop version 1.7.6.8. Mail is sent successfully in both. But there is no mail sending with XGP.

![resim](https://user-images.githubusercontent.com/16218107/95610546-2d225280-0a69-11eb-8ca6-6dbc6622c164.png)

Such an error occurs when the user tries to reset his password.

![resim](https://user-images.githubusercontent.com/16218107/95610697-5fcc4b00-0a69-11eb-928e-5760f514ab2f.png)

**Comment by duhow** [comment]
Controller Mail on `runAction` does not give any details. "no account" means a generic error.
```php
private function runAction(): void
{
    $email = filter_input(INPUT_POST, 'email', FILTER_VALIDATE_EMAIL);

    if ($email) {
        if ($this->processRequest($email)) {
            $this->send_result = $this->langs->line('ma_sent');
        } else {
            $this->send_result = $this->langs->line('ma_error');
        }
    }
}
```

In order to debug the error you may check the `error_log` in your server or enable PHP debugging.

**Comment by BeReal86** [comment]
[xgproyect.net-ssl_log-Oct-2020.gz](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/5434680/xgproyect.net-ssl_log-Oct-2020.gz)
[ftp.xgproyect.net-ftp_log-Oct-2020.gz](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/5434681/ftp.xgproyect.net-ftp_log-Oct-2020.gz)

**Comment by LucasKovacs** [comment]
@BeReal86 closing this one. Opening a new one
https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/422
