### ISSUE TITLE
Http Error 500 - Fleet mission arrives and returns

### ISSUE THREAD

**Issue by asparatu** [XGProyect/XG-Proyect-v3.x.x#378]
I have these errors, I see how to fix the problem in the database but i dont see what is causing the problem because no matter what kind of mission does the server getting http error 500.

It give me the error when the feet arrives and returns. when the fleet return is when the server crash gives 500 error not when it arrives at the destination.

can anyone give me idea of what is causing this so i can fix it?

`Uncaught Error: Class 'public_html/application\libraries\missions\Missions' not found in application/libraries/missions/Transport.php:30 Stack trace: #0 public_html/application/core/AutoLoader.php(135): require_once() #1 [internal function]: AutoLoader::loadClass('Transport') #2 public_html/application/libraries/MissionControlLibrary.php(106): spl_autoload_call('application\\lib...') #3 public_html/application/libraries/MissionControlLibrary.php(67): public_html/application\libraries\MissionControlLibrary->processMissions(Array) #4 public_html/application/libraries/UpdatesLibrary.php(155): public_html/application\libraries\MissionControlLibrary->returningFleets() #5 public_html/application/libraries/UpdatesLibrary.php(56): applicati`

`Uncaught Error: Class 'application\libraries\missions\Missions' not found in /application/libraries/missions/Deploy.php:31 Stack trace: #0 public_html/application/core/AutoLoader.php(135): require_once() #1 [internal function]: AutoLoader::loadClass('Deploy') #2 public_html/application/libraries/MissionControlLibrary.php(106): spl_autoload_call('application\\lib...') #3 public_html/application/libraries/MissionControlLibrary.php(55): application\libraries\MissionControlLibrary->processMissions(Array) #4 public_html/application/libraries/UpdatesLibrary.php(154): public_html/application\libraries\MissionControlLibrary->arrivingFleets() #5 public_html/application/libraries/UpdatesLibrary.p`

**Comment by BeReal86** [comment]
Hello @asparatu , thank you for your feedback.

Can you illustrate how you got these errors with more examples? Example: What is your php version. What is the XGP version you are using. Did you delete everything and do a clean install. Have you made any editing or file changes in the version you are using?

**Comment by asparatu** [comment]
When you make a fleet movement, let's say transport resources from a planet to a moon or planet to plant, you get an error when you reach your destination and when your fleet return to the original location it crashes the game interface. 
The PHP Version 7.3.22, Version XGP 3.1.0, don't know if what alpha version. Before when I was going to fix the issue, I restored a backup of the database, and everyone just lost about 6 hours of progress, now from doing some testing on the test server, I seen that I just deleted the finished fleet movements and the game interface works again. I have seen some changes other people did and tried to see if that fixed the issue but does not, so I have not made any changes to files. 

Here is the debug trace log

Fleet Arriving Debug Error
`|61.28.158.128|php|1|Uncaught Error: Class '\application\libraries\missions\' not found in /home/warlegen/xtremedarkness.uk.nf/application/libraries/MissionControlLibrary.php:106
Stack trace:
#0 /home/warlegen/xtremedarkness.uk.nf/application/libraries/MissionControlLibrary.php(55): application\libraries\MissionControlLibrary->processMissions(Array)
#1 /home/warlegen/xtremedarkness.uk.nf/application/libraries/UpdatesLibrary.php(154): application\libraries\MissionControlLibrary->arrivingFleets()
#2 /home/warlegen/xtremedarkness.uk.nf/application/libraries/UpdatesLibrary.php(56): application\libraries\UpdatesLibrary->updateFleets()
#3 /home/warlegen/xtremedarkness.uk.nf/application/core/common.php(99): application\libraries\UpdatesLibrary->__construct()
#4 /home/warlegen/xtremedarkness.uk.nf/public/index.php(18): require('/home/warlegen/...')
#5 {main}
  thrown|Where called: line  of  (in )<br>Where called: line  of  (in )<br>Where called: line  of application\core\ErrorHandler (in )<br>Where called: line 89 of application\core\ErrorHandler (in ErrorHandler.php)<br>Where called: line 75 of application\libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 146 of application\libraries\DebugLib (in DebugLib.php)|2020/09/25 12:58:42|
`
Fleet Returning Debug Trace
`|61.28.158.14|php|1|Uncaught Error: Class '\application\libraries\missions\' not found in /home/warlegen/xtremedarkness.uk.nf/application/libraries/MissionControlLibrary.php:106
Stack trace:
#0 /home/warlegen/xtremedarkness.uk.nf/application/libraries/MissionControlLibrary.php(67): application\libraries\MissionControlLibrary->processMissions(Array)
#1 /home/warlegen/xtremedarkness.uk.nf/application/libraries/UpdatesLibrary.php(155): application\libraries\MissionControlLibrary->returningFleets()
#2 /home/warlegen/xtremedarkness.uk.nf/application/libraries/UpdatesLibrary.php(56): application\libraries\UpdatesLibrary->updateFleets()
#3 /home/warlegen/xtremedarkness.uk.nf/application/core/common.php(99): application\libraries\UpdatesLibrary->__construct()
#4 /home/warlegen/xtremedarkness.uk.nf/public/game.php(19): require('/home/warlegen/...')
#5 {main}
  thrown|Where called: line  of  (in )<br>Where called: line  of  (in )<br>Where called: line  of application\core\ErrorHandler (in )<br>Where called: line 89 of application\core\ErrorHandler (in ErrorHandler.php)<br>Where called: line 75 of application\libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 146 of application\libraries\DebugLib (in DebugLib.php)|2020/09/23 17:47:56|
`

**Comment by BeReal86** [comment]
Hello, I downloaded the latest version from the develoment section as shown in the picture. I provided a clean install and sent the fleet on a mission and it came back successfully. I did not encounter any errors.

![resim](https://user-images.githubusercontent.com/16218107/94812188-12176900-03ff-11eb-8fe7-0d035ea4bb6b.png)

![resim](https://user-images.githubusercontent.com/16218107/94812437-66bae400-03ff-11eb-93c4-4a02df6f96bc.png)

![resim](https://user-images.githubusercontent.com/16218107/94812143-01ff8980-03ff-11eb-84da-34b98513f0b9.png)

**Comment by BeReal86** [comment]
the only problem i have encountered so far

<img width="1826" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/94816849-0af35980-0405-11eb-8253-811d368bcbb8.png">

**Comment by asparatu** [comment]
@BeReal86 I download the newest development version yesterday and did a test with it. I see that it is working also. I think I have an older version installed. 

Thank you for checking that for me. 

Issues that I have noticed in updating from 3.1.x to 3.1.x beta builds

There has to be a better way to update the database also when you change versions. There is a lot of issue going from the older 3.x version to the newer 3.x version. 

The database user account passwords in the earlier version are MD5 and the current version is SHA1, which causes problems trying to login to do the update. The other problem is the permission are the same between the versions. In the older version of 3.x in the options table row, 21 is different than the current version in row 21. 

In the admin panel for fleet, the movement page gives an error prettyCoords function. What happens the string is not cast as an integer. 

The code that give error
` private function buildBeginningBlock(array $fleet): array` 
    ` {` 
      `   return [` 
`            'beginning' => Format::prettyCoords(` 
`                  $fleet['fleet_start_galaxy'],` 
`                 $fleet['fleet_start_system'],` 
 `                $fleet['fleet_start_planet']` 
`             ),` 
       `  ];` 
   `  }`

Fix Code for the Error
` private function buildBeginningBlock(array $fleet): array` 
    ` {` 
      `   return [` 
`            'beginning' => Format::prettyCoords(` 
`                 (int) $fleet['fleet_start_galaxy'],` 
`                 (int) $fleet['fleet_start_system'],` 
 `                (int) $fleet['fleet_start_planet']` 
`             ),` 
       `  ];` 
   `  }`

You really can not update your current database to a newer version without doing set up the new database first and importing all the data only in the new one and making everyone change their passwords.

I think there should be a PHP CLI file that does update and so you don't need to be logon the admin page and have a deal with issue why it is not working.
