### ISSUE TITLE
some questions please

### ISSUE THREAD

**Issue by agony09** [XGProyect/XG-Proyect-v3.x.x#388]
Hello, I have questions about this very interesting project and I would be very happy to receive information.
- which PHP version on the server is recommended?
- I am interested in making a German version of it, which XG Proyect would you recommend? 
(also seen in the longer term for the future)
- Am I correct in assuming that the "SuperNova.WS" project is actually based on your project here?

regards and thank you

**Comment by BeReal86** [comment]
Hi @agony09 ,

>   which PHP version on the server is recommended?
Require PHP >= 7.3+
Require MySQLi >= 5.5+
>     I am interested in making a German version of it, which XG Proyect would you recommend?
We will announce the v3.1 version as the most stable version.
>     (also seen in the longer term for the future)
version 3.1 is the most suitable for the long term. Until this release, many files have been refactored and many improvements have been made and will continue. Of course, everything will happen over time.
>     Am I correct in assuming that the "SuperNova.WS" project is actually based on your project here?
The "SuperNova.WS" project is a substantially modified version of the "XNova RageRepack v226" project.



These are the answers I can give to your questions. When my friend @LucasKovacs  is available, he will complete the missing parts.

Thanks for your interest.

**Comment by agony09** [comment]
OK thanks.
I now wanted to test the script and have uploaded it from the "upload" directory to the server. I called the domain and only got a white window with the text:
---------------------------------------
Template not found or empty:
Location: ../../application/views/general/simple_footer.php
---------------------------------------
(from file: ../install/)

is there still something missing, or have I done something wrong?

**Comment by BeReal86** [comment]
Which version did you try to install? I did not have any problems when I installed the development branch.

**Comment by agony09** [comment]
I used the version: XGP v3.1.0 Beta 4. 
Now I found the file "simple_footer.php" in another directory and copied it 
into the directory "/../application/views/general/", then the installation worked.

Now it's working.
But there is another problem:
"Universe" is empty for "Login" and "Register". This means that when you click on "Universe", you can no longer enter anything in the fields "Username", "Password", etc. Then there is no courser. I then have to do a "reload" of the whole page so that I can add something. In the admin I couldn't find anything to give the universe / Galaxy a name.

![XG_Projekt_Login](https://user-images.githubusercontent.com/29257553/95958378-5fcda180-0e01-11eb-9173-7ae658227cca.png)

**Comment by BeReal86** [comment]
> 
> 
> I used the version: XGP v3.1.0 Beta 4.
> Now I found the file "simple_footer.php" in another directory and copied it
> into the directory "/../application/views/general/", then the installation worked.
> 
> Now it's working.
> But there is another problem:
> "Universe" is empty for "Login" and "Register". This means that when you click on "Universe", you can no longer enter anything in the fields "Username", "Password", etc. Then there is no courser. I then have to do a "reload" of the whole page so that I can add something. In the admin I couldn't find anything to give the universe / Galaxy a name.
> 
> ![XG_Projekt_Login](https://user-images.githubusercontent.com/29257553/95958378-5fcda180-0e01-11eb-9173-7ae658227cca.png)

The action you have done for simple_footer.php is correct. It has been fixed in future versions.


Universe selection place is closed. After installing, you can log in with the password and e-mail address you created while registering without making any selection.

**Comment by agony09** [comment]
Yes that's right. But when a new player wants to register. And if he clicks on "Universe", he can no longer enter any data. And thus do not register. That confuses. Then maybe you should get rid of the "universe"?

**Comment by BeReal86** [comment]
Sizi anlıyorum fakat şuan bizim yaptığımız tasarım bu. Tabiki bu değiştirilemez değil yada geliştirilemez.
If you think the player will not register because the universe is not selected. You can change the home page or the simplest is to write a note.

**Comment by agony09** [comment]
I think the problem is not fully understood.
If a player wants to register and clicks on "universum" beforehand, he CANNOT register anymore.
BECAUSE, for "Username", "Password", "E-Mail Address" NO coursor appears! The user can no longer enter anything, it just doesn't work. You can test it yourself:
1. first click once on "universe" in the register window, then
2. try to enter a username.
(I tried the latest Firefox)

**Comment by BeReal86** [comment]
When the universe is clicked, the user name cannot be written. When you click again, the user name can be written. I cannot say that it cannot be recorded, but yes, this is correct. I will also add this issue to our list.

**Comment by agony09** [comment]
ok, thanks a lot

**Comment by BeReal86** [comment]
We thank you. If you have any problems or questions, do not hesitate to contact us.

I wish you good games.

XGP Team

**Comment by LucasKovacs** [comment]
@agony09 version 3.1 has been released

**Comment by agony09** [comment]
thanks very much.
Another question about that.
What will be the difference between version 3.1. and 3.2?
(So that I can consider which version I will use to translate the language.)

**Comment by BeReal86** [comment]
@agony09 
We recommend that you wait for version 3.2 for language translation.
There will be some differences between each absolute version but as you can see in the report here https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/326 the articles are reviewed and compiled again.

**Comment by LucasKovacs** [comment]
@agony09 what ufuk said is true, although language lines are being added and improved all the time. Translation is really time consuming so you can start, and when 3.2 is released you would only make a few changes.

**Comment by agony09** [comment]
thank you. 
So it is recommended to translate version 3.1 into German? And then later to adopt it in version 3.2. Did I understand that correctly ? (I always use a translator here because my English is not that good)
So can i start?

**Comment by BeReal86** [comment]
Yes of course you can start. If you wish, you can get the necessary texts from Ogame Germany server for a more accurate translation. Thus, it will be easier and you will get a more accurate translation.

**Comment by LucasKovacs** [comment]
> thank you.
> So it is recommended to translate version 3.1 into German? And then later to adopt it in version 3.2. Did I understand that correctly ? (I always use a translator here because my English is not that good)
> So can i start?

Ja genau! 😄
