### ISSUE TITLE
Aumentar el límite de los almacenes.

### ISSUE THREAD

**Issue by TulioTesar** [XGProyect/XG-Proyect-v3.x.x#389]
Uso la versión 3.0.3 de XG-Proyect y quisiera saber si el límite de capacidad de los almacenes es una limitación del sistema o un bug.
![2020-10-14 18_08_55-Window](https://user-images.githubusercontent.com/72880357/96015954-70553a80-0e48-11eb-9215-1e51bb6c21c4.png)

A partir del nivel 33 de cualquier almacen, la capacidad del almacen se vuelve negativa y por lo tanto no se puede subir más.

Muchas gracias.
fdo. Tuliotesar.

**Comment by akahya22** [comment]
![image](https://user-images.githubusercontent.com/7634657/96030686-8386fb00-0e86-11eb-8785-ebce9dd1d52e.png)


Look like no bug with 3.1.x

**Comment by BeReal86** [comment]
@TulioTesar,  Thank you for choosing us and giving your feedback. There are some bugs in version 3.0.3, this is included in the problem you have experienced. However, many problems have been fixed in version 3.1. Soon, 3.1 stable version will be released.

**Comment by LucasKovacs** [comment]
@TulioTesar es recommendable que actualices a la version 3.1 Liberada Ayer. La versión es mucho más estable e incluye un método de actualización desde 3.0.3.
