### ISSUE TITLE
Phalanx

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#39]
In all but the task of giving the fault deployment

There is no scrollbar opened phalanx page. we need it

Notice: Undefined offset: 1454356924 in /home/eskiog/public_html/3/application/controllers/game/phalanx.php on line 177

Notice: Undefined variable: Fleets in /home/eskiog/public_html/3/application/controllers/game/phalanx.php on line 200	
![radar](https://cloud.githubusercontent.com/assets/16218107/12767906/de79f122-ca14-11e5-8a88-d4c10b388ab9.png)

Notice: Undefined offset: 1454356924 in /home/eskiog/public_html/3/application/controllers/game/phalanx.php on line 170

Notice: Undefined offset: 1454357512 in /home/eskiog/public_html/3/application/controllers/game/phalanx.php on line 195

Notice: Undefined variable: Fleets in /home/eskiog/public_html/3/application/controllers/game/phalanx.php on line 200
![radar 2](https://cloud.githubusercontent.com/assets/16218107/12767916/f6804c9e-ca14-11e5-82c1-d5709f33c927.jpg)

**Comment by XGProyect** [comment]
Fixed
