### ISSUE TITLE
[3.1.0-5]Registration problem in universe selection

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#390]
If a player wants to register and clicks on "universum" beforehand, he CANNOT register anymore.
BECAUSE, for "Username", "Password", "E-Mail Address" NO coursor appears! The user can no longer enter anything, it just doesn't work. You can test it yourself:
1. first click once on "universe" in the register window, then
2. try to enter a username.
(I tried the latest Firefox)

_Originally posted by @agony09 in https://github.com/XGProyect/XG-Proyect-v3.x.x/issue_comments/709880552_

**Comment by akahya22** [comment]
Same bug have in OSX Safari

**Comment by duhow** [comment]
By clicking in Universe select, #uni_selection sets as `display: inline` and blocks input on any other field.
Note there's a small line referring to the row of the universe, which is empty.
![image](https://user-images.githubusercontent.com/1145001/96301681-cfa57d00-0ff7-11eb-8b0a-a2ce0d373327.png)

There are several ways to fix this, either hide the "Universe" row until the multi-universe feature is implemented, or set a default name for universe.

**Comment by LucasKovacs** [comment]
@BeReal86 ready for test

**Comment by BeReal86** [comment]
@LucasKovacs 
I did a clean install. Login is working. I tried to register with a new player. This error occurs when you press the Register button.

![resim](https://user-images.githubusercontent.com/16218107/97108426-87184e80-16de-11eb-93b8-2bd4272e0771.png)

**Comment by BeReal86** [comment]
```
<script type="text/javascript">
                        <!--
                            select_uni('{base_path}'.replace('http://', '').replace('https://', '').slice(0, -1), '','');
                        //-->
                        </script>
```

It works like this but you can check it out anyway.

**Comment by BeReal86** [comment]
<img width="841" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/97113393-16335f80-16fb-11eb-9751-f67acad51863.png">

**Comment by BeReal86** [comment]
@LucasKovacs 

`<div id="row-0" class="server-row " title="" onclick="select_uni('{base_path}','{hm_universe_name}');" onmouseover="highlightRow(&#39;row-0&#39;);this.style.cursor=&#39;pointer&#39;" onmouseout="unHighlightRow(&#39;row-0&#39;);">`

to

`<div id="row-0" class="server-row " title="" onclick="select_uni('','{hm_universe_name}');" onmouseover="highlightRow(&#39;row-0&#39;);this.style.cursor=&#39;pointer&#39;" onmouseout="unHighlightRow(&#39;row-0&#39;);">`


<img width="655" alt="Screenshot_3" src="https://user-images.githubusercontent.com/16218107/97113732-585da080-16fd-11eb-8f49-7ae357a833af.png">

**Comment by LucasKovacs** [comment]
@BeReal86 check that you have two .htaccess files. One in the root, and one in public

**Comment by BeReal86** [comment]
Yeah yes i have

<img width="1215" alt="Screenshot_4" src="https://user-images.githubusercontent.com/16218107/97113926-7546a380-16fe-11eb-9719-65d4844b5245.png">


Root .htaccess
`<IfModule mod_rewrite.c>
    RewriteEngine on

    # define RewriteBase and store it
    RewriteCond %{REQUEST_URI}::$1 ^(.*?/)(.*)::\2$
    RewriteRule ^(.*)$ - [E=BASE:%1]

    # redirect requests to public folder
    RewriteCond %{THE_REQUEST} /public/([^\s?]*) [NC]
    RewriteRule ^ %1 [L,NE,R=302]

    RewriteRule ^((?!public/).*)$ %{ENV:BASE}/public/$1 [L,NC]
</IfModule>`

public .htaccess
`<IfModule mod_rewrite.c>
    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
`
