### ISSUE TITLE
I have problems with this !!

### ISSUE THREAD

**Issue by closepgames** [XGProyect/XG-Proyect-v3.x.x#395]
**Describe the bug**
Bug o Problems

**Help Me Plis!!**
Database connection failed: User 'XXXX' has exceeded the 'max_user_connections' resource (current value: 10)
Database query failed: Table 'XXXX.xgp_options' doesn't exist Last SQL Query: SELECT * FROM `xgp_options` WHERE `option_name` = 'lang';

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [Chrome]

 
 **Server (please complete the following information):**
 - PHP Version: [e.g. PHP 7.3.10]
 - MySQL Version: [e.g. MySQL 5.6]

**Extra**
I am not an expert on the script and less on the PHP, but it is the only invincible ... please help!!

**Comment by LucasKovacs** [comment]
@closepgames which hosting are you using? Do you think you can verify if the table xgp_options exists? You can do that from phpMyadmin

**Comment by BeReal86** [comment]
Hi @closepgames,

 As mentioned above, we need a little more information on this subject. It would be great if you could give one more detail exactly.

**Comment by closepgames** [comment]
@LucasKovacs 
@BeReal86 
I was checking and indeed I have xgp_options

DB Exception | 2020/10/22 00:47:44 | Where called: line 153 of application\core\Options (in FunctionsLib.php)Where called: line 67 of application\models\core\Options (in Options.php)Where called: line 47 of application\core\Database (in options.php)Where called: line 236 of application\core\Database (in Database.php)Where called: line 558 of application\libraries\DebugLib (in Database.php)Where called: line 164 of application\libraries\DebugLib (in DebugLib.php)
-- | -- | --


these are the errors that also appear to me, I was checking and I got new problems on the server but I don't know much about php ... I didn't think it would be complicated

**Comment by LucasKovacs** [comment]
@closepgames it seems that the amount of max db connections is too little. Maybe you can consider changing/upgrading the hosting

**Comment by closepgames** [comment]
@LucasKovacs 


I use version 3.1.0 that the official page says is stable, should I use another or is that fine?

**Comment by BeReal86** [comment]
@closepgames 

3.1 stable version is currently installed on our server and there is no error log. How did you take action for this error to occur?
I give an example: I sent the fleet to war. or I chose the fleet and sent it on a transport mission.

![resim](https://user-images.githubusercontent.com/16218107/96923005-54d9d780-14b9-11eb-92f8-e37d599e4b59.png)
![resim](https://user-images.githubusercontent.com/16218107/96923052-658a4d80-14b9-11eb-94c6-6a1fc65d12a7.png)

**Comment by closepgames** [comment]
Can you help me with the ftp error that won't let me connect after 20 seconds and won't let me upload or check the server.


@LucasKovacs 
@BeReal86

**Comment by LucasKovacs** [comment]
@closepgames it seems that your server is way too restricted. Any chance you can do an upgrade? Are you using a free version?

**Comment by closepgames** [comment]
@LucasKovacs If I was using the 000webhost, but I was going to change the host but since you say that I need another, I change it now I'm verifying the new one but it won't let me connect and it tells me the same thing.

possible solution please?

**Comment by BeReal86** [comment]
I registered for the trial and connected to the ftp server without any problem.
I think if you are sure that you are doing everything right. report this to support 000webhost

You can try another place for free hosting. My advice, either paid or free, is https://byet.host/

![resim](https://user-images.githubusercontent.com/16218107/96926942-fadc1080-14be-11eb-91d4-a5cbb618d1f8.png)

**Comment by closepgames** [comment]
@BeReal86  I'm sorry, I can't use ftp, the fillezilla tells me to wait 20 seconds and I don't know what else ... no host works for me, it tells me the same

**Comment by BeReal86** [comment]
You need to report this to the hosting company. 

In such cases related to hosting, there is nothing we can do from outside. Your service provider will give you the best assistance with connection problems. Because the problem seems to be with your service provider.

**Comment by closepgames** [comment]
well I'm going to upload it manually from the page's filemanager

one last thing, how can I add universes? or servers? ... so that this is not blank
@BeReal86

**Comment by BeReal86** [comment]
In order to create a universe, you need to complete the installation correctly after uploading the files.

**Comment by closepgames** [comment]
Well thank you very much for the help, but if you can't solve the FTP problem I can't even upload or modify the server ... thanks for the support
@BeReal86 @LucasKovacs

**Comment by BeReal86** [comment]
@closepgames 

Thank you for your feedback. You need to inform your service provider about your FTP problem. There is nothing we can do about it.
As you can see, I can upload files to the 000webhost server I just opened.

![resim](https://user-images.githubusercontent.com/16218107/96938899-32a18300-14d4-11eb-9321-8f5e3ebdff25.png)
