### ISSUE TITLE
Help Me, No host.

### ISSUE THREAD

**Issue by closepgames** [XGProyect/XG-Proyect-v3.x.x#396]
**No solution**
I changed the host to the recommended one and it keeps giving me the same problem

DB Exception | 2020/10/22 20:33:10 | Where called: line 153 of application\core\Options (in FunctionsLib.php)Where called: line 67 of application\models\core\Options (in Options.php)Where called: line 47 of application\core\Database (in options.php)Where called: line 236 of application\core\Database (in Database.php)Where called: line 558 of application\libraries\DebugLib (in Database.php)Where called: line 164 of application\libraries\DebugLib (in DebugLib.php)
-- | -- | --

DB Exception | 2020/10/22 20:46:10 | Where called: line 94 of application\models\core\Options (in XGPCore.php)Where called: line 36 of application\models\core\Options (in Model.php)Where called: line 54 of application\core\Database (in Model.php)Where called: line 78 of application\core\Database (in Database.php)Where called: line 93 of application\libraries\DebugLib (in Database.php)Where called: line 164 of application\libraries\DebugLib (in DebugLib.php)
-- | -- | --

**Comment by FGServers** [comment]
What hosting are you using?

**Comment by BeReal86** [comment]
@closepgames 

Can you please explain this error in more detail? How exactly to do it. Did I install without any problem?

**Comment by LucasKovacs** [comment]
@closepgames free hosting are a problem. I'm seeing that 000webhost has a lot of limitations. Can you tell me which page where you trying to access? Maybe there's a way to optimize it

**Comment by FGServers** [comment]
@closepgames try whit https://byet.host/

**Comment by closepgames** [comment]
as I had said change the host from 000webhost to byet.host and it continues to give the same problem about the errors of max_users_coneccts and that the xgp_opcions file is not detected but the latter I check again and if it is found.

here I leave the domain http://spaceinfamous.byethost33.com/

@LucasKovacs 
@FGServers
@BeReal86

**Comment by BeReal86** [comment]
@closepgames 

Is there a platform you use to chat? I will try to help you.

**Comment by closepgames** [comment]
@BeReal86

Yes, I have Facebook, it's the only one I use, although my english is not the best.... ¿speak spanish?

**Comment by BeReal86** [comment]
If you allow me I need your server information to check it. If you want, I can give my e-mail address. I want to check if you send it via mail / message. my spanish is bad too

**Comment by closepgames** [comment]
Okay, so I can email it to you ... will you send it to me? @BeReal86

**Comment by BeReal86** [comment]
@closepgames 

u.avcioglu86@gmail.com

**Comment by closepgames** [comment]
ready you can check @BeReal86

**Comment by BeReal86** [comment]
Error pictures sent to me. I add them here as well.

![error](https://user-images.githubusercontent.com/16218107/97049720-da768980-1584-11eb-8d3a-8fe754358b51.png)
![error2](https://user-images.githubusercontent.com/16218107/97049717-d9455c80-1584-11eb-817c-cf7392850669.png)
![error 3](https://user-images.githubusercontent.com/16218107/97049724-dba7b680-1584-11eb-93e4-39ffb8476ccf.png)

**Comment by BeReal86** [comment]
After logging into the game, the password is changed from the settings menu, and the game is entered with a new password. When looking at the logs, an error appears. Everything happens in the password change section

![resim](https://user-images.githubusercontent.com/16218107/97062260-d6596480-15a2-11eb-83c0-b66a59d040bd.png)

**Comment by duhow** [comment]
I'd suggest to provide PHP version details - and even try a reinstall. Are some files missing or having bad permission attributes (being unable to read)?

**Comment by LucasKovacs** [comment]
Closing since the owner did not reply anymore
