### ISSUE TITLE
[3.1.0] Spy Mission

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#397]
After sending an espionage mission, when the event occurs, an error occurs as shown in the picture when clicking Overview.

<img width="1873" alt="spy" src="https://user-images.githubusercontent.com/16218107/97093951-cc923880-1658-11eb-9b0b-ec0f94206c0f.png">

**Comment by LucasKovacs** [comment]
@BeReal86 this was a 3.1 issue.
