### ISSUE TITLE
[3.1.0] Transport Mission

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#398]
After sending the shipping task to another player, when the event happens, click Overview, the error in the picture occurs.

<img width="1880" alt="Transport" src="https://user-images.githubusercontent.com/16218107/97094189-34e21980-165b-11eb-97ea-dbf827336b3f.png">

**Comment by LucasKovacs** [comment]
@BeReal86 another 3.1 issue
