### ISSUE TITLE
Error index.php

### ISSUE THREAD

**Issue by Dokman** [XGProyect/XG-Proyect-v3.x.x#4]
![image](https://cloud.githubusercontent.com/assets/2290904/12679530/055f5be2-c6a5-11e5-87e3-d26c695bc39a.png)

**Comment by XGProyect** [comment]
I'm being unable to reproduce this issue.

**Comment by Dokman** [comment]
it's a fresh xampp nothing added

**Comment by XGProyect** [comment]
Por favor descarga el paquete una vez más, recién envie unos últimos cambios corrigiendo varias cosas.

**Comment by Dokman** [comment]
Gracias vi el commit arreglando el bug todo solucionado de momento ^^
