### ISSUE TITLE
[3.1.0] Interplanetary Missiles

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#400]
When I send a missile to destroy the defenses, there is an error like the picture. Also, Rockets damage the defense, but the person who sent the rocket is not reported. A report is only sent to the other player.

<img width="1115" alt="missiles_1" src="https://user-images.githubusercontent.com/16218107/97094396-5c39e600-165d-11eb-8991-81ad807b274e.png">
<img width="1116" alt="missiles_1_1" src="https://user-images.githubusercontent.com/16218107/97094398-5e03a980-165d-11eb-8787-e600578203ff.png">
<img width="707" alt="missiles_2" src="https://user-images.githubusercontent.com/16218107/97094401-60660380-165d-11eb-9052-08dc7c9660d7.png">

me messages
<img width="490" alt="report empty" src="https://user-images.githubusercontent.com/16218107/97094407-74116a00-165d-11eb-9a26-6d6ff8952bd7.png">

enemy messages
<img width="438" alt="Screenshot_1" src="https://user-images.githubusercontent.com/16218107/97094463-986d4680-165d-11eb-80ff-2e149c7ca4c1.png">

**Comment by LucasKovacs** [comment]
@BeReal86 another 3.1 issue. The person that sends the missiles does not get a message. This works as expected. The PHP notice was fixed.

**Comment by BeReal86** [comment]
The original OGame rocket attack report that came to me.

<img width="481" alt="Screenshot_24" src="https://user-images.githubusercontent.com/16218107/97107792-7239bc00-16da-11eb-879f-6d9a80ce954c.png">

**Comment by LucasKovacs** [comment]
@BeReal86 I was not aware of it. You can test it again

**Comment by BeReal86** [comment]
Anti-Ballistic Missiles does not appear.

<img width="443" alt="Screenshot_5" src="https://user-images.githubusercontent.com/16218107/97115429-b7281780-1707-11eb-8b14-63b7b7b6cf81.png">

<img width="452" alt="Screenshot_6" src="https://user-images.githubusercontent.com/16218107/97115559-5ea54a00-1708-11eb-95bb-6197f18e2671.png">
<img width="1167" alt="Screenshot_9" src="https://user-images.githubusercontent.com/16218107/97115560-606f0d80-1708-11eb-8a21-6ef678cd32d5.png">
<img width="441" alt="Screenshot_10" src="https://user-images.githubusercontent.com/16218107/97115561-6107a400-1708-11eb-8192-0d9136f539e5.png">

**Comment by LucasKovacs** [comment]
@BeReal86 what's the message when all the missiles are destroyed by anti-ballistic missiles?

**Comment by BeReal86** [comment]
This is our message when it disappears in anti-ballistic missiles.

It does not show the disappearing anti-ballistic missiles.
![resim](https://user-images.githubusercontent.com/16218107/97209524-84485700-17cd-11eb-9a5f-32768e229d13.png)

**Comment by LucasKovacs** [comment]
@BeReal86 in the original game hahah

**Comment by BeReal86** [comment]
> 
> 
> @BeReal86 in the original game hahah

:D Sorry his picture is here but if you want I can try to get a new report.

![resim](https://user-images.githubusercontent.com/16218107/97210513-b8704780-17ce-11eb-8668-b8ee25e62ce0.png)

**Comment by LucasKovacs** [comment]
@BeReal86 do you have one where all the rockets are destroyed? 9 interplanetary vs 9 or more anti ballistic

**Comment by LucasKovacs** [comment]
@BeReal86 I've sent new code to test. Any new info about missiles put it on the missions ticket here https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/326

**Comment by BeReal86** [comment]
I sent 10 missiles that I remember in that report. I sent 40 missiles in the Current Report.

![resim](https://user-images.githubusercontent.com/16218107/97213014-2cf8b580-17d2-11eb-9a73-1357e00aa072.png)

do you want other tries?

**Comment by LucasKovacs** [comment]
@BeReal86 that message is weird.. It says a rocket from ... but you sent 40... :/

**Comment by BeReal86** [comment]
Work fine

![resim](https://user-images.githubusercontent.com/16218107/97234948-ebc4cd80-17f2-11eb-88b2-9c0d8cacce5b.png)
