### ISSUE TITLE
Ion Technology effect on level destruction

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#401]
The concentration of ions allows for the construction of cannons, which can inflict enormous damage and reduce the deconstruction costs per level by 4%.

<img width="502" alt="Screenshot_3" src="https://user-images.githubusercontent.com/16218107/97094536-247f6e00-165e-11eb-90d2-a45ed5d5e5db.png">
<img width="322" alt="Screenshot_4" src="https://user-images.githubusercontent.com/16218107/97094538-26493180-165e-11eb-84cb-183b65d7d385.png">
<img width="526" alt="Screenshot_5" src="https://user-images.githubusercontent.com/16218107/97094539-277a5e80-165e-11eb-80c0-2ab767a363e3.png">

**Comment by FGServers** [comment]
Después de clonar la nueva versión del repositorio al desmantelar me salta este como 0 los recursos necesarios.

![1](https://user-images.githubusercontent.com/2124810/97789386-c3482500-1b9e-11eb-970c-3731ee783185.png)

**Comment by BeReal86** [comment]
Ion Technology level 0
<img width="405" alt="Screenshot_15" src="https://user-images.githubusercontent.com/16218107/97789859-fa392d80-1bd4-11eb-98c4-41a4a0b18397.png">

Ion Technology level 1
<img width="407" alt="Screenshot_14" src="https://user-images.githubusercontent.com/16218107/97789855-f86f6a00-1bd4-11eb-81a2-2b3fc84a72c6.png">

Ion Technology level 6
<img width="409" alt="Screenshot_16" src="https://user-images.githubusercontent.com/16218107/97789860-fb6a5a80-1bd4-11eb-8dcf-289199bee292.png">

**Comment by LucasKovacs** [comment]
@BeReal86 problem has been fixed

**Comment by BeReal86** [comment]
@LucasKovacs 

The cost of demolition has improved, no problem.

But there is an inconsistency regarding demolition times. Should I open a different report title?




<img width="941" alt="1" src="https://user-images.githubusercontent.com/16218107/97802381-fc8e9c80-1c53-11eb-9648-25fbd7451a23.png">
<img width="1123" alt="2" src="https://user-images.githubusercontent.com/16218107/97802383-fdbfc980-1c53-11eb-9592-e12752b031be.png">

Except for the destruction time, the duration of the research section is different.
<img width="925" alt="3" src="https://user-images.githubusercontent.com/16218107/97802387-ff898d00-1c53-11eb-8f6b-1d47e3157f40.png">

**Comment by LucasKovacs** [comment]
@BeReal86 You've to test on a server that's x1. Like UK Dorado

**Comment by BeReal86** [comment]
@LucasKovacs 
I'm going to test it on a server with ok x1 speed.
