### ISSUE TITLE
[3.1.0] Registration error

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#404]
I got this error on the 3.1 version on the hosting server. I don't know if it's still going on after the last changes.

PHP version: 7.4.9
Database server 5.5.5-10.3.25-MariaDB

https://drive.google.com/file/d/1ny3DUirjFZOWzTo85Wc7wtkbV1cumKEN/view?usp=sharing

**Comment by duhow** [comment]
#385 . Same issue as in HTTPS redirects to HTTP.
Update config hosting to redirect all HTTP to HTTPS.

**Comment by duhow** [comment]
Also #381 pending to merge.

**Comment by FGServers** [comment]
register error its this 
![image](https://user-images.githubusercontent.com/2124810/97110407-19195a80-16d1-11eb-8430-561670266ae8.png)

**Comment by LucasKovacs** [comment]
@BeReal86 @FGServers the changes proposed by @duhow are now part of 3.2. Please try again
