### ISSUE TITLE
[3.2.0] Difference in the Energy balance and level

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#405]
@LucasKovacs 
Except for the issue that @FGServers stated. There is only 1 unit of difference in the Energy balance part.

<img width="1002" alt="metal" src="https://user-images.githubusercontent.com/16218107/97239146-02bbed80-17fc-11eb-9aa5-9273fd109bc4.png">
<img width="1015" alt="Crystal" src="https://user-images.githubusercontent.com/16218107/97239153-064f7480-17fc-11eb-8c27-c33052b6129f.png">
<img width="1007" alt="deu" src="https://user-images.githubusercontent.com/16218107/97239158-08193800-17fc-11eb-8dbf-a1508234f737.png">
<img width="1060" alt="fusion" src="https://user-images.githubusercontent.com/16218107/97239163-0bacbf00-17fc-11eb-86ee-3ec3f55ed50d.png">
<img width="995" alt="solar" src="https://user-images.githubusercontent.com/16218107/97239228-267f3380-17fc-11eb-8f08-b4eccb7746ce.png">

https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/374#issuecomment-716207679

_Originally posted by @BeReal86 in https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/374#issuecomment-716881780_

**Comment by duhow** [comment]
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/f26dc480755f8925297b03f4deb78db19d7d5419/src/upload/app/controllers/game/infos.php#L538-L542

Having `$energy_prod` as a float, here it does `floor` to upper values, which causes the issue.
Check Metal mine values before processing as an example:
```
float(-4037.878210982)
float(-4600.2969617973)
float(-5234.8206806659)
float(-5950.2461736903)
float(-6756.4085585128)
float(-7664.300958563)
float(-8686.2077530381)
float(-9835.8528968225)
float(-11128.564991833)
float(-12581.460976878)
float(-14213.650509014)
float(-16046.463337808)
float(-18103.70222727)
float(-20411.924261247)
float(-23000.753679747)
```
