### ISSUE TITLE
Fix Creation moons in admin panel

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#41]
This line

`$combo_rows	.= '<option value="' . $planets_row['id'] . '" ' . ( $_GET['planet'] == $planets_row['id'] ? 'selected' : '' ) . ' >' .  $planets_row['planet_name'] . ' [' . $planets_row['planet_galaxy'] . ':' . $planets_row['planet_system'] . ':' . $planets_row['planet_planet'] . ']' . '</option>';`

change for this

`$combo_rows	.= '<option value="' . $planets_row['planet_id'] . '" ' . ( $_GET['planet'] == $planets_row['planet_id'] ? 'selected' : '' ) . ' >' .  $planets_row['planet_name'] . ' [' . $planets_row['planet_galaxy'] . ':' . $planets_row['planet_system'] . ':' . $planets_row['planet_planet'] . ']' . '</option>';`

And this line

`$combo_rows	.= '<option value="' . $planets_row['id'] . '">' .  $planets_row['planet_name'] . ' [' . $planets_row['planet_galaxy'] . ':' . $planets_row['planet_system'] . ':' . $planets_row['planet_planet'] . ']' . '</option>';`

change for this
`$combo_rows	.= '<option value="' . $planets_row['planet_id'] . '">' .  $planets_row['planet_name'] . ' [' . $planets_row['planet_galaxy'] . ':' . $planets_row['planet_system'] . ':' . $planets_row['planet_planet'] . ']' . '</option>';`

**Comment by XGProyect** [comment]
Applied!
