### ISSUE TITLE
[3.2.0] Fuel consumption within capacity

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#410]
In the original ogame, fuel consumption was excluded from capacity. As seen in XGP, fuel consumption is deducted from cargo capacity.

<img width="527" alt="Screenshot_17" src="https://user-images.githubusercontent.com/16218107/97790445-b39a0200-1bd9-11eb-963a-e2ffe8112b38.png">
<img width="514" alt="Screenshot_18" src="https://user-images.githubusercontent.com/16218107/97790448-b563c580-1bd9-11eb-9a96-b204ed006b17.png">
<img width="437" alt="Screenshot_19" src="https://user-images.githubusercontent.com/16218107/97790450-b694f280-1bd9-11eb-93dc-d75ea42ee595.png">
<img width="410" alt="Screenshot_20" src="https://user-images.githubusercontent.com/16218107/97790452-b7c61f80-1bd9-11eb-837b-e6781aa0e01c.png">

**Comment by FGServers** [comment]
Puede que sea un bug visual de OGame.

**Comment by duhow** [comment]
Looks like this is intended? It can be removed.
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/f26dc480755f8925297b03f4deb78db19d7d5419/src/upload/app/controllers/game/fleet4.php#L661

**Comment by LucasKovacs** [comment]
@duhow it needs more test. There are some JS also that takes care of it

**Comment by FGServers** [comment]
![image](https://user-images.githubusercontent.com/2124810/147474946-d4e64eef-ef3a-439a-abf1-9adcee1a8948.png)
Indeed, more testing is needed with ogame x1 because in ogame 8.5.0 they solved the bug of deuterium consumption that ships can transport

**Comment by LucasKovacs** [comment]
So what’s the conclusion? Does the fuel takes storage capacity or not?

**Comment by FGServers** [comment]
> ‎Entonces, ¿cuál es la conclusión? ¿El combustible toma capacidad de almacenamiento o no?‎

No lo probé por que ahora esta gonzalo viendo eso pero por lo que me dijo que ahora ocupa parte del espacio del almacenamiento para trasladar el combustible de la misión

Pero por mi conclusión lo veo asi

**Comment by LucasKovacs** [comment]
Ok so fuel is not part of the storage

**Comment by FGServers** [comment]
> Ok so fuel is not part of the storage
From what is seen in OGame it does not affect the storage of resources. and it's weird it should. it used to be like that

**Comment by LucasKovacs** [comment]
@FGServers / @BeReal86 currently does deuterium take space from cargo capacity? I want to implement this one, but I need to be sure

**Comment by BeReal86** [comment]
![resim](https://user-images.githubusercontent.com/16218107/234077690-d2c676a3-622c-4d76-a289-1f7f05c5ef07.png)

![resim](https://user-images.githubusercontent.com/16218107/234077942-44a01acf-727b-4898-a025-868ba410eb46.png)

Yes, I did a little experiment again. Deuterium doesn't take up space from cargo capacity.

**Comment by LucasKovacs** [comment]
Completed as part of commit#f7cf381e3d2d3cb800ae635b2605981ad58ee376
