### ISSUE TITLE
[3.2.0] Research time difference

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#414]
There are differences in research processes. Universe properties are set the same, but there are differences.

<img width="925" alt="3" src="https://user-images.githubusercontent.com/16218107/97802387-ff898d00-1c53-11eb-8f6b-1d47e3157f40.png">

**XGP Game speed settings**
General speed -->Construction Time and Research time
Fleet speed --> Fleet time
Production speed --> Production affects.

**Original OGame Game speed settings**
Fleet speed --> Fleet time
Economy speed --> Construction Time and Production affects.
Research speed --> Research time

<img width="441" alt="Screenshot_21" src="https://user-images.githubusercontent.com/16218107/97803018-6f9a1200-1c58-11eb-9aaa-81aa9b853496.png">

x1 Universe
<img width="920" alt="7" src="https://user-images.githubusercontent.com/16218107/97852067-4dab9880-1d07-11eb-88e4-055b8602a53d.png">

**Comment by FGServers** [comment]
and the research formula changed 2 times

Before to 5.5 version
The current formula is: (Metal + Crystal) / ( X * 1000 * (1 + R) )

X = Uni Speed
R = Addition of Research Lab levels according to your Intergalactic Research Network level

After to 5.5 Versión
What I would add is:

(Metal + Crystal) / ( X * 1000 * (1 + (E * R) )

X = Uni Speed
R = Addition of Research Lab levels according to your Intergalactic Research Network level
E = Number of Expedition slots available

**Comment by LucasKovacs** [comment]
@BeReal86 server is not x1, so not valid until you get a server x1 proof

**Comment by BeReal86** [comment]
The x1 universe has been tested.

<img width="921" alt="5" src="https://user-images.githubusercontent.com/16218107/98102621-d875ca00-1ea4-11eb-8016-6987db81791b.png">

**Comment by LucasKovacs** [comment]
@BeReal86 ready for quality

**Comment by BeReal86** [comment]
x1 Universe Work Fine.

But problems arise when the speed of the Universe increases. the room is due to this. In the original OGame Economy speed is General Speed in our opinion. But the research speed is calculated separately.



**XGP Game speed settings**

- General speed -->Construction Time and Research time
- Fleet speed --> Fleet time
- Production speed --> Production affects.

**Original OGame Game speed settings**

- Economy speed --> Construction Time and Production affects.
- Fleet speed --> Fleet time
- Research speed --> Research time


I open a different ticket for this problem?
