### ISSUE TITLE
[3.2.0] Ships and Defense time difference

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#415]
*since we are I leave the formula interpreted in my hangar way*
**Ships and Defense, in hours:**
(Metal + Crystal) / (2'500 * (1 + (level Shipyard)) * (2 ^ (level Nanite Factory)))

`$time = 3600 * ($pricelist[$element]['metal'] + $pricelist[$element]['crystal']) / (FunctionsLib::readConfig('game_speed') * (1 + ($current_planet[$resource['21']])) * pow(2, ($current_planet[$resource['15']])));`

Reference test in server x4 research speed
![11](https://user-images.githubusercontent.com/2124810/97873636-afafd200-1cf6-11eb-8e68-872518233f8d.png)

Reference: https://board.en.ogame.gameforge.com/index.php?thread/548906-formula-thread-v3/

**Comment by LucasKovacs** [comment]
@BeReal86 as I said, if it's not reported on a x1 server the bug is not valid.

**Comment by BeReal86** [comment]
Since the universe is very slow, I have only been able to compare these units now. I'll add in different pictures later.

<img width="813" alt="4" src="https://user-images.githubusercontent.com/16218107/98101557-723c7780-1ea3-11eb-845d-79b77bca78c5.png">

**Comment by BeReal86** [comment]
x1+ universe work fine
