### ISSUE TITLE
[3.2.0] 500. That’s an error.

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#419]
There is a local server setup, but when I install hosting, the loading screen does not appear.
I noticed this last night. I noticed while trying to update xgp live server files

<img width="1364" alt="Screenshot_12" src="https://user-images.githubusercontent.com/16218107/98357005-9039e180-2035-11eb-9a06-6b622e70206b.png">
<img width="1188" alt="Screenshot_13" src="https://user-images.githubusercontent.com/16218107/98357008-916b0e80-2035-11eb-9c22-3fc19e0c083f.png">

`
|85.101.42.221|php|E_WARNING|require_once(../../application/models/libraries/userslibrary.php): failed to open stream: No such file or directory|Where called: line 60 of application\libraries\UsersLibrary (in XGPCore.php)<br>Where called: line 47 of  (in UsersLibrary.php)<br>Where called: line 75 of  (in FunctionsLib.php)<br>Where called: line 75 of application\core\ErrorHandler (in FunctionsLib.php)<br>Where called: line 77 of application\libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 164 of application\libraries\DebugLib (in DebugLib.php)|3.2.0|2020/11/06 10:29:58|`

**Comment by LucasKovacs** [comment]
@BeReal86 re upload everything

**Comment by BeReal86** [comment]
`|85.101.42.221|php|E_WARNING|require_once(../../application/models/libraries/userslibrary.php): failed to open stream: No such file or directory|Where called: line 60 of application\libraries\UsersLibrary (in XGPCore.php)<br>Where called: line 47 of  (in UsersLibrary.php)<br>Where called: line 75 of  (in FunctionsLib.php)<br>Where called: line 75 of application\core\ErrorHandler (in FunctionsLib.php)<br>Where called: line 77 of application\libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 164 of application\libraries\DebugLib (in DebugLib.php)|3.2.0|2020/11/06 17:59:45|
`

I reinstalled. The same problem continues. I got this error from the log file.

**Comment by LucasKovacs** [comment]
@BeReal86 check the file name on /application/models/libraries/

**Comment by BeReal86** [comment]
![resim](https://user-images.githubusercontent.com/16218107/98439706-d1e58d80-2104-11eb-9209-06ce076c2ace.png)

**Comment by LucasKovacs** [comment]
@BeReal86 delete all files and re upload

**Comment by BeReal86** [comment]
@LucasKovacs 

The problem still persists. I have tried other hosting. The problem continues.

**Comment by BeReal86** [comment]
@LucasKovacs 
The problem still persists but I have tried other hosting. The problem is still the same.

**Comment by FGServers** [comment]
creo que lo solucione lucky rembre el archivo en minuscula userslibrary.php y se soluciono

**Comment by LucasKovacs** [comment]
@BeReal86 give it a try. @FGServers was right the name of the file was wrong, BUT only on GitHub, weird... it was fine on my local so I just deleted the file and re sent it.

**Comment by BeReal86** [comment]
the point that I can not understand anyway. localhost was working very well. it was just giving an error on the hosting server.

but now it works very well. 

<img width="1861" alt="Screenshot_3" src="https://user-images.githubusercontent.com/16218107/98539215-0429f300-229d-11eb-8667-bc3dc7b5e0f7.png">
<img width="1734" alt="Screenshot_4" src="https://user-images.githubusercontent.com/16218107/98539218-04c28980-229d-11eb-94b8-e184c15f7da6.png">

**Comment by duhow** [comment]
@BeReal86 your "localhost" may be Windows? If so, Windows File Systems (FAT32/NTFS) use **case insensitive** file names, while Linux ones (probably the external hosting) are **case sensitive**.
That means **UsersLibrary.php** file is different from **userslibrary.php**.

**Comment by BeReal86** [comment]
> @BeReal86 your "localhost" may be Windows? If so, Windows File Systems (FAT32/NTFS) use **case insensitive** file names, while Linux ones (probably the external hosting) are **case sensitive**.
> That means **UsersLibrary.php** file is different from **userslibrary.php**.

Yes i use windows 10 and the filesystem is NTFS

**Comment by FGServers** [comment]
> @BeReal86 your "localhost" may be Windows? If so, Windows File Systems (FAT32/NTFS) use **case insensitive** file names, while Linux ones (probably the external hosting) are **case sensitive**.
> That means **UsersLibrary.php** file is different from **userslibrary.php**.

En windows funciona perfecto, lo que me extraña que en el hosting tengo Cpanel y tira ese error
