### ISSUE TITLE
Mail feature

### ISSUE THREAD

**Issue by LucasKovacs** [XGProyect/XG-Proyect-v3.x.x#422]
- Choose from the admin panel the mailing system
- Possibility to configure SMTP from the admin panel
- New Mailing library

**Comment by FGServers** [comment]
Si configuras el email library de ci lo cambias a SMTP funciona enviar todos yo lo probé editando el email.php

**Comment by duhow** [comment]
No me parece adecuado tener una única parte de CodeIgniter para gestionar el mail, además de no estar documentado... 

Debería usarse una librería - yo ya sugerí PHPMailer, e incorporar la configuración a XGProyect en el panel de administración o en el archivo config.

**Comment by LucasKovacs** [comment]
@BeReal86 please give it a try now. You can configure it from the admin panel. @FGServers metele vos tambien a ver que tal te anda. Actualice la libreria de CI, ya que por el momento no pienso usar otra cosa.

**Comment by FGServers** [comment]
![image](https://user-images.githubusercontent.com/2124810/99110220-d14b6c00-25c8-11eb-9cf3-fd2e87bc6f63.png)
se ve asi

**Comment by BeReal86** [comment]
@LucasKovacs sending e-mail is making me have a problem. It could probably originate from the hosting company. For Codeintegner it says is there a wound that needs to be done or a component that needs to be activated on the server?

**Comment by LucasKovacs** [comment]
@BeReal86 there are cases where smtp is not enabled and does not allow to use it. In my hosting that was not possible. So I used sendgrid

**Comment by BeReal86** [comment]
@LucasKovacs Yes, maybe.  I couldn't understand anyway smtp only works in certain places.
I also failed with sendgrid.  maybe I made a mistake.  But I'm sure it works well. We've provided a lot of testing with jonamix.

https://www.smtper.net/
https://prnt.sc/viun2n

https://prnt.sc/viumpg

**Comment by BeReal86** [comment]
that's why I approve.

**Comment by FGServers** [comment]
> @BeReal86 there are cases where smtp is not enabled and does not allow to use it. In my hosting that was not possible. So I used sendgrid
> 
> @FGServers veo que en el template salen etiquetas {mailing_smtp_host}. Te faltaron los cambios de la DB

Hice instalación nueva
