### ISSUE TITLE
[Enhancement] Updating the Expedition formula v7.1

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#426]
ogame Expedition has repeatedly changed the amount and variety of calculations and incoming rewards. Currently the pre-current version is 7.1. Details about Calculation and Expedition are specified with links.

https://ogame.fandom.com/wiki/Expedition

https://forum.es.ogame.gameforge.com/forum/thread/1895-gu%C3%ADa-de-expediciones/

https://expocalc.universeview.be/

**Comment by LucasKovacs** [comment]
Most of it has been applied. There are some missing stuff like pirates, aliens which need further research.
