### ISSUE TITLE
[3.3.0-1244] Database error displayed to user when banned

### ISSUE THREAD

**Issue by duhow** [XGProyect/XG-Proyect-v3.x.x#428]
**Describe the bug**
Unexpected error on PHP regarding database connection? 

**To Reproduce**
- Ban user via database
```sql
UPDATE users SET user_banned = UNIX_TIMESTAMP("2020-11-16 00:46:58")
```
- Login

![image](https://user-images.githubusercontent.com/1145001/99263010-efaaa500-281e-11eb-96b4-32fb73dec1b5.png)
 
 **Server:**
- Docker files from project
- XGProyect ac501997d35523b86be88e680dbd70a831b58fc4

**Comment by BeReal86** [comment]
Hello, @duhow  in what version did this error occur?

Branch, commit, version? It would be very good if we specify it in the title of the report, or we can check it faster in the report.

**Comment by duhow** [comment]
I already shared it was in commit ac50199 .

**Comment by BeReal86** [comment]
yes I noticed that later.



![resim](https://user-images.githubusercontent.com/16218107/99294868-b2add500-2855-11eb-8f7e-4ba15c508ef6.png)
