### ISSUE TITLE
[3.3.0-1249] Difference in production

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#434]
I got pictures from x1 speed universe. There are differences in production. I don't remember having such a difference before. Looking at the old pictures, it is understood that there is no difference. But now there are differences in all but the crystal mine.

<img width="1172" alt="metal" src="https://user-images.githubusercontent.com/16218107/99389235-c4d85380-28e7-11eb-88f4-6ee92d7efc1c.png">
<img width="1172" alt="kri-deu" src="https://user-images.githubusercontent.com/16218107/99389231-c1dd6300-28e7-11eb-854b-168c4ba503bd.png">
<img width="1004" alt="fus" src="https://user-images.githubusercontent.com/16218107/99390174-3bc21c00-28e9-11eb-9588-a07bf1980584.png">
<img width="1027" alt="sol-pro" src="https://user-images.githubusercontent.com/16218107/99389241-c6a21700-28e7-11eb-9982-ff50e0ec2f2c.png">

**Comment by LucasKovacs** [comment]
@BeReal86 try again on 3.2 please. And see if you can reproduce this issue

**Comment by LucasKovacs** [comment]
@BeReal86 unable to reproduce. I have verified, and I get the same values as the dorado universe, which follows also the current formulas.

**Comment by BeReal86** [comment]
@LucasKovacs  i forgot the metal bonus factor. Jona reminded me. And I tried different positions in different universe, it's true.


Metal bonus

*Positions 6-10 now get a metal production bonus (similar to the crystal bonus on the first positions).

*The bonus means an increased base production for metal as long as a planet is on one of these positions. *Positions 6+10 have the same bonus= 17%. Positions 7+9 have the same bonus= 23%. 8 has another bonus= 35%. The bonus on position 8 is the hightest, on 6+10 the lowest.
