### ISSUE TITLE
Mission Expedition

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#44]
Notice: Undefined variable: fleet_capacity in /home/eskiog/public_html/beta7/application/libraries/missions/expedition.php on line 64

Notice: Undefined variable: fleet_points in /home/eskiog/public_html/beta7/application/libraries/missions/expedition.php on line 65

Notice: Undefined variable: message in /home/eskiog/public_html/beta7/application/libraries/missions/expedition.php on line 172

**Comment by XGProyect** [comment]
Fixed
