### ISSUE TITLE
[Feature] Soporte para PHP 8

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#440]
Mañana estaré actualizando mi vps con cpanel le integrare PHP8. quería saber si ya puedo empezar a desbugiar con esa versión. y si ya se puede reportar errores de esa versión

Lo interesante de esta versión son las uniones, Mixeds y Las Expresiones.
https://wiki.php.net/rfc/union_types_v2#supported_types
https://wiki.php.net/rfc/mixed_type_v2
https://php.watch/versions/8.0/match-expression

WampServer y Xampp ya lanzaron las versiones
![1](https://user-images.githubusercontent.com/2124810/101262784-da3ee180-371f-11eb-81f9-71950ed499d3.png)

**Comment by BeReal86** [comment]
Php 8 has a longer term life.

<img width="1079" alt="Screenshot_8" src="https://user-images.githubusercontent.com/16218107/101771504-18ab1680-3afb-11eb-9a40-02b536c102da.png">

**Comment by BeReal86** [comment]
<img width="1758" alt="Screenshot_9" src="https://user-images.githubusercontent.com/16218107/101911764-e0c2d280-3bd1-11eb-8dfe-eaecbbf352b8.png">

**Comment by FGServers** [comment]
Siempre sacan nuevas versiones para sacar cosas nuevas la 8.0 es una beta paso como con la 7.0 que salió la 7.1 rápido siempre pasa eso. yo lo que voy es empezar a desarrollar el código para q sea compatible por que las cosas q trae la 8.0 estarán en 8.1 o 8.2

**Comment by kov-lucas** [comment]
Que errores has notado entre 7.4 y 8?

**Comment by LucasKovacs** [comment]
Que errores ves entre 7.4 y 8?

**Comment by FGServers** [comment]
@LucasKovacs vos sabes que errores en php 8 no encontré ahora que hay una nueva versión del 8 voy a probar de nuevo

**Comment by BeReal86** [comment]
latest updated information

![Screenshot_28](https://user-images.githubusercontent.com/16218107/147474457-c7998875-29e6-4b44-8da1-14244578691b.png)

![Screenshot_29](https://user-images.githubusercontent.com/16218107/147474471-b4ad3af1-9b2c-49d6-88ca-0558be50dfda.png)

**Comment by LucasKovacs** [comment]
Para mantener las cosas ordenados cierro esto. Si ven algún error en PHP => 8 abren un error específico.
