### ISSUE TITLE
[BUG 3.2.0] Error en el tiempo de construccion en el overview

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#441]
![image](https://user-images.githubusercontent.com/2124810/101295521-da60df00-37fc-11eb-8889-027bd05dc0ab.png)
Cuando pones a construir algo te salta el error-

Crystal Mine (15 )1:17:19.38000011439999 --- > Te sale asi el tiempo
cancel |  
-- | --

**Comment by duhow** [comment]
This is a Javascript issue, HTML rendered by server displays with time:
```
Crystal Mine (27)<br /><div id="blc" class="z">34w 5d 9h 19m 48s</div>
```

**Comment by LucasKovacs** [comment]
Fixed on 3.3
