### ISSUE TITLE
How ı can edit Expeditions setting  and points

### ISSUE THREAD

**Issue by S4curity** [XGProyect/XG-Proyect-v3.x.x#442]
How ı can edit Expeditions , and ı want new point system For every 1000 resources spent,1 point is earned.

**Comment by BeReal86** [comment]
Hello, some php knowledge is required to edit the Expeditions section.  It is also valid for the scoring system. However, it is possible to make some adjustments from the statistics settings as shown in the picture.

<img width="1131" alt="Screenshot_7" src="https://user-images.githubusercontent.com/16218107/101699102-a2230000-3a8b-11eb-89bf-b7e81a38b993.png">

**Comment by S4curity** [comment]
How can ı add new server ? and last question In Is there a pirate war?

**Comment by FGServers** [comment]
> How can ı add new server ? and last question In Is there a pirate war?
They only have the old ones. Before the redesign, the expeditions have to be refactored to those of the redesign.

**Comment by S4curity** [comment]
I understant sir , how ı can contact with BeReal86 ?

**Comment by BeReal86** [comment]
Hi @S4curity, I think what your friend is trying to say is that the expeditions feature in XGP is not like the version in the redesign. It will be reorganized later.

Have you set up a server before? A hosting is required for this. and I recommend php version 7.4.

I don't know what you use for communication, but I can give my e-mail address. 
u.avcioglu86@gmail.com or skype ufuk.avcioglu
