### ISSUE TITLE
Oturum açma problemi

### ISSUE THREAD

**Issue by lodoskent** [XGProyect/XG-Proyect-v3.x.x#443]
Merhaba 

Oyunu kurduğum da açmış olduğum yönetici " ID ve Password " giremiyorum. Kayıt olunca oyuna giriş yapıyor. fakat tekrardan oyuna giriş yapmıyor. Oturum açılmıyor. yardım et ? ve 3.2.0 kurulum videosunu at

**Comment by BeReal86** [comment]
Merhaba,

Öncelik ile herhangi bir sorununuzu yada talebinizi yazarken ingilizce olarak da yazarsanır sevinirim. Diğer arkadaşların Türkçe bilgisi maalesef yoktur.

Bizim örnek bir kurulmuş oyunumuz var ve defalarca çıkış giriş yapabiliyoruz.

https://www.xgproyect.net/

ssl kullanıyor musunuz?

**Comment by BeReal86** [comment]
Do not hesitate to contact us if you have problems again. 

I wish you a good day.
