### ISSUE TITLE
[HELP] Guía de archivos / file guide

### ISSUE THREAD

**Issue by Reddington5** [XGProyect/XG-Proyect-v3.x.x#449]
Hola a todos, soy nuevo en XG y tengo conocimientos básicos de php y medios-altos en html y css.

Me gustaría saber si existe una guía de los archivos del juego. Por ejemplo: 

- Qué archivos tocar para añadir una nave, recurso, mina o tecnología. 
- Qué archivos se usan para el motor de batallas.
- Qué archivos configuran las expediciones.
- Qué archivos tocan la visión general (me gustaría hacer algo como el rediseño de OGame pero sin las funciones del mismo (subastador, importador, etc).

Muchas gracias a todos.

Un saludo.

-------

Hi everyone, I am new to XG and I have basic knowledge of php and medium-high in html and css.

I would like to know if there is a guide to the game files. For example:

- Which files to touch to add a ship, resource, mine or technology.
- What files are used for the battle engine.
- What files configure the expeditions.
- Which files touch the overview (I would like to do something like OGame redesign but without its functions (auctioneer, importer, etc).

Thank you very much to all.

A greeting.

**Comment by FGServers** [comment]
Repuestas:
1.Qué archivos tocar para añadir una nave, recurso, mina o tecnología.
Los archivos son varios
- Primero la base de datos ahora los edificios estan en la tablas "xgp_buildings". naves en "xgp_ships", Investigaciones en "xgp_research", Defensas en "xgp_defenses"
- Segundo: para agregarla tenes que cargarla al objects_collection.php que se encuentra en app/core/
- Hay deberás agregar la el nombre de la tabla que vas a utilizar $resource = [] acodarte de seguir el orden de ese numero. por que te va servir para el lenguaje dependiendo el idioma, en cambio si es una nave acodarte bien por que deberás tocar mas cosas para el motor de batalla y misiones. Si le quieres poner un requisito tendrás que agregara en la sección: $requeriments = [], para el valor en $pricelist = [], Si es nave o defensa $CombatCaps = [] para agregarle el ataque y escudos a su ves también para editar los fuegos rápidos.

Después deberás buscar esto, poder agregarlo al Árbol de tecnología.
// new ogame 
$reslist['resources'] = [1, 2, 3, 4, 12, 22, 23, 24];
$reslist['facilities'] = [14, 15, 21, 31, 33, 34, 41, 42, 43, 44];
$reslist['defenses'] = [401, 402, 403, 404, 405, 406, 407, 408];
$reslist['missiles'] = [502, 503];
$reslist['tech'] = [106, 108, 109, 110, 111, 113, 114, 115, 117, 118, 120, 121, 122, 123, 124, 199];
$reslist['fleet'] = [202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215];

- Despues deberas editar dicho archivos de lenguajes que por el momento hay 2 Ingles y Español.
- Si tenes que agregar nave tenes que modificar los archivos de Fleets, missions, Que se encuentran en app/libraries y por ultimo si es nave tendras que tocar el javascripts. para hacerlo funcionar en el Fleets.


2. Qué archivos se usan para el motor de batallas.
- El motor de batalla esta creado por JSTAR88 - esta dentro de la carpeta app/ThirdPArty

3. Qué archivos configuran las expediciones.
- El archivo esta en app/libraries/missions se llama Expedition.php (Por el momento se encuentra en desarrollo este le falta muchas misiones por agregar).

4. Qué archivos tocan la visión general (me gustaría hacer algo como el rediseño de OGame pero sin las funciones del mismo (subastador, importador, etc).

- Tenes que modificar los templates. que están en la carpeta "app/views/" teoricamente esto se desarrollara pero por el momento no es prioridad.

**Comment by Reddington5** [comment]
Buenos días:

Muchas gracias @FGServers .

Comentar dos cosas: 

1. El mercader no aparece. Me sale solo para rellenar almacenes con recursos, pero no me aparece el mercader para vender y cambiar recursos.
2. Me aparecen 7 errores como este en diferentes tablas (la instalación es limpia y no he tocado nada del juego aún): Database query failed: Table 'vpserver_juego.xgp_options' doesn't exist Last SQL Query: SELECT * FROM `xgp_options` WHERE `option_name` = 'mailing_protocol'; ¿se sabe a qué se debe?

¿Puedo ayudar en algo? Poco a poco iré haciéndome al sistema de archivos, por eso quería saber dónde está cada cosa. 

Muchas gracias y un saludo.

**Comment by FGServers** [comment]
El mercader no está terminado en la próxima versión ya debería estar  finalizado 

Y lo otro es para configurar el smtp para el evio de mails te faltan las tablas prueba instalar la versión 3.3.0
