### ISSUE TITLE
Alliance Deletation Runtime Error when Inactive Users is Deleted. 

### ISSUE THREAD

**Issue by asparatu** [XGProyect/XG-Proyect-v3.x.x#450]
**Describe the bug**
When a user is being deleted because they have not login for more than 30 days the account is deleted. If the user has an alliance, it will be deleted because they are the only one in the alliance. The error happens in the UsersLibrary.php when calling `$this->Users_Model->deleteAlliance($alliance['alliance_id]);` cause runtime error because the function is not found in the models userslibrary.php.  You need to call the `deleteAllianceById` function. The `deleteAlliance` function is the model/game/alliance.php.

Sorry, I have not figured out how to make a merge request yet. When i figure out will start using merge request for bug fixes.

The fix for the error is 

Line 147 to 156
`                // check and update
                if (is_numeric($userRank)) {
                    $this->Users_Model->updateAllianceOwner($alliance['alliance_id'], $userRank);
                } else {
                    $this->Users_Model->deleteAllianceById($alliance['alliance_id']);
                }
            } else {
                $this->Users_Model->deleteAllianceById($alliance['alliance_id']);
            }
        }`

**Comment by duhow** [comment]
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/b04b3a9d3159436770d1e44a143ee602e257aa4c/src/upload/app/models/game/alliance.php#L419
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/b04b3a9d3159436770d1e44a143ee602e257aa4c/src/upload/app/models/libraries/userslibrary.php#L75

Reported issue:
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/b04b3a9d3159436770d1e44a143ee602e257aa4c/src/upload/app/libraries/UsersLibrary.php#L147-L154

**Comment by LucasKovacs** [comment]
Fixed on 3.3
