### ISSUE TITLE
Admin Acct Bug Station

### ISSUE THREAD

**Issue by Dobrovodsky** [XGProyect/XG-Proyect-v3.x.x#452]
**Describe the bug**
When I log in with the Admin Account, everything works except the /game.php?page=station page, to increase the laboratory level, or the robots factory, it returns me the 500 error page once I click the "Instalaciones" menu it gives the error, it does not affect the rest of the players. This happened after I upgraded Graviton level from 1 to 2.

**To Reproduce**
1. Go to 'Research' (below market)
2. Click on 'Graviton' (Increase to level 2)
3. Go to 'Instalaciones' 
4. See error 500 afterwards

**Expected behavior**
I expect the Installations menu (/game.php?page=station) to show up even If I have the Graviton Level beyond level 1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 

**Smartphone (please complete the following information):**
 - Not using smartphone
 
 **Server (please complete the following information):**
 - PHP Version: 7.3.6
 - MySQL Version: 5.7.33 

**Additional context**
Rest of the users are unafected at the momment, but I dont want them getting blocked because they increase the Graviton tech beyond Level 1.

**Comment by Dobrovodsky** [comment]
![errorlog_server](https://user-images.githubusercontent.com/7953561/105224095-5a7ba380-5b22-11eb-828d-ed245ac3cf29.PNG)

**Comment by Dobrovodsky** [comment]
allright, while playing with the database, it seems that somewhere in between the Solar Plant level 40, Robot plants above 10 and Nanobots above 1, gets this errors. I have fixed them by lowering the plants levels and will try to test in real time levels to prevent DB crashes.

**Comment by LucasKovacs** [comment]
fixed on 3.3
