### ISSUE TITLE
Moons are not being created

### ISSUE THREAD

**Issue by Dobrovodsky** [XGProyect/XG-Proyect-v3.x.x#453]
**Describe the bug**
After receiving multiple attacks, and one successfully said that the metal and crystal was fusioned, I expected a moon but aparently nothing happened, even the battle message shows it, but no moon. 

**To Reproduce**
1. Send fleet to attack someones planet 
2. attack several times until the battle report tells you that a new satellite is formed. 
3. go to galaxy and cant find any moon except debris. 

**Expected behavior**
I expected a moon to be created when the battle report told me that I was created. 
![moon_ogame_issue](https://user-images.githubusercontent.com/7953561/105617132-99b82780-5da2-11eb-97b2-00295894fdf1.PNG)

**Screenshots**
I have attached a screenshot of the message. 
![moon_ogame_issue_3](https://user-images.githubusercontent.com/7953561/105617142-c5d3a880-5da2-11eb-8bcd-b57cdd3d5785.PNG)
![moon_ogame_issue_2](https://user-images.githubusercontent.com/7953561/105617143-c66c3f00-5da2-11eb-9575-d39b2a21fa53.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Edge -- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75

**Smartphone (please complete the following information):**
 
 **Server (please complete the following information):**
- PHP Version: 7.3.6
- MySQL Version: 5.7.33

**Additional context**
The message says that a moon was created on 1:1:1 but the attack happened on 1:1:9 and no moon was created. 

as a side note, I have this error on the servers error admin config panel, not sure what it means.

Undefined index: user_id
--
187.###.###.89 | php | E_NOTICE | 2021/01/21 14:59:16 | Where called: line of (in )Where called: line of (in )Where called: line of App\core\ErrorHandler (in )Where called: line 90 of App\core\ErrorHandler (in ErrorHandler.php)Where called: line 72 of App\libraries\DebugLib (in ErrorHandler.php)Where called: line 165 of App\libraries\DebugLib (in DebugLib.php)

**Comment by BeReal86** [comment]
Hi @Dobrovodsky ,

Thank you for your feedback. Which version of the game did you get these errors?

**Comment by LucasKovacs** [comment]
@BeReal86 can you reproduce this issue? Or @FGServer

**Comment by BeReal86** [comment]
@LucasKovacs Of course I'll try it tonight.

**Comment by LucasKovacs** [comment]
Fixed on 3.3
