### ISSUE TITLE
Unable to access the install page, fresh installation

### ISSUE THREAD

**Issue by ken013194** [XGProyect/XG-Proyect-v3.x.x#455]
**Describe the bug**
I have installed the httpd, php and mysql on a centos 7 box and copy the game files to the webroot. But when i access the install page it shows "**500. That’s an error.**", which does not shows the installation page. 
Found the error " **PHP Warning:  App\\core\\Database::confirmQuery(): Couldn't fetch mysqli in /var/www/xgp/app/core/Database.php on line 553**"

**To Reproduce**
1. Visit http://xxxxxxxx/public/install
2. shows "500. That’s an error."

**Expected behavior**
Expected to be into the installation page.

**Screenshots**
![image](https://user-images.githubusercontent.com/7060441/109628894-3a59ee00-7b7e-11eb-8d89-be55f85837bd.png)
![image](https://user-images.githubusercontent.com/7060441/109628940-480f7380-7b7e-11eb-978a-75e95b59aacd.png)

 **Server (please complete the following information):**
 - PHP Version: [PHP 7.3.27]
 - MySQL Version: [MySQL 5.7.33]

**Comment by RetryR1** [comment]
Same Error Here Cant Install

**Comment by FGServers** [comment]
Config.php it's deleted?

**Comment by RetryR1** [comment]
I Solved the Problem was a Porblem of my Domain Settingsd needed to Letsencrypt it first then my browser let me install the CMS
Thanks Anyway for your help
Am So., Juni 27, 2021 03:52 schrieb JonaMiX ***@***.***>:
 Config.php it's deleted?

**Comment by KamilPacanek** [comment]
> Config.php it's deleted?

Have the same issue on Ubuntu when unpacking the archive. File is there, but it has 0 bytes, that probably why OS or `unzip` just removed it.
To fix it just run `sudo touch app/config/config.php from root of your application.

**Comment by LucasKovacs** [comment]
The file was mistakenly added to 3.2, it is now removed from 3.3

**Comment by GavBurke** [comment]
> > Config.php it's deleted?
> 
> Have the same issue on Ubuntu when unpacking the archive. File is there, but it has 0 bytes, that probably why OS or `unzip` just removed it. To fix it just run `sudo touch app/config/config.php from root of your application.

This fixed my issue thanks! :)
