### ISSUE TITLE
[4.0] Database Migration to PDO

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#456]
I always had the doubt if xgp will continue with MySqli or will migrate to the PDO database engine or secure the set of CodeIgniter libraries.

**Comment by LucasKovacs** [comment]
Inicialmente, quería migrar a PDO, pero creo que por el momento XGP3 quedará en MySQLi y XGP4 ya tendría un core mas nuevo usando PDO o incluso doctrine.
