### ISSUE TITLE
Admin Panel throws err. code 500 on remote SSL Server Cert. Verification

### ISSUE THREAD

**Issue by Danielc20** [XGProyect/XG-Proyect-v3.x.x#457]
**Describe the bug**
Admin panel throws the 500 internal server error page when trying to verify the SSL Certificate from https://updates.xgproyect.org/latest.php.

**To Reproduce**
1. Login into your admin account
2. Click on 'Administrator Panel'
3. Login into Admin Panel

**Expected behavior**
Login into Admin page like it should.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Opera GX]
 - Version [3.2.0]

**Smartphone (please complete the following information):**
 - None
 
 **Server (please complete the following information):**
 - PHP Version: [8.0.7]
 - MySQL Version: [10.4.19-MariaDB]

**Additional context**
I do have a self-signed cert, to make the game work over 'https', wich is not trusted in my pc but the game works anyway. It's just the admin panel who doesn't work properly. Maybe it could be some kind of conflict between the two of the certs. (Remote from metioned url and the local one), but i dont really think so, since trying to login into the XGPROYECT Forums also gives a CERT verification error.

I temporarily fixed the issue in my code using a negation char (!) when it checks for the function "function_exists('file_get_contents')", so it just returns false and the admin panel works as intended.

**Comment by Crimsonbasilisk** [comment]
I had the same issue and turns out that my webhosting Php version was 8.0, just downgraded to 7.4x and problem solved.-

**Comment by LucasKovacs** [comment]
Anyone on PHP8 capable of reproducing this issue?

**Comment by FGServers** [comment]
> Anyone on PHP8 capable of reproducing this issue?

on localhost work perfect admin panel.

![image](https://user-images.githubusercontent.com/2124810/147511335-00fd4d39-3028-422b-b46c-3bd3d4206372.png)

**Comment by LucasKovacs** [comment]
Re open if you have more evidence in what’s going on.
