### ISSUE TITLE
Fleet and Defense destruction of the given player adds points on highscore, instead of subtracting

### ISSUE THREAD

**Issue by WinnieTheClue** [XGProyect/XG-Proyect-v3.x.x#459]
**Describe the bug**
Fleet destruction of players adds points on highscore, instead of subtracting
Defense points are not subtracted either, if destroyed.

**To Reproduce**
Have a fleet attack a planet, if both or 1 army get destroyed, points will be added on the highscore list under (fleet).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. Microsoft Edge]

 
 **Server (please complete the following information):**
 - PHP Version: PHP 7.3]
 - MySQL Version: MySQL 5.7]

**Additional context**

**Comment by WinnieTheClue** [comment]
Sometimes, destructed fleet are not given points to the one who lost them. Then the fleet points are unchanged.

**Comment by WinnieTheClue** [comment]
Colony ships are deleted from the "fleet" highscore, but not ordinary ships...

**Comment by WinnieTheClue** [comment]
![image](https://user-images.githubusercontent.com/89651424/131667707-72a66d69-28ce-4baf-9621-b92bff9a853f.png)

**Comment by LucasKovacs** [comment]
fixed on 3.3 - PR #461
