### ISSUE TITLE
Mission Recycle

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#46]
As long as the air fleet off this error code. After the error is deleted from the ruins of the field in the fleet.

Notice: Undefined index: target_name in /home/eskiog/public_html/1/application/libraries/missions/recycle.php on line 57

Fatal error: Call to undefined method application\libraries\missions\Recycle::recycle_message() in /home/eskiog/public_html/1/application/libraries/missions/recycle.php on line 84

Warning: Invalid callback application\core\Sessions::write, cannot access private method application\core\Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

Warning: Invalid callback application\core\Sessions::close, cannot access private method application\core\Sessions::close() in Unknown on line 0

**Comment by XGProyect** [comment]
Fixed
