### ISSUE TITLE
Espionage 

### ISSUE THREAD

**Issue by WinnieTheClue** [XGProyect/XG-Proyect-v3.x.x#460]
**Describe the bug**
Espionage reports show what the planet looked like the last time it was active, instead of showing real time. 

**To Reproduce**
Have someone be offline. Send 1 probe to the planet.
The report will show ressources and everything else within the limits of the technology level. 
Now send another probe, and the espionage will give a more accurate report.
![240796602_375512994060143_5782980500630779137_n](https://user-images.githubusercontent.com/89651424/131151640-97f25360-5b98-4db6-a373-d47ddd59faad.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version

 
 **Server (please complete the following information):**
 - PHP Version: [e.g. PHP 7.3]
 - MySQL Version: [e.g. MySQL 5.7]

**Additional context**

**Comment by LucasKovacs** [comment]
Fixed on #463
