### ISSUE TITLE
New Old Login

### ISSUE THREAD

**Issue by had3s688** [XGProyect/XG-Proyect-v3.x.x#465]
I search for someone that want make a new login or an other login for xgp. (maybe for money)
The datas are on my pc , but its from the old xgp and i really want it back for xgp 3.2.0

https://forum.xgproyect.org/forum/archives/archives-aa/xg-proyect-2-9-x/-2-9-x-foro-de-estilos/-2-9-x-estilos-en-desarrollo/5098-nuevo-login-had3s-procesamiento

anyone interesstet ? 
just write me had3s@live.de or some else.

and sorry its the wrong topic ...

**Comment by LucasKovacs** [comment]
You can use a freelancers site for this. Closing
