### ISSUE TITLE
Attack system dont work

### ISSUE THREAD

**Issue by karmakarmelo** [XGProyect/XG-Proyect-v3.x.x#466]
I have a problem with the attack system, when I send fleets to an enemygo to attack when they arrive, they simply leave me a white box with this message (An error occurred, we will resolve it soon as possible), I cannot locate the problem. It also leaves me a log error with this:

Monday 6th of December 2021 12:16:19 AM
ArgumentCountError: func_get_args() expects exactly 0 arguments, 1 given in C:\xampp\htdocs\app\ThirdParty\battle_engine\utils\DebugManager.php:59

Stack trace:
#0 C:\xampp\htdocs\app\ThirdParty\battle_engine\utils\DebugManager.php(59): func_get_args(Array)
#1 C:\xampp\htdocs\app\libraries\missions\Attack.php(179): DebugManager::{closure}()
#2 C:\xampp\htdocs\app\libraries\MissionControlLibrary.php(99): App\libraries\missions\Attack->attackMission(Array)
#3 C:\xampp\htdocs\app\libraries\MissionControlLibrary.php(47): App\libraries\MissionControlLibrary->processMissions(Array)
#4 C:\xampp\htdocs\app\libraries\UpdatesLibrary.php(147): App\libraries\MissionControlLibrary->arrivingFleets()
#5 C:\xampp\htdocs\app\libraries\UpdatesLibrary.php(54): App\libraries\UpdatesLibrary->updateFleets()
#6 C:\xampp\htdocs\app\core\common.php(194): App\libraries\UpdatesLibrary->__construct()
#7 C:\xampp\htdocs\app\core\common.php(60): App\core\Common->setUpdates()
#8 C:\xampp\htdocs\public\game.php(20): App\core\Common->bootUp('game')
#9 {main}
$_POST =
$_GET =
array (
)array (
  'page' => 'overview',
)

**Comment by LucasKovacs** [comment]
fixed on 3.3
