### ISSUE TITLE
[3.3] Producción de energía con diferentes velocidades

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#467]
No se si es un bug pero cuando cambio la produccion de diferente velocidad la energia no es afectada-

Velocidad a 1
![image](https://user-images.githubusercontent.com/2124810/147474341-ef081655-0911-4130-be7e-ed0ab7590815.png)

![image](https://user-images.githubusercontent.com/2124810/147474258-13e9cf55-015c-4d37-a292-814bdf2c19ac.png)

Velocidad a 100
![image](https://user-images.githubusercontent.com/2124810/147474292-9ac6f592-0f2e-4af8-82a4-601e914703d0.png)

![image](https://user-images.githubusercontent.com/2124810/147474312-f238b24b-e8dc-46f6-88cc-91a4932db02c.png)

Versión de php 7.4.25 - Testeado en php 8.0.12 tambien

**Comment by LucasKovacs** [comment]
Works as expected. Energy is never factored into speed.
