### ISSUE TITLE
Create Moon #2

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#47]
Diameter and Temperature Randomslect a not have problem.  but the problem manually input by going challenge.

Notice: Undefined index: diameter_check in /home/eskiog/public_html/1/application/controllers/adm/maker.php on line 211

Notice: Undefined index: diameter_check in /home/eskiog/public_html/1/application/controllers/adm/maker.php on line 215

Notice: Undefined index: temp_check in /home/eskiog/public_html/1/application/controllers/adm/maker.php on line 222

Notice: Undefined index: temp_check in /home/eskiog/public_html/1/application/controllers/adm/maker.php on line 225

![ay1](https://cloud.githubusercontent.com/assets/16218107/12834263/db6b22b2-cbae-11e5-9893-cbd5942c2e3b.png)
![ay2](https://cloud.githubusercontent.com/assets/16218107/12834268/e1854164-cbae-11e5-93f2-7f1ed83a06d7.png)

we add one, but the admin control panel appears on the entire planet. Is this a problem?

**Comment by XGProyect** [comment]
Fixed
