### ISSUE TITLE
XGP 3.3 -  1,334 commits (b00b5ee)

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#472]
1,334 post commit admin panel left menu not working.
I added a picture

xampp php 8.0.14
Windows 11
Firefox v95.0.2 x64

![Screenshot_30](https://user-images.githubusercontent.com/16218107/147860207-d5c5ff60-cac4-4979-8301-154351a28bef.png)

**Comment by FGServers** [comment]
F12 - Herramientas de desarrollo que error te tira en la consola. por que yo lo tengo andando perfecto en W11 en edge Versión 96.0.1054.62 (Compilación oficial) (64 bits) PHP 7.4.25

**Comment by LucasKovacs** [comment]
I don't have that problem. Are you on 3.3? Have you clear cache, and everything?

**Comment by BeReal86** [comment]
Yes, I'm on version 3.3. I will clear cache and history and try again. When I uploaded the commits 2 days ago, I did not encounter any problems. This was the last update. Now I'm going to download it again and do a clean install. I am using php 8.0.14 for tests.

**Comment by BeReal86** [comment]
I reinstalled xampp. I cleared the cache and did a clean install with fresh xgp3.3



![Screenshot_1](https://user-images.githubusercontent.com/16218107/147874066-ddcfa214-c55c-4c91-917f-fb68179cda6d.png)

**Comment by duhow** [comment]
@BeReal86 what commit are you checking? Is it b00b5ee1913c5c249eef654e56a599ab1c220fe9 ?

**Comment by BeReal86** [comment]
@duhow b00b5ee and later have problems like thinking in ACP. When I install the  b00b5ee , that is, I do not encounter any problems with the changes until December 31.

**Comment by BeReal86** [comment]
4453d5b commit

![Screenshot_2](https://user-images.githubusercontent.com/16218107/147875350-46ecf9a4-c06e-4a8b-bf66-f8757c64b9f9.png)

**Comment by FGServers** [comment]
Perdon por reabrir esto pero 
En la estructura no esta la carpeta vendor en el ultimo commit
![image](https://user-images.githubusercontent.com/2124810/147881645-877beccb-82d7-4647-b5ec-d3946e3e2e12.png)

**Comment by LucasKovacs** [comment]
Voy a revisar

**Comment by LucasKovacs** [comment]
@FGServers @BeReal86 missing folder has been pushed, it should work again
