### ISSUE TITLE
[3.3] Bug en el tiempo activo de los oficiales pero visual

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#475]
Bug visual en el tiempo de los oficiales activos dice 2 meses cuando deberia decir 3 y 7 dias
![image](https://user-images.githubusercontent.com/2124810/147884206-e0bc3aab-b8a8-475f-a3fc-b4a10356611c.png)

**Comment by LucasKovacs** [comment]
Estas seguro que es bug? La utlima vez que revise los oficiales los ajuste de acuerdo al rediseño

**Comment by FGServers** [comment]
Universo Supernova
![image](https://user-images.githubusercontent.com/2124810/148275050-7cfc0fa3-0824-4114-98ae-40b197c51dd1.png)

Universo Beta
![image](https://user-images.githubusercontent.com/2124810/148275229-4015377a-0e78-4c8f-ae87-e823e654de5c.png)

Creo que lo volvieron a modificar XD

**Comment by LucasKovacs** [comment]
@FGServers entonces basicamente, el bug es que debería estar en días, y no en meses?

**Comment by FGServers** [comment]
Estube viendolo y efectivamnte y cuando  llega el dia 1 que se termina muestra las horas restantes

**Comment by LucasKovacs** [comment]
Pero cual es la segmentación de esos tiempos?
* 90 dias
* 60 dias
* 30 dias
* ... ??

**Comment by FGServers** [comment]
![image](https://user-images.githubusercontent.com/2124810/234433745-5daa0989-eecc-4d71-9025-1ea161ea9bfb.png)
1 Semana

![image](https://user-images.githubusercontent.com/2124810/234433773-93b439ac-82a0-42d3-a7e6-872c37455a79.png)
9 dias

**Comment by LucasKovacs** [comment]
Se muestran dias como 133 o 134?  o 22 o 23 dias? o siempre redondea en dias el equivalente en semanas.

**Comment by FGServers** [comment]
No no redondea muestra los dias enteros

**Comment by FGServers** [comment]
![image](https://user-images.githubusercontent.com/2124810/234734992-48e0157c-a488-4d33-b634-4b947084121f.png)
ya lo fixie 

Elimine e hice un par de cambios, era facil alfinal ahora queda como ogame pero el problema que te quita un dia y en ogame cuando contratas el oficial dice 7 dias o 30 días en XGP dice 6 días y 29 días

 ```
public static function prettyTimeAgo(string $datetime, $full = false): string
    {
        $now = new DateTime();
        $ago = new DateTime($datetime);
        $diff = $now->diff($ago);
        $days = $diff->days;

        $string = [
            // 'y' => 'year',
            // 'm' => 'month',
            'd' => 'day',
            'h' => 'hour',
            'i' => 'minute',
            's' => 'second',
        ];

        foreach ($string as $k => &$v) {
            if ($k !== 'd') {
                if ($diff->$k) {
                    $v = $diff->$k . ' ' . $v . ($diff->$k > 1 ? 's' : '');
                } else {
                    unset($string[$k]);
                }
            } else {
                if (!empty($days)) {
                    $v = $days . ' ' . $v . ($days > 1 ? 's' : '');
                } else {
                    unset($string[$k]);
                }
            }
        }

        if (!$full) {
            $string = array_slice($string, 0, 1);
        }

        return $string ? implode(', ', $string) : '';
    }
```

**Comment by LucasKovacs** [comment]
Gracias Jona, pero el fix es otro. Ahi lo mande... ese método no debe cambiar.

https://github.com/XGProyect/XG-Proyect-v3.x.x/commit/6eba830f9c100c9c084ea56d5bf29db60c2372f6
