### ISSUE TITLE
[3.3-17e16b] Bug Overview

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#477]
El ultimo commit tiene un error en el overview

![image](https://user-images.githubusercontent.com/2124810/148270368-54462c7c-7482-4c89-a3e2-1663e0848368.png)

**Comment by LucasKovacs** [comment]
Tenes que instalar con composer

te vas a tu root, donde tenes composer.json y ahi haces composer install

**Comment by FGServers** [comment]
Hay lo probe y funciono en la version final para instalar en servidor ya vendrá activado o rem comendas algún hosting con Consola

**Comment by LucasKovacs** [comment]
El archivo zip para subir va a venir con todo pre-instalado. Esto es desarrollo

**Comment by FGServers** [comment]
Works perfect solo tenia que hacer composer update nada mas

**Comment by LucasKovacs** [comment]
genial. Hay un sistema nuevo de mailing incluido MailHog y PHPMailer, un golazo si lo podes mirar :) se que eso fue un dolor de cabeza por mucho tiempo. La configuración esta en la wiki

**Comment by FGServers** [comment]
> genial. Hay un sistema nuevo de mailing incluido MailHog y PHPMailer, un golazo si lo podes mirar :) se que eso fue un dolor de cabeza por mucho tiempo. La configuración esta en la wiki

Me baje el plugin en hosting con PHPmailer funciona perfecto en localhost con el plugin mailhog
![image](https://user-images.githubusercontent.com/2124810/148295664-189c9bce-e598-4b92-9cf5-cf5969bcdf77.png)

**Comment by LucasKovacs** [comment]
Excelente
