### ISSUE TITLE
Mission Attack

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#48]
When I first tried this I got an error. In later experiments did not any errors. Please be controlled better if

Fatal error: Call to a member function fetch_assoc() on a non-object in /home/eskiog/public_html/beta/application/core/Database.php on line 247

Warning: Invalid callback application\core\Sessions::write, cannot access private method application\core\Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

Warning: Invalid callback application\core\Sessions::close, cannot access private method application\core\Sessions::close() in Unknown on line 0

**Comment by XGProyect** [comment]
Fixed
