### ISSUE TITLE
XGP 3.3 - Commit 88571f8

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#482]
Clean install. Error when trying to login

Windows 11
Firefox 95.0.2
Xampp php 8.0.14

![Screenshot_3](https://user-images.githubusercontent.com/16218107/148609098-7a26bac0-a516-4d6c-9ffb-c0410288245a.png)

**Comment by FGServers** [comment]
Not a bug, install Composer, Go to root directory folder src/ and execute whit terminal composer update

**Comment by BeReal86** [comment]
> Not a bug, install Composer, Go to root directory folder src/ and execute whit terminal composer update

I'm just seeing this. Thanks
