### ISSUE TITLE
setView() on null

### ISSUE THREAD

**Issue by djlolito** [XGProyect/XG-Proyect-v3.x.x#483]
Version 3.3
Php Version 7.4
Error 500 al iniciar sesion.

Log generado:

[09-Jan-2022 16:59:52 Europe/Madrid] PHP Fatal error:  Uncaught Error: Call to a member function setView() on null in /app/core/Template.php:75
Stack trace:
#0 /app/core/Template.php(66): App\core\Template->setBlade('overview/overvi...', Array)
#1 /app/controllers/game/overview.php(107): App\core\Template->set('overview/overvi...', Array)
#2 /app/controllers/game/overview.php(68): App\controllers\game\Overview->buildPage()
#3 /public/game.php(57): App\controllers\game\Overview->index()
#4 {main}
  thrown in /app/core/Template.php on line 75

Instalado con otro prefix en tablas por si afectase.

**Comment by FGServers** [comment]
No es por eso pasa que tenes q ejecutar composer update en el root del directorio
