### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by Nykus** [XGProyect/XG-Proyect-v3.x.x#484]
![image](https://user-images.githubusercontent.com/1218974/157468112-9f05907c-c36c-4a21-9dd8-435b2bf5d31b.png)

can't login
I put name password , login and nothing happens

http://stellarimpact.online/index.php

**Comment by LucasKovacs** [comment]
Which XGP version are you on?

**Comment by Nykus** [comment]
the last version

**Comment by RockLee-BC** [comment]
Any solution to this? I downloaded the last package from here, it does the same thing to me, and the error log does not generate anything.

**Comment by elmouse19** [comment]
I have the same problem.

**Comment by LucasKovacs** [comment]
Que version de PHP usas @elmouse19 ?

**Comment by Graxo** [comment]
I have the same issue, but only with the admin login.

**Comment by LucasKovacs** [comment]
can you verify if this still happens with version 3.3?

**Comment by LucasKovacs** [comment]
No reply - closed

**Comment by bin9yuz79** [comment]
Hello, I cannot log in, I have the same problem. @LucasKovacs @Nykus
