### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by RedScorpion123** [XGProyect/XG-Proyect-v3.x.x#486]
Hello
If i Download the Game Files install it on my wwwroot Folder.
after i setup all data on the page with (Mysql Datas) the page told me to delete the install folder and press the Finalize butten thet give me the check is all okay.
normaly i sould come on the page after this step but not today :(.
my problem is after the install i get an error 500 and nothing else.
plz i need help

 **Server (please complete the following information):**
- Xamp : 8.1.4
 - PHP Version: 8.1.4
 - MariaDB: 10.4.24

**Comment by RedScorpion123** [comment]
[error logs.txt](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/8473983/error.logs.txt)

**Comment by FGServers** [comment]
> [error logs.txt](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/8473983/error.logs.txt)

XGP not working on PHP 8.x

**Comment by RedScorpion123** [comment]
which version is the best?

**Comment by RedScorpion123** [comment]
Thank you very much for the help. I have now installed version 7.4.28 and it works.

However, I have more errors in the admin panel
[error logs.txt](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/8474648/error.logs.txt)
:

**Comment by FGServers** [comment]
Download the last commit and reinstall again, after delete the config.php

**Comment by RedScorpion123** [comment]
I downloaded the stable version from the main page and reinstalled it. still the same errors appear.
If I delete the config.php in app\config\ then nothing works anymore.

**Comment by RedScorpion123** [comment]
Is there a way that you can look at it via teamviewer.

**Comment by RedScorpion123** [comment]
I'm in the process of creating a language pack for German, where can I upload it for you if it's even desired.

**Comment by FGServers** [comment]
> I downloaded the stable version from the main page and reinstalled it. still the same errors appear. If I delete the config.php in app\config\ then nothing works anymore.

change To xgp 3.3

**Comment by RedScorpion123** [comment]
Thank you for your help.
So far everything is working fine. We're testing everything right now. So far there was only one error:

Trying to access array offset on value of type null

xxx.xx.xxx.xxx | php | E_NOTICE | 2022/04/13 22:26:19 | Where called: line 47 of App\libraries\MissionControlLibrary (in C:\inetpub\wwwroot\game\app\libraries\MissionControlLibrary.php)Where called: line 99 of App\libraries\missions\Attack (in C:\inetpub\wwwroot\game\app\libraries\MissionControlLibrary.php)Where called: line 199 of App\libraries\missions\Attack (in C:\inetpub\wwwroot\game\app\libraries\missions\Attack.php)Where called: line 420 of App\core\ErrorHandler (in C:\inetpub\wwwroot\game\app\libraries\missions\Attack.php)Where called: line 75 of App\libraries\DebugLib (in C:\inetpub\wwwroot\game\app\core\ErrorHandler.php)Where called: line 165 of App\libraries\DebugLib (in C:\inetpub\wwwroot\game\app\libraries\DebugLib.php)


I'm already translating into German. That also works without any problems.
