### ISSUE TITLE
Responsive skin

### ISSUE THREAD

**Issue by voignar** [XGProyect/XG-Proyect-v3.x.x#489]
Quisiera saber si hay alguna skin responsive para esta versión ya que es bastante incómoda de jugar en movil

**Comment by BeReal86** [comment]
Hola, No tenemos una vista compatible con dispositivos moviles en este momento.

**Comment by BeReal86** [comment]
Please do not hesitate to contact us.

**Comment by devrimmehmet** [comment]
devrimmehmet@gmail.com
Please contact me. I would like to be involved in your project, at least to provide support for the Turkish version.
