### ISSUE TITLE
Raspberry Pi installation problem

### ISSUE THREAD

**Issue by Mtt0836** [XGProyect/XG-Proyect-v3.x.x#490]
Hi,

i've tried to install XGP on Raspberry Pi 3 b+

I have installed apache 2, php 7.4, mariaDB, sqlite extension, phpmyadmin but every php page in XGP is blank.
The PHPmyAdmin works fine, i have created the DB.

I attach the error log of Apache service:
[error.log](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/9070543/error.log)

Please give me an help
THX

**Comment by LucasKovacs** [comment]
Something wrong with your paths
