### ISSUE TITLE
Enrutador URL

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#493]
Hay alguna manera de adaptarle algun enrutador a las url para quitar las variables, ?page= y convertialas en /overview /instalation. o conviene hacerlo del htaccess

**Comment by MahmutHizal** [comment]
Easiest way is .htaccess i think. But i suggests a few 3rd party modules:
https://github.com/symfony/routing
https://lumen.laravel.com/docs/9.x/routing
https://laracasts.com/discuss/channels/laravel/using-routing-outside-of-laravel-without-the-huge-dependency-list?page=1&replyId=352074
