### ISSUE TITLE
Infected file detected

### ISSUE THREAD

**Issue by RockLee-BC** [XGProyect/XG-Proyect-v3.x.x#495]
It is the latest stable version that I downloaded from here, I don't know if it is a problem with my hosting but I warn you. The game worked fine but I get a ticket that a file is infected that I should look at it but without much more details... I'm not very sure that's why I report it.

1. Download the latest package from GitHub
2. Upload and unzip it
3. Install and play a few minutes
4. Report from my supplier

> Dear,
> 
> We inform you that we have detected the upload or modification of an infected or malicious file to your cpanel account within the “public_html” directory, due to this we have sent the file to the quarantine directory located at '/home/quarantine/'.
> 
> The detection of this file has been done automatically, if you uploaded or recently edited the file we recommend reviewing its content and cleaning it before trying to upload it again.
> 
> In the event that you have not uploaded or modified this file, we recommend carrying out a complete review of your account, since it could be compromised, we recommend changing the password of cpanel and FTP accounts, strong passwords should be used.
> 
> 
> SERVICE DATA:
> 
> User: tuweb.net
> Server: yourwebdns.net
> plan: plan1
> Status: Active
> 
> REPORT OF INFECTION DETECTED:
> 
> /home/public_html/xgame/app/views/general/notices_view.php
> 
> IMPORTANT:
> 
> The files sent to quarantine can be downloaded from the backup section of cpanel, which will be automatically deleted after 60 days from when they were sent there.
> 
> Best regards
> Support Department

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox and Chrome
 - Version 104.0.1 (64-bit) / 105.0.5195.102 (Build oficial) (64 bits)
 
 **Server (please complete the following information):**
 - PHP Version: PHP 7.4.30
 - MySQL Version: MySQL 5.7

**Comment by MahmutHizal** [comment]
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/master/src/upload/app/views/general/notices_view.php

```html
<table width="100%" style="border: 3px solid {color}; text-align:center;background:transparent;">
    <tr style="background:transparent;">
        <td style="background:transparent;">
            {message}
        </td>
    </tr>
</table>
{jump_line}
```

what about your file?

**Comment by RockLee-BC** [comment]
After investigating and reviewing, I noticed the failure was due to the active mod_security (apparently it does not like many redirects). Also by disabling the module the login issue was fixed.
