### ISSUE TITLE
Error on Docker Version

### ISSUE THREAD

**Issue by AlejandroSobral** [XGProyect/XG-Proyect-v3.x.x#496]
**Describe the bug**
Hi, I'm trying to run a instance from a Docker Container using the compose yml file. After the compose itself (Where I had to create a network in particular beforehand), I get the following error at "localhost" from a browser:

Database query failed: Table 'xgp.xgp_options' doesn't exist Last SQL Query: SELECT * FROM `xgp_options` WHERE `option_name` = 'lang';

**To Reproduce**
Create a network called xgp_network for Docker.
Compose the image & run the container: docker-compose up

**Expected behavior**
To work and begin installation?

**Desktop:**
 - OS: Windows 10

**Comment by Crystal1462** [comment]
I am not finished with it but in order to get this to install easily I had to create a new docker-compose file.  It isn't polished enough to share yet sorry but figured I would chime in to let you know what I had to do for a solution.

**Comment by AlejandroSobral** [comment]
Thanks a lot, no hurry at all.

**Comment by LucasKovacs** [comment]
@AlejandroSobral the issue that you get is probably because your config.php has data but the DB is not yet installed.

Clean your config.php file and retry the install
