### ISSUE TITLE
Adding Cryptocurrency as new resource ingame

### ISSUE THREAD

**Issue by Ruxiol** [XGProyect/XG-Proyect-v3.x.x#499]
**Is your feature request related to a problem? Please describe.**

Adding crypto integration, like for sample, adding Bitcoin/Altcoin into one of the game resources, that can be taken or lost by attack on planet.

Is there a way to add this, and if someone is willing to help me try this method, would pay.

**Comment by nextweb-sfe** [comment]
XGP follows the original line once XGP3.3.x is finished I am going to put together a guide on how to add new resources.

**Comment by LucasKovacs** [comment]
We also don't intend to add anything that contributes to make a profit. You will have to implement that by yourself or hiring a developer to do so.
