### ISSUE TITLE
Alliance #2

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#50]
Warning: Illegal string offset 'alliance_ranks' in /home/eskiog/public_html/1/application/controllers/game/alliance.php on line 374

Notice: Uninitialized string offset: 0 in /home/eskiog/public_html/1/application/controllers/game/alliance.php on line 374

Notice: Undefined variable: alliance_name in /home/eskiog/public_html/1/application/controllers/game/alliance.php on line 498

These errors are available

Notice: Undefined variable: alliance_name in /home/eskiog/public_html/1/application/controllers/game/alliance.php on line 495

Notice: Undefined variable: PHP_SELF in /home/eskiog/public_html/1/application/controllers/game/alliance.php on line 496

These errors are out. When the screen is blank contunue exit. normally it should be directed to the search page and create alliances.

![ayril](https://cloud.githubusercontent.com/assets/16218107/12834740/9f55edb2-cbb2-11e5-92ab-ac6f50521d38.png)
![bos](https://cloud.githubusercontent.com/assets/16218107/12834743/a897bc7a-cbb2-11e5-9ba9-bfcd33fe355e.png)
![1](https://cloud.githubusercontent.com/assets/16218107/12834748/b14e53ec-cbb2-11e5-8514-916588d61e1f.png)
![db](https://cloud.githubusercontent.com/assets/16218107/12834755/c093f5dc-cbb2-11e5-80c3-387b432ce295.png)

**Comment by XGProyect** [comment]
All of the warning and notices were fixed. Couldn't reproduce the DB error though.
