### ISSUE TITLE
[Feature] Vista del imperio ya no es mas necesario el comandate

### ISSUE THREAD

**Issue by nextweb-sfe** [XGProyect/XG-Proyect-v3.x.x#505]
A partir de la 9.0 de ogame la vista del imperio ya no necesita tener el comandante activado

![image](https://user-images.githubusercontent.com/29988859/231312896-55bc6c86-7339-4f48-b3fb-e7cc4004f50d.png)

PD: Soy JonaMix es mi nueva cuenta.

**Comment by LucasKovacs** [comment]
Is this confirmed? Is it universe based?

**Comment by BeReal86** [comment]
Yes, I just checked.

![Screenshot_3](https://user-images.githubusercontent.com/16218107/233178298-f786741d-0671-4d81-a6d7-39e404e9428c.png)

![Screenshot_4](https://user-images.githubusercontent.com/16218107/233178335-137e3141-f0a0-4723-b9aa-c6c6c1d60fc1.png)

**Comment by FGServers** [comment]
Ahora las ventajas del comandantes son 3 nomas

+40 favoritos
Lista de construcción
Escáner de transportes
Sin publicidad --> XGP no cuenta con publicidad asi que son 3
