### ISSUE TITLE
undefined index: table_name

### ISSUE THREAD

**Issue by manuelkamp** [XGProyect/XG-Proyect-v3.x.x#507]
[ip-address-of-reverse-proxy] | php | E_NOTICE | 2023/04/13 12:52:16 | Where called: line of (in )Where called: line 46 of App\controllers\adm\Repair (in admin.php)Where called: line 54 of App\controllers\adm\Repair (in repair.php)Where called: line 77 of App\core\ErrorHandler (in repair.php)Where called: line 75 of App\libraries\DebugLib (in ErrorHandler.php)Where called: line 165 of App\libraries\DebugLib (in DebugLib.php)

**Comment by BeReal86** [comment]
Hello,

Thank you for your feedback. What version and where do you get this error? 
Can you explain the error a little bit?

**Comment by manuelkamp** [comment]
Hello, this error is in the admin UI of the game, and not just once. I do not know what it is for, since I just installed the game and do not know which function may not be working, since I do not know the game from elsewhere.

**Comment by LucasKovacs** [comment]
Which php version are you on?

**Comment by manuelkamp** [comment]
PHP 7.4.3-4ubuntu2.18 (cli) (built: Feb 23 2023 12:43:23) ( NTS )

**Comment by LucasKovacs** [comment]
Should be fixed on 3.3
