### ISSUE TITLE
Replace SWF trailer on startpage with video or animated gif

### ISSUE THREAD

**Issue by manuelkamp** [XGProyect/XG-Proyect-v3.x.x#508]
This is a feature request for replacing the now on all browsers banned swf trailer with a actual video file or animated gif. now it shows just "plugin not available", which is not nice.

**Comment by manuelkamp** [comment]
i implemented that for the 3.2 stable, but found out, that it is not there in this 3.3 repo anymore

**Comment by LucasKovacs** [comment]
This has been implemented on v3.4
