### ISSUE TITLE
Release Package v3.3 is not working

### ISSUE THREAD

**Issue by manuelkamp** [XGProyect/XG-Proyect-v3.x.x#511]
I want to do the manual installation of the current 3.3 release zip file.

Browsing to the landing page fails, with server error 500:
Apache logs show the following lines:

`[Fri Apr 14 12:44:05.690270 2023] [php7:warn] [pid 134] [client 10.0.3.5:62488] PHP Warning:  require(/var/www/html/app/core/Common.php): failed to open stream: No such file or directory in /var/www/html/public/index.php on line 8`
`[Fri Apr 14 12:44:05.690298 2023] [php7:error] [pid 134] [client 10.0.3.5:62488] PHP Fatal error:  require(): Failed opening required '/var/www/html/app/core/Common.php' (include_path='.:/usr/share/php') in /var/www/html/public/index.php on line 8`

The issue is, that the path unzipped is
`/var/www/html/app/Core/Common.php`
instead of
`/var/www/html/app/core/Common.php`

Edit: If I rename the "Core" folder to "core", this error occurs, where this path expects "Core" instead of "core":
`[Fri Apr 14 12:55:45.697966 2023] [php7:warn] [pid 526] [client 10.0.3.5:63575] PHP Warning:  include(/var/www/html/vendor/composer/../../app/Core/ErrorHandler.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/ClassLoader.php on line 571`

**Comment by FGServers** [comment]
It's in Development this package.

**Comment by manuelkamp** [comment]
sure? There was a stable release 3.3 published 2 hours ago

**Comment by FGServers** [comment]
After install XGP3.3.x your run Composer update and make folder compiles in public folder, the stable project it's XGP 3.2

**Comment by manuelkamp** [comment]
I did a manual installation without composer, docker, docker-compose etc. and want to have it without docker, since I run LXC on my HA cluster and do not want docker container inside LXCs...

**Comment by manuelkamp** [comment]
so, I now downloaded the 3.3 release zip onto a fresh LXC (apache2, php8.2). Unzipped the files into /var/www/html. Where do I now run composer? since there is no composer.json, it fill of course fail if I run it in /var/www/html path?

**Comment by manuelkamp** [comment]
Yes I'm using exactly this package from this link.

The pat is not lowercase in the zip (also if extracted), but the error message says, lowercase is expected. If I change it to lowercase another error occurs, saying Uppercase is needed (see initial post).

**Comment by LucasKovacs** [comment]
can you try with the branch 3.4? I have sent a fix, if not I will make a package

**Comment by LucasKovacs** [comment]
I did an update to the package anyway... check now please
https://github.com/XGProyect/XG-Proyect-v3.x.x/releases/download/v3.3.0/XGP3.3.zip

**Comment by manuelkamp** [comment]
Yup, that seems to work now (I get the install screen). I will try to install and upgrade the 3.2 database now and will come back with an edit soon.

**Comment by LucasKovacs** [comment]
There are actually no DB changes on 3.3 besides the version update

**Comment by manuelkamp** [comment]
ok, then I will skip that.

**Comment by manuelkamp** [comment]
So, it took me a while, because I wanted to test everything on fresh LXCs.

Just the 3.4 branch did not work, the following error occured:
`[Fri Apr 14 19:22:30.447722 2023] [php:warn] [pid 21142] [client 10.0.3.5:55024] PHP Warning:  require_once(/var/www/html/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/app/Core/Common.php on line 22`
`[Fri Apr 14 19:22:30.447760 2023] [php:error] [pid 21142] [client 10.0.3.5:55024] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/app/Core/Common.php:22\nStack trace:\n#0 /var/www/html/public/index.php(8): require()\n#1 {main}\n  thrown in /var/www/html/app/Core/Common.php on line 22`

Just the new package 3.3 did work.

The 3.4 branch replacing files over the old 3.3 package did work.
