### ISSUE TITLE
Release v3.3 Administration UI not working

### ISSUE THREAD

**Issue by manuelkamp** [XGProyect/XG-Proyect-v3.x.x#512]
Sorry to be here again, the Admin UI in release 3.3 (and also dev-branch 3.4) is not working. It does not show the sub-menus in the left menu bar. This is a screenshot of a fresh installation (no upgrade from 3.2) of release package 3.3

![Screenshot 2023-04-14 200344](https://user-images.githubusercontent.com/48356947/232122975-f95d05a4-372f-475e-8d82-ec5fe4670855.png)

not browser related issue, tried firefox too: it gives more details about the error (sorry, it is in german, but you see that the issue is with wrong mime type somewhere in loading the .js files)

![Screenshot 2023-04-14 201701](https://user-images.githubusercontent.com/48356947/232125652-9fac4861-ad55-4a59-be0a-cd992f48a18d.png)

the translation is: MIME-type text/html is not a valid MIME-type for JavaScript. I found this: https://stackoverflow.com/questions/3630006/error-uncaught-syntaxerror-unexpected-token#comment58476440_24442984

**Comment by FGServers** [comment]
Confirm this bug Missing vendor folder from public/admin
[vendor.zip](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/11237037/vendor.zip)

**Comment by LucasKovacs** [comment]
Thanks Joan. Fixed on 3.4 and the 3.3 package
