### ISSUE TITLE
[XGP 3.3] Compiles missing folder in public

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#514]
**Describe the bug**
When you log in and it redirects you to the Overview

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/2124810/232150295-5bb38435-2c55-48b4-814e-6dad5b31680b.png)

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Edge
 - Version Last

**Smartphone (please complete the following information):**
 
 **Server (please complete the following information):**
 - PHP Version: 8.2
 - MySQL Version: 5.6

**Comment by LucasKovacs** [comment]
fixed on #524
