### ISSUE TITLE
[XGP 3.3] When making backups, it does not update the date and time of when it was made

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#515]
**Describe the bug**
When making backups, it does not update the date and time of when it was made
**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/2124810/232153083-e57b1f5f-c544-4db4-bf82-f4dc173c9961.png)

![image](https://user-images.githubusercontent.com/2124810/232153238-2b433937-6679-4e79-9d3f-748266b5f91b.png)
 
 **Server (please complete the following information):**
 - PHP Version: PHP 8.2
 - MySQL Version: MySQL 5.6

**Comment by FGServers** [comment]
Esto es un agregado mío interesante poder utilizar ahora Vendor y composer recién instale composer require nesbot/carbon
$next_run = Carbon::createFromTimestamp($task_time)->diffForHumans();
![image](https://user-images.githubusercontent.com/2124810/232154211-6cf284c8-483d-4c16-9f79-32c0fd193e35.png)

**Comment by LucasKovacs** [comment]
Well technically, is not a bug... you are confusing the automatic backup last timestamp with the manual backup. They don't relate... and the last run time will make sense once you it runs for the first time. I liked your proposal with Carbon, I will use it but for XGP4.
