### ISSUE TITLE
New Mailer can't handle german Umlauts in v3.3

### ISSUE THREAD

**Issue by manuelkamp** [XGProyect/XG-Proyect-v3.x.x#516]
**Describe the bug**
New Mailer in v3.3 can't handle german umlauts in mails.

**To Reproduce**
send an announcement via mail containing german umlaut, like äöü.

**Expected behavior**
Display correct encoding for german ulauts.

**Screenshots**
Admin UI:
<img width="832" alt="Screenshot 2023-04-15 084324" src="https://user-images.githubusercontent.com/48356947/232193045-cdd19948-ffb6-44b1-9b4e-ac415ae0d565.png">
Outlook (or any other mail client):
<img width="423" alt="Screenshot 2023-04-15 084546" src="https://user-images.githubusercontent.com/48356947/232193357-2c78edd9-24cb-4c64-834b-61e18c6e380b.png">

 
 **Server (please complete the following information):**
 - PHP Version: 8.2

**Additional context**
Also line breaks are missing

**Comment by LucasKovacs** [comment]
Thanks - fixed on 3.4
