### ISSUE TITLE
ADmin CP Action > Delete planet and moon

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#52]
Notice: Undefined index: glplanet_destroyed in /home/eskiog/public_html/beta/application/libraries/GalaxyLib.php on line 244

the moon and the planet has been deleted but remains on the panel.

![admcp](https://cloud.githubusercontent.com/assets/16218107/12863901/463c6ea2-cc86-11e5-8bca-2a3d7339b4fb.png)
![admcp2](https://cloud.githubusercontent.com/assets/16218107/12863907/61e2168e-cc86-11e5-9844-f287125ec587.png)

the planets and the moon came out indicating that a confirmation or denial letter deleted

**Comment by XGProyect** [comment]
Changes applied to reflect deleted moons and planets
