### ISSUE TITLE
[3.4] Install error in hosting CPANEL

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#521]
**Describe the bug**
Error install in hosting

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2124810/232246593-e47c03a6-3b82-463a-874e-0dd7dc3ee676.png)
 
 **Server (please complete the following information):**
 - PHP Version: 7.4
 - MySQL Version: 5.6

**Additional context**
Hosting CPANEL 

LOG FILE

E_WARNING|strpos(): Empty needle|Where called: line 55 of App\Http\Controllers\Install\InstallationController (in InstallationController.php)<br>Where called: line 327 of App\Http\Controllers\Install\InstallationController (in InstallationController.php)<br>Where called: line 351 of  (in InstallationController.php)<br>Where called: line  of App\Core\ErrorHandler (in )<br>Where called: line 39 of App\Libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 117 of App\Libraries\DebugLib (in DebugLib.php)

E_DEPRECATED|Directive 'allow_url_include' is deprecated|Where called: line  of  (in )<br>Where called: line  of  (in )<br>Where called: line  of App\Core\ErrorHandler (in )<br>Where called: line 49 of App\Core\ErrorHandler (in ErrorHandler.php)<br>Where called: line 39 of App\Libraries\DebugLib (in ErrorHandler.php)<br>Where called: line 117 of App\Libraries\DebugLib

**Comment by manuelkamp** [comment]
confirm, re-submitting this url in browser address line continues setup successfully

**Comment by FGServers** [comment]
Check your linux and php configuration in linux because I have it running xgp3.3 and 3.4 with w11 and wamp64 +php8.2 localhost and it installs me either by docker or composer

**Comment by manuelkamp** [comment]
What should I check, you reported this bug? I do not understand what your comment is about...

**Comment by LucasKovacs** [comment]
Check your setup

https://stackoverflow.com/questions/63532111/deprecated-directive-allow-url-include-is-deprecated-in-unknown-on-line-0

**Comment by FGServers** [comment]
Solucionado cambie de hosting y funciono perfecto
