### ISSUE TITLE
[3.4] Error on expeditions

### ISSUE THREAD

**Issue by manuelkamp** [XGProyect/XG-Proyect-v3.x.x#522]
php8.1, current 3.4 branch.

When setting up an expedition, this page results in an error: game.php?page=fleet3

`Uncaught TypeError: App\Libraries\FleetsLib::fleetMaxSpeed(): Argument #1 ($fleetArray) must be of type string, array given, called in /var/www/html/app/Http/Controllers/Game/Fleet3Controller.php on line 453 and defined in /var/www/html/app/Libraries/FleetsLib.php:51 Stack trace: #0 /var/www/html/app/Http/Controllers/Game/Fleet3Controller.php(453): App\Libraries\FleetsLib::fleetMaxSpeed() #1 /var/www/html/app/Http/Controllers/Game/Fleet3Controller.php(67): App\Http\Controllers\Game\Fleet3Controller->setInputsData() #2 /var/www/html/app/Http/Controllers/Game/Fleet3Controller.php(48): App\Http\Controllers\Game\Fleet3Controller->buildPage() #3 /var/www/html/public/game.php(48): App\Http\Controllers\Game\Fleet3Controller->index() #4 {main} thrown in /var/www/html/app/Libraries/FleetsLib.php on line 51`
`Error code: E_ERROR`

**Comment by LucasKovacs** [comment]
I think this issue was already fixed, double check on 3.4 and please let me know

**Comment by manuelkamp** [comment]
This error message is copied from the debug overlay from the current 3.4 branch, so it does not semm to be fixed.
It is not only with expeditions, but also if I send a fleet to another planet (for example to colonize it).

**Comment by LucasKovacs** [comment]
fixed on 3.4
