### ISSUE TITLE
Reset Uni #2

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#53]
Admin CP
Notice: Undefined index: id in /home/eskiog/public_html/beta/application/controllers/adm/reset.php on line 154

Notice: Undefined index: id in /home/eskiog/public_html/beta/application/controllers/adm/reset.php on line 155

Game

Notice: Undefined index: building_crystal_store in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 53

Notice: Undefined index: building_deuterium_tank in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 54

Notice: Undefined index: planet_temp_max in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 61

Notice: Undefined index: planet_energy_max in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 66

Notice: Undefined index: planet_energy_used in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 67

Notice: Undefined index: planet_building_metal_mine_porcent in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 78

Notice: Undefined index: building_metal_mine in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 79

Notice: Undefined index: planet_building_crystal_mine_porcent in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 78

Notice: Undefined index: building_crystal_mine in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 79

Notice: Undefined index: planet_building_deuterium_sintetizer_porcent in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 78

Notice: Undefined index: building_deuterium_sintetizer in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 79

Notice: Undefined index: planet_building_solar_plant_porcent in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 78

Notice: Undefined index: building_solar_plant in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 79

Notice: Undefined index: planet_building_fusion_reactor_porcent in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 78

Notice: Undefined index: building_fusion_reactor in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 79

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 114

Notice: Undefined index: planet_ship_solar_satellite_porcent in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 78

Notice: Undefined index: ship_solar_satellite in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 79

Notice: Undefined index: planet_type in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 125

Notice: Undefined index: planet_last_update in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 144

Notice: Undefined index: planet_metal in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 172

Notice: Undefined index: planet_metal in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 179

Notice: Undefined index: planet_crystal in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 190

Notice: Undefined index: planet_crystal in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 197

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 208

Notice: Undefined index: planet_deuterium in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 215

Notice: Undefined index: planet_b_hangar_id in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 337

Notice: Undefined index: planet_b_tech in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 276

Notice: Undefined index: planet_b_tech_id in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 276

Notice: Undefined index: planet_b_hangar_id in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 308

Notice: Undefined index: planet_id in /home/eskiog/public_html/beta7/application/libraries/UpdateResourcesLib.php on line 319

Notice: Undefined index: planet_b_building_id in /home/eskiog/public_html/beta7/application/libraries/UpdateLib.php on line 121

**Comment by XGProyect** [comment]
Fixed

**Comment by Reigen1991** [comment]
i have the same issue after i migrated from 2.10.9 to 3.0.0RC

**Comment by XGProyect** [comment]
After testing, I'm closing this issue again.
