### ISSUE TITLE
[v3.4] The loading screen does not appear

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#531]
http://localhost/xgp3.4/ The loading screen does not appear

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 112.0.1

 
 **Server (please complete the following information):**
 - PHP Version: PHP 8.2.4

![Screenshot_1](https://user-images.githubusercontent.com/16218107/233132417-4d5f9592-6ba7-46d9-b6fb-bc5f1269aab8.png)

**Comment by LucasKovacs** [comment]
you need to run `composer install` on the root of the project using the command line or terminal
