### ISSUE TITLE
[v3.4] Exchange resources

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#535]
**Describe the bug**
Exchange resources,  Call merchant button not working.

**To Reproduce**
1. Go to Resource Market
2. Select the raw resource and press the call merchant button.
3. It does not go to the next page and no error occurs.

**Screenshots**
![resim](https://user-images.githubusercontent.com/16218107/234351980-4a6f3655-3688-4679-9786-eca587346daf.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Firefox 112.0.1

 
 **Server (please complete the following information):**
 - PHP Version: 8.2.4

**Comment by LucasKovacs** [comment]
Feature is not ready.
