### ISSUE TITLE
Moon Edit

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#54]
Month I get this error trying to add building

Fatal error: Call to undefined method application\controllers\adm\Users::save_buildings() in /home/eskiog/public_html/beta7/application/controllers/adm/users.php on line 274

Warning: Invalid callback application\core\Sessions::write, cannot access private method application\core\Sessions::write() in Unknown on line 0

Warning: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

Warning: Invalid callback application\core\Sessions::close, cannot access private method application\core\Sessions::close() in Unknown on line 0

We delete moon. deletion successful or unsuccessful he did not post.
but stands out as a mistake when we added the following moon again.
Planet Moon coming months, the official goes official in the admin control panel after deleted. After going there again entered the planet and the moon.

Warning! Unable to create moon.
Probable errors:
-Moon already exists on that planet.
-You're traying to add a moon to another moon.
-The selected planet is destroyed.

**Comment by XGProyect** [comment]
- Fixed
- Notice that the second error is because the moon and planet deletion is a "logical" delete, they will be physically deleted after a period of time.
