### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by agentcobra** [XGProyect/XG-Proyect-v3.x.x#543]
# How to install
1. run command in directory `Git clone https://github.com/XGProyect/XG-Proyect-v3.x.x.git`
2. run command `docker compose up`
Error in navigator : http://localhost/
```php
Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/app/Core/Common.php on line 19

Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/app/Core/Common.php on line 19
```
3. run command `docker compose down`
4. run command `composer install`
5. run command `docker compose up`
in navigator : http://localhost/install/index.php?page=installation&mode=step1 fields are empty
fill fields with : 
 - host=db
 - user=root
 - password=root
 - db=xgp
 - prefix=xgp_
6. submit

that's the easy install!

**Comment by LucasKovacs** [comment]
That's a different way, the preferred one would be doing 
```
composer create-project xgproyect/xgproyect
```

And then running docket.

**Comment by agentcobra** [comment]
maybe need to update readme file https://github.com/XGProyect/XG-Proyect-v3.x.x#docker

**Comment by fr0st87** [comment]
Hi, cuando intento: 

> run command docker compose up

Me da error. 

> docker: 'compose' is not a docker command.

Pudieran explicar cual es mi error......... soy nuevo trabajando con docker.

**Comment by agentcobra** [comment]
> Hi, cuando intento: 
> 
> > run command docker compose up
> 
> Me da error. 
> 
> > docker: 'compose' is not a docker command.
> 
> Pudieran explicar cual es mi error......... soy nuevo trabajando con docker.
> 
> 

Hi,
Is docker installed on your system?

**Comment by fr0st87** [comment]
> > Hi, cuando intento:
> > > run command docker compose up
> > 
> > 
> > Me da error.
> > > docker: 'compose' is not a docker command.
> > 
> > 
> > Pudieran explicar cual es mi error......... soy nuevo trabajando con docker.
> 
> Hi, Is docker installed on your system?

SI lo tengo instalado
![Screenshot_20230810_165158](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/80664141/5dc79af0-0d5a-47ef-8806-f336422af35c)

**Comment by fr0st87** [comment]
> > > Hi, cuando intento:
> > > > run command docker compose up
> > > 
> > > 
> > > Me da error.
> > > > docker: 'compose' is not a docker command.
> > > 
> > > 
> > > Pudieran explicar cual es mi error......... soy nuevo trabajando con docker.
> > 
> > 
> > Hi, Is docker installed on your system?
> 
> SI lo tengo instalado ![Screenshot_20230810_165158](https://user-images.githubusercontent.com/80664141/259872080-5dc79af0-0d5a-47ef-8806-f336422af35c.jpeg)


A ver, estuve buscando y es que soy de Cuba y Docker esta bloqueado para mi país.

Alguna otra forma de poder instalar esta versión.

**Comment by mystikxkemix** [comment]
Hi!
I'm trying to install the project on a VM using docker.
On the VM, I installed PHP 7.4, Composer, and docker.

I ran `composer create-project xgproyect/xgproyect` that created me the folder `xgproyect` with the dependencies downloaded.
Then I ran `docker compose up` to run the containers. No error for now. PhpMyAdmin and Mailhog are running correctly.


Then when I try to go to `http://192.168.2.213/install/index.php?page=installation&mode=step1` to start the installation, but I got the error 500.

![Capture d’écran 2023-08-30 à 13 45 48](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/9988890/fd6ae39a-49f6-4448-9eea-e216c3b289ab)

Do you know what can lead to this? 

Edit: it seems that it works locally but not from another computer on the network. Do you know how I can open the access?
