### ISSUE TITLE
Protection and Attack

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#55]
Protection feature will activate the control panel of the Board. Players can not fight among themselves. ( Note: not the manager. They are regular players )

![attack fleet4](https://cloud.githubusercontent.com/assets/16218107/12980112/a2a86158-d0e3-11e5-8581-26541b3bab0f.png)

closed the Protection of property, any problem does not occur for war.

**Comment by XGProyect** [comment]
Fixed
