### ISSUE TITLE
Black holes in Expeditions 

### ISSUE THREAD

**Issue by Raptor2971** [XGProyect/XG-Proyect-v3.x.x#554]
hello everyone and sorry for my english.
I'm playing the latest version, 3.4 and like the previous ones there are big problems in the expeditions, it's impossible to do them, the probability of black holes is too high, the average is very high, is there someone who can solve this thing or is it impossible?
In addition playing with the officers the admiral does not automatically give the + 1 expedition , another bug ....
Thank you

**Comment by LucasKovacs** [comment]
Hello, we will be looking at those issues.

**Comment by LucasKovacs** [comment]
Related to https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/426

**Comment by Raptor2971** [comment]
I have done a lot of expeditions but the probability of losing the fleet or part of the fleet is always too high, 1 in every 4 done...something needs to be reviewed...
