### ISSUE TITLE
Resource Market issue

### ISSUE THREAD

**Issue by Raptor2971** [XGProyect/XG-Proyect-v3.x.x#557]
![bug](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/129175671/64bf9808-b5ca-4978-99a3-c68330a4b988)

Good morning everyone,
another bug found...the "call merchant" function is not working, you can't exchange resources in the "resource market".

**Comment by jonamix-ar** [comment]
yes not working, its bug confirmed

**Comment by LucasKovacs** [comment]
Not a bug. I had no time to wrap up the feature

**Comment by Raptor2971** [comment]
> Not a bug. I had no time to wrap up the feature


I can understand that you don't have time but this is a bug!! the feature doesn't work! then take it off!
