### ISSUE TITLE
Battle report error

### ISSUE THREAD

**Issue by minideveloper1778** [XGProyect/XG-Proyect-v3.x.x#559]
Hello!

![error](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/122751334/80c437c7-8887-4b2c-9165-6b3af1c139e7)

OS: ubuntu-22.04.1-desktop-amd64
GAME in docker-compose (default)

How to fix?

**Comment by LucasKovacs** [comment]
Still looking for a solution ... I want this fixed before releasing 3.5

**Comment by OceanicNomad** [comment]
#569 This is the fix @LucasKovacs @minideveloper1778
