### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#56]
In the building stage, as shown in the first image is being upgraded. And inserted into the research unit is no problem.
![pic1](https://cloud.githubusercontent.com/assets/16218107/12980460/2ef29434-d0e5-11e5-84c8-7dd8351c6e36.png)

As shown in the second image. It was added to construct a unit list. These errors came logs in the research department
![pic2](https://cloud.githubusercontent.com/assets/16218107/12980553/9b2e45b2-d0e5-11e5-9791-82477f076cd5.png)

Notice: Undefined offset: 3 in /home/eskiog/public_html/beta/application/controllers/game/research.php on line 286
Notice: Undefined offset: 4 in /home/eskiog/public_html/beta/application/controllers/game/research.php on line 286
Notice: Undefined offset: 2 in /home/eskiog/public_html/beta/application/controllers/game/research.php on line 286
Notice: Undefined offset: 3 in /home/eskiog/public_html/beta/application/controllers/game/research.php on line 286
Notice: Undefined offset: 4 in /home/eskiog/public_html/beta/application/controllers/game/research.php on line 286

**Comment by XGProyect** [comment]
Fixed
