### ISSUE TITLE
Bug in research

### ISSUE THREAD

**Issue by minideveloper1778** [XGProyect/XG-Proyect-v3.x.x#560]
Hello!

ran into a research problem.
If there is a research laboratory in the construction queue, the research cannot be completed.

screenshots:
![queue](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/122751334/ebb1c8d8-8bc1-478d-b8b0-65190508b911)
![research](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/122751334/af7df9da-f4ce-4a7a-bfb1-a4ebb04cb9c7)

**Comment by LucasKovacs** [comment]
So the alert needs to be removed? Functionality is ok?

**Comment by jonamix-ar** [comment]
RTA: 1 - The blocking function works well as it should, so you can't build the lab when researching.
RTA: 2 - The message is deleted only appears in the inputs, what we can do is block the input build and leave a message is being investigated in the style of domes.

THIS ITS BUILDING LAB 
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/2dbf78d4-feb8-4ebd-85bc-b7144dc1be9f)

Research tooltip
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/868d2973-b642-4462-af12-4cc80b61f83f)

Research input
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/7e2305fe-fbe8-4c6d-8e0c-242ed8d8213b)

Building lab in colony
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/a6b792c1-2bec-4671-a022-37a0e44a95bd)



THIS IT'S REVERSE
IMG
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/e0d36e76-009a-4bfc-b210-84a338ea34ed)

Labs blocked its reserching
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/a5ad18cd-602c-46d6-969b-74407bf19696)

Lab info
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/88a21c5a-aa8c-44a4-981e-9d967b593fc1)

Research labs in other planet whit intergalactic network
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/95a3de01-fcd7-4958-b4c6-efe41339fbfd)

**Comment by jonamix-ar** [comment]
Lo que si encontre en la 3.5
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/cd1c9445-2145-4906-ba51-8ca5ff1bc351)

Deberia estar bloqueado.
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/72f34630-2197-41ae-9ff2-d471dddfd5dd)

Encontre el bug

```
private function isLaboratoryInQueue()
    {
        $return = true;
        $current_building = '';
        $element_id = 0;

        if ($this->planet['planet_b_building_id'] != 0) {
            $current_queue = $this->planet['planet_b_building_id'];

            if (strpos($current_queue, ';')) {
                $queue = explode(';', $current_queue);

                for ($i = 0; $i < MAX_BUILDING_QUEUE_SIZE; $i++) {
                    if (isset($queue[$i])) {
                        $element_data = explode(',', $queue[$i]);
                        $element_id = $element_data[0];

                        if ($element_id == 31) {
                            break;
                        }
                    }
                }
            } else {
                $current_building = $current_queue;
            }

            if ($current_building == 31 or $element_id == 31) {
                $return = false;
            }
        }

       
        return $return;
    }
```
$queue = explode(';', $current_queue); ---> el explode tiene un ; y en la db esta con, "31,4,314.18181818182,1687124721.1818,build"

Lo que no entiendo por que cuando insertas la Construccion a la db la coloca con coma y los explode tan todos con ;

@LucasKovacs

**Comment by LucasKovacs** [comment]
Puede ser un bug. En un momento hice una revisión, y puede ser que me haya faltado cambiar algo. La verdad es que eso necesita volverse a hacer usando la clase Queue

**Comment by LucasKovacs** [comment]
Mirando de nuevo. El `;` separa cada ítem, y la `,` separa los detalles de cada ítem.

**Comment by LucasKovacs** [comment]
I sent a fix that correctly checks the queue. Can you check if that's enough? Or do we need other fix for it?

**Comment by jonamix-ar** [comment]
> I sent a fix that correctly checks the queue. Can you check if that's enough? Or do we need other fix for it?

Working perfect again reseach blocked whit lab  upgrading.

**Comment by LucasKovacs** [comment]
Closed as fixed. XGP 3.5
