### ISSUE TITLE
Server not buildable/runnable

### ISSUE THREAD

**Issue by Speiger** [XGProyect/XG-Proyect-v3.x.x#563]
o/
I have been trying with a friend to compile/run the server.
After working out a bunch of kinks, like:
- Requiring a php requirement that wasn't listed.
- Trying to figure out what command actually is needed
- And configuring troubleshooting in general.

We simply gave up because we realized this project is a mess.

We basically ran into these 3 issues:
#511 #543 #561
And even after following all the potential fixes it just did not work.

In the end we got a HTTP answer 500 and gave up because it was already the 2 hour mark.

What this project kinda needs are VERY CLEAR install instructions.
Or maybe a script that you just run and it tries to run all the steps required at once.
That also includes dependency checks like:
- Is PHP installed.
- Are all PHP plugins that I use present
- Is Docker installed
- Can I actually run this? (Like check system specs)
- Do i have all system file permissions?

After that a "What is required afterwards?"
Stuff like gitea/archivia show you exact install instructions of what to do after the install is completed. This here does nothing of sorts.

I personally like OGame a lot, I just hate the Massive Competitiveness of it and would love to play just with a small community instead for a few months.

And thought maybe this project would work.

Nope sadly not possible.

Sorry for this rant but all "releases" should be maybe marked as "beta" or "unstable" so people know they might not get them running.

I know you do these things for free on your own time and what i am telling here is really mean in that sense that you owe me nothing.
On the other hand i am pretty sure you would like people to use your software.

So please keep that in mind.

Anyways I hope you can get that sorted out at some point where a "install" script is just included with it.
Overall i do assume you have done a ton to get this already running so Major Props from my side.
I am not a Web dev but i know how hard this can be and i think you did a great job so far.
Even if there is still a few bugs to kink out.

Anyways I am out.
There is no logs or anything left since i deleted all traces of this project from my server.

This is just feedback

**Comment by agentcobra** [comment]
Hi,
See #543

**Comment by Speiger** [comment]
> Hi,
> See #543

Hi.
I listed the exact issue you are referencing as "issues we have encountered and it didn't help"

**Comment by agentcobra** [comment]
> > Hi,
> > See #543
> 
> Hi.
> I listed the exact issue you are referencing as "issues we have encountered and it didn't help"

Is it better with my installation guide?

**Comment by Speiger** [comment]
We tried everything and all we get at the end is a HTTP 500 answer from the server (or a white screen from Firefox).

So no. There isn't a "working" Installation guide.

Tip:
Maybe provide a installation script that guides the user instead of what you have right now.

**Comment by Speiger** [comment]
@agentcobra sry i missread your answer, in the way that i thought you were the developer.
Basically no.
Effectively we tried your solution and it didn't work.

Is your solution simpler even if it is not working?
Yes.

But again neither solution/steps to install do not work.

**Comment by agentcobra** [comment]
> @agentcobra sry i missread your answer, in the way that i thought you were the developer.
> Basically no.
> Effectively we tried your solution and it didn't work.
> 
> Is your solution simpler even if it is not working?
> Yes.
> 
> But again neither solution/steps to install do not work.

Ok, no problem. 
Have you got some error logs ?

**Comment by Speiger** [comment]
@agentcobra nope.
I basically applied rm -rf on the folder/images/docker itself
I am not the biggest user of docker, but the friend who joined me knew enough to make things work.
And we both basically said: Way to much work and not worth spending days over it to get it running.

Honestly I would suggest someone makes a install script and let them test it on a machine that JUST has docker installed, nothing else.
And look how well that works.

The install script should either download the required dependencies instantly or give you feedback what is required to run it.
Or both.

**Comment by Speiger** [comment]
@LucasKovacs so the project is dead and was never ment to be started outside of your development tools?

**Comment by LucasKovacs** [comment]
Th project is not dead. I need help actually, so any contribution is welcome!

I closed this issue, because it looked solved.
