### ISSUE TITLE
Shipyard

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#57]
When this error occurs, the error is very similar research. It is almost the  https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/56
Step 1 is pressed, this error is when you go back to the shipyard.

![shipyard](https://cloud.githubusercontent.com/assets/16218107/12985326/a355babc-d0fa-11e5-95a4-e7a1fd4b0057.png)

![shipyard1](https://cloud.githubusercontent.com/assets/16218107/12985327/a6f7c11a-d0fa-11e5-9599-ef3448159793.png)

**Comment by XGProyect** [comment]
Fixed
