### ISSUE TITLE
Combat not working PHP 8 fix

### ISSUE THREAD

**Issue by OceanicNomad** [XGProyect/XG-Proyect-v3.x.x#570]
Instead of dynamically creating the `fighters` property as in previous versions of PHP, we need to explicitly declare it at the beginning of the class.

https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/d1d9dc7ed498c4417f41b955871d4b67e0bb39d7/app/Libraries/BattleEngine/CombatObject/PhysicShot.php#L62

Add `private $fighters;` below
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/d1d9dc7ed498c4417f41b955871d4b67e0bb39d7/app/Libraries/BattleEngine/CombatObject/PhysicShot.php#L42

**Comment by jonamix-ar** [comment]
[FIX] https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/595
