### ISSUE TITLE
Error installing using WAMP on Windows

### ISSUE THREAD

**Issue by OceanicNomad** [XGProyect/XG-Proyect-v3.x.x#571]
When trying to install on Windows using WAMP or similar, the following needs to be removed.

https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/d1d9dc7ed498c4417f41b955871d4b67e0bb39d7/app/Http/Controllers/Install/InstallationController.php#L440-L442
https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/d1d9dc7ed498c4417f41b955871d4b67e0bb39d7/app/Http/Controllers/Install/InstallationController.php#L456-L458

**Comment by jonamix-ar** [comment]
Version PHP Wamp?

**Comment by OceanicNomad** [comment]
This is a fix for any PHP version, it just removes the script checking for Windows environment and attempting to use Windows SQL Server rather than MySQL.

If you must know, it was tested on PHP 8.2 and MySQL 8
