### ISSUE TITLE
Error code: E_DEPRECATED

### ISSUE THREAD

**Issue by fr0st87** [XGProyect/XG-Proyect-v3.x.x#575]
**Describe the bug**
En ocasiones cada vez que cargo una pagina me sale en la parte inferior de la pagina una barra en azul  (ver Captura mas abajo)

**To Reproduce**
No se lo que lo reproduce, solo que cuando estoy navegando dentro del juego sale.

**Screenshots**
![Screenshot_20230910_150725](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/80664141/d43606f6-4c0b-4dea-9a01-ae06217f49ca)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox
 - Version: 117 (64 bits)

 
 **Server (please complete the following information):**
 - PHP Version: 7.4.23
 - MySQL Version:  MariaDB 10.4.21

**Additional context**
Me pudieran decir si es un error o porque sale ese ERROR.

NOTA: Perdonen que escriba en Español, pero mi Ingles no pasa de la media

**Comment by jonamix-ar** [comment]
Podes probar con php 8.2 aver su te tura el error, lo prove en la 7.4 + Mysql 8 y no lo puedo replicar

hace esto mejor, entra al php.ini busca track_errors=On y cambialo por track_errors=Off

No hay drama yo también hablo español podes en los dos idiomas

**Comment by fr0st87** [comment]
> hace esto mejor, entra al php.ini busca track_errors=On y cambialo por track_errors=Off

Hice esto, y hasta ahora no me ha salido mas.

**Comment by fr0st87** [comment]
> hace esto mejor, entra al php.ini busca track_errors=On y cambialo por track_errors=Off

Hice esto y hasta ahora no me ha salido mas el cartel del error.

Cierro Issue
