### ISSUE TITLE
Error instalacion, Mysql 8.x

### ISSUE THREAD

**Issue by jonamix-ar** [XGProyect/XG-Proyect-v3.x.x#577]
**Describe the bug**
Uncaught mysqli_sql_exception: Variable 'sql_mode' can't be set to the value of 'MYSQL40' in C:\laragon\www\XG-Proyect-v3.5.1\app\Core\Database.php:138 Stack trace: #0 C:\laragon\www\XG-Proyect-v3.5.1\app\Core\Database.php(138): mysqli->query('set @@global.sq...') #1 C:\laragon\www\XG-Proyect-v3.5.1\app\Models\Install\Installation.php(74): App\Core\Database->query('set @@global.sq...') #2 C:\laragon\www\XG-Proyect-v3.5.1\app\Http\Controllers\Install\InstallationController.php(442): App\Models\Install\Installation->setWindowsSqlMode() #3 C:\laragon\www\XG-Proyect-v3.5.1\app\Http\Controllers\Install\InstallationController.php(136): App\Http\Controllers\Install\InstallationController->insertDbData() #4 C:\laragon\www\XG-Proyect-v3.5.1\app\Http\Controllers\Install\InstallationController.php(35): App\Http\Controllers\Install\InstallationController->buildPage() #5 C:\laragon\www\XG-Proyect-v3.5.1\public\install\index.php(21): App\Http\Controllers\Install\InstallationController->index() #6 {main} thrown
in C:\laragon\www\XG-Proyect-v3.5.1\app\Core\Database.php on line 138

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/fa8ffaa8-1a3a-4e7e-8158-fd7172d6c4f8)

**Desktop (please complete the following information):**
 - OS: W11
 - Browser chrome
 - Version Last
 
 **Server (please complete the following information):**
 - PHP Version: PHP 8.2.10
 - MySQL Version: MySQL 8.0

**Comment by fr0st87** [comment]
Perdona que pregunte por acá, pero donde fue que conseguiste la versión 3.5.1?

**Comment by jonamix-ar** [comment]
Es la 3.5.0 yo le pongo cuando voy armando un fix. es codigo interno mio

**Comment by LucasKovacs** [comment]
fixed on 14cce0533c6873c52dc1fafda5444cd7d6c0def0
