### ISSUE TITLE
Missing battle report and debris

### ISSUE THREAD

**Issue by MrCalhoun** [XGProyect/XG-Proyect-v3.x.x#579]
**Describe the bug**
An planet were attacked, that only got some (low) defense (no fleet) and a bunch of satellite (~4000)
No debris and battlereport (for both players) was generated. Attacker and attacked are both in the same alliance.
Goal was to get a moon.

**To Reproduce**
1. Build on a planet an bunch of satellite without any other ships
2. Attack that planet
3. See error

**Expected behavior**
Debris and battlereport should generated

**Screenshots**
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/671185/f20fc08b-134d-42e3-9721-e84c542073ad)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version latest
 
 **Server (please complete the following information):**
 - PHP Version: Looking atm for that an will update that information
 - MySQL Version: Looking atm for that an will update that information

**Comment by jonamix-ar** [comment]
[FIX] https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/595
