### ISSUE TITLE
Jump Gate

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#58]
/home/eskiog/public_html/area51/application/controllers/game/infos.php on line 299
Notice: Undefined index: building_jump_gate in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 431
Notice: Undefined index: building_jump_gate in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 299
Notice: Undefined index: building_jump_gate in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 431
Notice: Undefined offset: 200 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 201 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 216 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 217 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 218 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 219 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 220 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 221 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 222 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 223 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 224 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 225 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 226 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 227 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 228 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 229 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 230 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 231 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 232 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 233 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 234 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 235 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 236 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 237 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 238 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 239 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 240 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 241 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 242 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 243 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 244 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 245 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 246 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 247 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 248 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405
Notice: Undefined offset: 249 in /home/eskiog/public_html/area51/application/controllers/game/infos.php on line 405

![jump](https://cloud.githubusercontent.com/assets/16218107/12990045/c40856e6-d110-11e5-8004-663b7ad2c83e.png)

**Comment by XGProyect** [comment]
Fixed
