### ISSUE TITLE
EXPEDITIONS AND MERCHANT

### ISSUE THREAD

**Issue by Raptor2971** [XGProyect/XG-Proyect-v3.x.x#580]
expeditions still have too high a probability of encountering black holes or being partially destroyed and without a merchant it is not possible to play completely, either you resolve these things or otherwise I don't think you can play dynamically and completely.

**Comment by jonamix-ar** [comment]
The project is stopped for now, it is not a stable core for now to be put into production, the Merchant I am trying to develop it now, in a couple of days I will try to upload a PR

**Comment by LucasKovacs** [comment]
version 3.5 has a refactor on expeditions, you can try that version @Raptor2971
