### ISSUE TITLE
Error when acessing webserver

### ISSUE THREAD

**Issue by YaibaToKen** [XGProyect/XG-Proyect-v3.x.x#581]
**Describe the bug**

**To Reproduce**
1. Clone the repo
2. Do docker-compose-up
3. Navigate to http://localhost

**Expected behavior**
Anything other than an error page tbh

**Screenshots**
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/9133736/a242fccf-4f85-4fdd-85a8-01cb78cb71d2)

**Additional context**
The container logs show nothing out of the ordinary. The problem happens both when using a linux server as well as using a windows machine with docker for desktop.

**Comment by jonamix-ar** [comment]
Run in terminal ``Composer update``

**Comment by agentcobra** [comment]
See #543

**Comment by agentcobra** [comment]
See #543

**Comment by YaibaToKen** [comment]
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/9133736/7f98c461-2c8a-4c0f-b39d-be12a1c760e5)
I'm now greeted with this error page

**Comment by jonamix-ar** [comment]
Log File put here

**Comment by YaibaToKen** [comment]
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/9133736/8e7f23ba-0e38-4f78-a48b-4b6c7bf93692)
This is all I have for the container log.
