### ISSUE TITLE
Admin CP - Create Planet

### ISSUE THREAD

**Issue by YaibaToKen** [XGProyect/XG-Proyect-v3.x.x#582]
Is there a guide somewhere with info on what constitutes valid data when creating a planet through the admin control panel?
No matter what data I insert, I always get the same error.

**Comment by jonamix-ar** [comment]
What mistake do you make?

**Comment by YaibaToKen** [comment]
For example:
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/9133736/cebfa043-7919-4876-b384-2b06dc5404ed)
Regardless of what I put in though, I always get this error:
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/9133736/fa079f7e-5287-43e3-8b20-fc4714eee6b2)


Note that the only existing planet is on 1:1:1

**Comment by jonamix-ar** [comment]
If you place the numbers in the coordinates, they are placeholders.

![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/ded8708f-0c3e-4b34-8b97-3c0c8cc81f58)
Its a bug the input number

**Comment by YaibaToKen** [comment]
That worked, thanks
