### ISSUE TITLE
About Style

### ISSUE THREAD

**Issue by jbezza123** [XGProyect/XG-Proyect-v3.x.x#585]
So I've been changing the ui yet one thing eludes me, "#content" in which im unable to change top; 91px; to 110px;, I'm not sure what is changing it when the page loads, any suggestions?

Así que he estado cambiando la interfaz de usuario pero una cosa se me escapa, "#content" en la que no puedo cambiar la parte superior; 91 píxeles; a 110px; no estoy seguro de qué lo cambia cuando se carga la página, ¿alguna sugerencia?

**Comment by jonamix-ar** [comment]
En el footer esta el codigo que maneja el tamaño del top.

``` 
headerHeight = 81;
errorbox.style.top = parseInt(headerHeight + messagebox.offsetHeight + 5) + 'px';
contentbox.style.top = parseInt(headerHeight + errorbox.offsetHeight + messagebox.offsetHeight + 10) + 'px';
if (navigator.appName == 'Netscape') {
    if (window.innerWidth < 1020) {
        document.body.scroll = 'no';
    }
    contentbox.style.height = parseInt(window.innerHeight) - messagebox.offsetHeight - errorbox.offsetHeight - headerHeight - 20;
    if (document.getElementById('resources')) {
        document.getElementById('resources').style.width = (window.innerWidth * 0.4);
    }
} else {
    if (document.body.offsetWidth < 1020) {
        document.body.scroll = 'no';
    }
    contentbox.style.height = parseInt(document.body.offsetHeight) - messagebox.offsetHeight - headerHeight - errorbox.offsetHeight - 20;
    document.getElementById('resources').style.width = (document.body.offsetWidth * 0.4);
}
for (var i = 0; i < document.links.length; ++i) {
    if (document.links[i].href.search(/.*redir\.php\?url=.*/) != -1) {
        document.links[i].target = "_blank";
    }
}
```

si lo borras podras meterle asi 

#content {
	position:absolute;
	left:190px;
	scrollbars:none;
	overflow:auto;
	width:80%;
	height:100%;
	margin-top: 110px;
}

**Comment by jbezza123** [comment]
Gracias, amigo. Estaba perdiendo la cabeza tratando de encontrar qué lo estaba cambiando

**Comment by BeReal86** [comment]
> Gracias, amigo. Estaba perdiendo la cabeza tratando de encontrar qué lo estaba cambiando

I'm closing it because your question has been answered. Do not hesitate to contact us with any problems.
