### ISSUE TITLE
Responsive, for Phone 

### ISSUE THREAD

**Issue by Jeawyn** [XGProyect/XG-Proyect-v3.x.x#587]
Hi !

Does anyone have a solution to make the site responsive on the phone?

**Comment by Jeawyn** [comment]
And it's possible to create new Univers please ?

**Comment by jonamix-ar** [comment]
We are waiting for Lucas to publish 4.0

**Comment by Jeawyn** [comment]
Oh nice, the 4.0 is fully responsive ? 
do you know whenthe 4.0 is disponible ?

**Comment by BeReal86** [comment]
> Oh nice, the 4.0 is fully responsive ? do you know whenthe 4.0 is disponible ?

Hello,
There is no final date for the v4.0 version. When the date information is updated, we will publish it here. Thanks.

**Comment by Denizuga** [comment]
Merhaba 3.4 sürümünü kullanıyorum fakat Tüccarı çalıştıramıyorum daha 3.4den daha güncel bir sürüm var mı, Ufuk bey size ulaşmaya çalıştım fakat başaramadım :( neler ekleyebileceğimi öğrenmek istiyorum.

**Comment by BeReal86** [comment]
Merhaba @Denizuga 
3.4 sürümünden daha güncel bir sürüm yok. Tüccar bazı bölümleri tam değildir.

**Comment by Denizuga** [comment]
Bir çok site var bonus, maden toplama, filo toplama gibi değişik eklentiler var bunlara nasıl ulaşabilirim bilgilerinizden faydalanmak isterim denizuga@gmail.com
