### ISSUE TITLE
Crash after battle when debris is generated 

### ISSUE THREAD

**Issue by TheChaser5** [XGProyect/XG-Proyect-v3.x.x#592]
**Describe the bug**
When you attack a planet and the battle would generate debris 
No battle is generated 
No debris is generated 
The ships have been processed so has defense. As the numbers where lower then original 

**To Reproduce**
Attack a planet with a fleet that generates debris 

**Expected behavior**
A battle report and debris 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: all os
 - Browser all browsers 
 - Version 3.4.0

**Smartphone (please complete the following information):**
 - Device: all os
 - OS: all os
 - Browser all browsers 
 - Version 3.4.0
 
 **Server (please complete the following information):**
 - PHP Version: will look up
 - MySQL Version: will look up

**Additional context**
Where called: line 268 of App\Libraries\BattleEngine\Core\BattleReport (in Attack.php)
Where called: line 292 of App\Libraries\BattleEngine\Core\BattleReport (in BattleReport.php)
Where called: line 259 of (in BattleReport.php)
Where called: line of App\Core\ErrorHandler (in )
Where called: line 39 of App\Libraries\DebugLib (in ErrorHandler.php)
Where called: line 116 of App\Libraries\DebugLib (in DebugLib.php)

**Comment by Tsamsiyu1** [comment]
i have the same error.

**Comment by jonamix-ar** [comment]
[FIX] https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/595
