### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Luciano1141** [XGProyect/XG-Proyect-v3.x.x#597]
**Describe the bug**
I got an error 500 after trying to start the configuration
http://xx.xx.xx.xx/public/install/

**To Reproduce**
1. VPS installed with Debian, PHP 7.4, composer and docker
2. git clone https://github.com/XGProyect/XG-Proyect-v3.x.x.git
3. docker-compose build --build-arg PHP_VERSION=7.4 && docker-compose up -d
4. going to http://xx.xx.xx.xx/public/install/
5. Got the error 500 - even if I checked the phpmyadmin, DB, everything seems OK

**Expected behavior**
Something else than this error. 

**Screenshots**
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/167027842/d88edd89-20d7-4cae-9bfa-2a7b6a4200f1)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser Chrome
 - Version 123.0.6312.107 (Build officiel) (64 bits)

 
 **Server (please complete the following information):**
 - PHP Version: 7.4
 - Server version: 10.11.6-MariaDB-0+deb12u1 Debian 12

**Additional context**
If someone can help me ? I am ready to retribute if someone wants to take time and help me to install this server. Thanks a lot.

**Comment by jonamix-ar** [comment]
Active debug in Constant.php and update PHP VErsion to 8.1

**Comment by Luciano1141** [comment]
Thanks a lot for your help Jonamix-ar.

Even if I delete the docker, updating the php to 8.1 and recreate the docker, now I don't have any error but the server seems to not be reachable. 

Any chance to get in touch directly with you ? As I said, it would be a pleasure and it's normal to retribute you for your help. 

I will update this post to help the community if they have got the same problem.

**Comment by jonamix-ar** [comment]
Two question you run "composer update" and in config/constant.php put "true" in DEBUG_MODE = false

**Comment by Luciano1141** [comment]
Thanks a lot Jonamix ! 
Actually I did resolve my problem by upgrading to 5.3 instead of 5.2
I was able to do the configuration without any trouble then :)
