### ISSUE TITLE
Permission Denied - Every player actions

### ISSUE THREAD

**Issue by Luciano1141** [XGProyect/XG-Proyect-v3.x.x#598]
**Describe the bug**
The installation of the server went well, without any issues. Unfortunately, when I try to create an account from the "normal" portal, I got an error even if the account is well created (I can see it on the admin panel)
Even so, when I try to connect with this fresh new user, I got a lot of error about permission.

**To Reproduce**
1. Create an account or login with an existing account

**Expected behavior**
To be able to create an account and got the email confirmation
To be able to login

**Screenshots**
Creation : 

![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/167027842/42e938a8-8a07-46eb-875a-1289ea5b4d4c)

Login : 

![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/167027842/785aab7c-4f2d-4a54-9a8c-9a7b0d7ab5e6)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - 64b
 - Browser : Chrome
 - Version : Version 123.0.6312.123 (Build officiel) (64 bits)

 
 **Server (please complete the following information):**
PHP Version: 8.3
Server version: 10.11.6-MariaDB-0+deb12u1 Debian 12

**Comment by Pin-Lui** [comment]
It is probably not the right way to fix it, but I got it to work after chmod 755 the compiles folder in public
