### ISSUE TITLE
Admin CP Operator

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#60]
Notice: Undefined index: lm_overview in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 430

Notice: Undefined index: lm_empire in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 431

Notice: Undefined index: lm_resources in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 432

Notice: Undefined index: lm_resources_settings in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 433

Notice: Undefined index: lm_station in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 434

Notice: Undefined index: lm_trader in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 435

Notice: Undefined index: lm_research in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 436

Notice: Undefined index: lm_shipyard in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 437

Notice: Undefined index: lm_fleet in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 438

Notice: Undefined index: lm_movement in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 439

Notice: Undefined index: lm_technology in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 440

Notice: Undefined index: lm_galaxy in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 441

Notice: Undefined index: lm_defenses in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 442

Notice: Undefined index: lm_alliance in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 443

Notice: Undefined index: lm_forums in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 444

Notice: Undefined index: lm_officiers in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 445

Notice: Undefined index: lm_statistics in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 446

Notice: Undefined index: lm_search in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 447

Notice: Undefined index: lm_messages in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 448

Notice: Undefined index: lm_notes in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 449

Notice: Undefined index: lm_buddylist in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 450

Notice: Undefined index: lm_options in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 451

Notice: Undefined index: lm_banned in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 452

Notice: Undefined index: lm_logout in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 453

Notice: Undefined index: lm_administration in /home/eskiog/public_html/area51/application/libraries/TemplateLib.php on line 530

![op](https://cloud.githubusercontent.com/assets/16218107/13063459/0364915e-d451-11e5-826b-7f53aaf18fd8.jpg)

**Comment by XGProyect** [comment]
Already fixed
