### ISSUE TITLE
Changing port for db connection

### ISSUE THREAD

**Issue by Spartancake** [XGProyect/XG-Proyect-v3.x.x#602]
Hi, I've been trying to install the container and everything works fine, but at the installation part there's not an option for the port for the connection for the db, since I'm using my own db on a different port and not in a container instead of the one in the compose file (which I've removed from the file), I would like to ask what do I need to add to change the port for the connection to the db.

Thanks in advance

**Comment by Legalistas** [comment]
in App\Core\Database.php change tryConnection

```
public function tryConnection(string $host = '', string $user = '', string $pass = null, int $port = 3306): bool
{
    try {
        if (empty($host) or empty($user)) {
            return false;
        }

        $this->connection = new mysqli($host, $user, $pass, '', $port);

        if ($this->connection->connect_error) {
            return false;
        }

        // force utf8 to avoid weird characters
        $this->connection->set_charset('utf8');

        return true;
    } catch (Exception $e) {
        return false;
    }
}
```
