### ISSUE TITLE
[Consulta] Recursos en tiempo real

### ISSUE THREAD

**Issue by ShacresX** [XGProyect/XG-Proyect-v3.x.x#607]
Hola, hay alguna forma de poder agregar que los recursos se vea en tiempo real sin la necesidad de recargar la pagina ?

**Comment by LucasKovacs** [comment]
Recuerdo que algo habia en el foro https://forum.xgproyect.org/ o quizas busca en https://github.com/XGProyect/XG-Proyect-v3.x.x/issues
