### ISSUE TITLE
[Beta8] After installed error

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#63]
No problem during installation. When I entered the admin control panel installation After I met with this error
first trial
![db](https://cloud.githubusercontent.com/assets/16218107/13161658/d09d6ef4-d6a7-11e5-92c3-fd8d25cd9c9f.png)

second trial
![db2](https://cloud.githubusercontent.com/assets/16218107/13161668/eb8aec5a-d6a7-11e5-8bc9-ca05e7af263d.png)

**Comment by XGProyect** [comment]
You have to clean your DB before you make a new installation

**Comment by BeReal86** [comment]
I did a clean install no problem. something that in the long prefix that causes problems. I'm trying to use less. Providing a clean install. The've limited it needs

**Comment by XGProyect** [comment]
MySQL tables support 60 chars long, that one is half shorter. If you pay attention to the error it says that the table already exists. I'm closing this for now.
