### ISSUE TITLE
[Beta8] Delete Moon (physical)

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#67]
We delete physically. As shown in the first image. then we want to add a new month, but gave a letter as follows.

this is a error?

![dlt-moon](https://cloud.githubusercontent.com/assets/16218107/13162391/60c2a314-d6ad-11e5-9fad-ffb5a091e3a1.png)

We physically remove the picture but still present a month. this error?

**Comment by XGProyect** [comment]
Not yet implemented

**Comment by XGProyect** [comment]
The option to physically delete moons or/and planets is disabled for now. It will be implemented on future versions.
