### ISSUE TITLE
[Beta8] Alliance Accept

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#68]
When the application is accepted, the alliance gives the following error
![iti](https://cloud.githubusercontent.com/assets/16218107/13162847/6c7846f2-d6b0-11e5-984a-9cd9c3689199.png)

This error code later

Notice: Undefined offset: 3 in /home/eskiog/public_html/area51/application/controllers/game/alliance.php on line 1105

**Comment by XGProyect** [comment]
This one only happened with languages that uses specials chars, ex.: "Founder's"
