### ISSUE TITLE
Create Moon

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#7]
Moon stands out when I want to create this error. I'll fill in the required information section opens, but the Moon can not be created

Notice: Undefined index: id in /home/eskiog/public_html/beta6/application/controllers/adm/maker.php on line 546

Notice: Undefined index: id in /home/eskiog/public_html/beta6/application/controllers/adm/maker.php on line 546

**Comment by XGProyect** [comment]
Fixed!
