### ISSUE TITLE
[Beta8] Delete Messages

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#71]
activate the feature commander of messages are not deleted.

commander feature passive when messages are deleted.

**Comment by XGProyect** [comment]
@BeReal86 Can you explain better please?

**Comment by BeReal86** [comment]
normally is there any problem with deleting posts. Commander feature is enabled when the message box is changing. so sift through the posts. Then any function does not work. what message in the display you can delete a message, it doesn't work.

in the first picture, no problem, everything works fine.
![messages](https://cloud.githubusercontent.com/assets/16218107/13527536/49cd9f9e-e218-11e5-9cf5-9307ebecab9d.png)


in the second picture doesn't work. active commander
![messages2](https://cloud.githubusercontent.com/assets/16218107/13527546/6507e314-e218-11e5-93f4-3de2b7ae469b.png)
