### ISSUE TITLE
[Beta8] DB Error some

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#73]
I think that these errors in the prefix table.  A shorter prefix, that's no problem. The longer occur several problems

![db](https://cloud.githubusercontent.com/assets/16218107/13175868/25107602-d716-11e5-80a5-87a47f59627c.png)

![db2](https://cloud.githubusercontent.com/assets/16218107/13175870/29d8dec2-d716-11e5-8258-cbac22257e0d.png)

[ErrorLog.txt](https://github.com/XGProyect/XG-Proyect-v3.x.x/files/137962/ErrorLog.txt)

**Comment by XGProyect** [comment]
Duplicate #63
