### ISSUE TITLE
[Beta8] Consumption

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#75]
While other colonies to deploy a mission to a planet, the amount of fuel needed to leave the planet to the half.

I will try to give example

There are fleet from the planet A. I will send deployment planet B.
Deuterium consumption: 10.000

Fleet planet B, with half of this amount of time in the 5,000 deuterium u leave the planet.

**before**
deuterium content in the planet B  / Deut: 20.000

**after**
The amount of deuterium in the fleet after the planet B  / Deut: 25.000

**Comment by XGProyect** [comment]
@BeReal86 I think this one is not a bug. Because if the amount before sending the fleet is 10000 (this amount is for back and forth), if is a deploy mission only half is going to be spent.

**Comment by BeReal86** [comment]
@XGProyect  I don't know how to explain it now. ogame the original situation is as follows. deploy the fleet from A planet to planet B as you're sending.

When sending the required fuel amount as much as 10,000 fleet deu. It takes. The fleet deployment task B resides on the planet when I landed, half of this fuel is refunded.

If I recall. B fleet to the planet on the way, called back, then consumes all of the fuel.
