### ISSUE TITLE
[Beta8] Create satellite lunar in battle

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#76]
After the war occurred a month but does not appear in the galaxy and players.

%s [%d:%d:%d] ! The report did not make sense to them. 
an error if necessary. scroll is required to report to the pop-up window. To manage page down.

sometimes months can not be destroyed

![lunar](https://cloud.githubusercontent.com/assets/16218107/13200650/6c24fe56-d85a-11e5-94e5-24321d0e9d5a.png)

**Comment by XGProyect** [comment]
Closed for now.
