### ISSUE TITLE
[Beta8] Battle and Destroy Report

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#77]
battle reporter first time in running smoothly. We can not come to report after a certain time, stands out a white sheet. 
If automatic deletion is not a good method should be a period of time. It has become unreadable in 2 days

![battle](https://cloud.githubusercontent.com/assets/16218107/13224454/53f439b8-d991-11e5-802d-66dade40cb53.png)

lunar destruction report does not work at all.

![destruccion](https://cloud.githubusercontent.com/assets/16218107/13224457/5c7332b0-d991-11e5-8c0d-543d51272434.png)

**Comment by XGProyect** [comment]
Duplicated error #85

**Comment by BeReal86** [comment]
@XGProyect  ok i deleted now
