### ISSUE TITLE
Planet Edit Buildings

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#8]
I get such a error while editing

Warning: mail() has been disabled for security reasons in /home/eskiog/public_html/beta6/application/libraries/Debug_Lib.php on line 112

**Comment by BeReal86** [comment]
![1-1](https://cloud.githubusercontent.com/assets/16218107/12704999/15b2c49e-c870-11e5-893f-d23c8928a2a1.png)

**Comment by athk** [comment]
Hard to see where the actual issue on the queries is. Could you apply [this patch](https://github.com/athk/XG-Proyect-v3.x.x/commit/2e360a94b9e976fe3e556e4ff7e8c1d901475e39) and screenshot it again?

**Comment by BeReal86** [comment]
Last try for edipt planet

 XG Proyect

500. That’s an error.

The requested URL throw an error. Contact the game Administrator. That’s all we know. 

![11](https://cloud.githubusercontent.com/assets/16218107/12735797/59b76d50-c953-11e5-9e1a-05be9ebcf64e.png)

**Comment by XGProyect** [comment]
Fixed
