### ISSUE TITLE
[Beta9] Research

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#86]
I began construction to upgrade the level of espionage technology the main planet.
then switch to the colony challenge is to get out of this error.

 Notice: Undefined index: id in /home/xtremega/public_html/xgproyect.org/microsites/server/application/controllers/game/research.php on line 139

![research](https://cloud.githubusercontent.com/assets/16218107/13516016/e0b2fe72-e1be-11e5-890d-75eb61e8ee54.png)

**Comment by XGProyect** [comment]
Fixed
