### ISSUE TITLE
Error de producción

### ISSUE THREAD

**Issue by Mallard1995** [XGProyect/XG-Proyect-v3.x.x#93]
Hola, creo que he encontrado un error. Se trata de un error de producción de los recursos. Según la página de recursos y la base de datos, la mina de materia oscura me tendría que producir 90 unidades de metal en una hora, pero me produce muchas más. Lo mismo con la de cristal y deuterio.

Att Mallard.

**Comment by BeReal86** [comment]
Gracias por sus comentarios. Comprobado y como resultado.
Metal = 90
crystal= 45

 Metal   Crystal  
 8.625   4.562
Después de 15 minutos,
8.670     4.585
diferencia
   45          23

producción por hora por diferencia
Metal = 180
Crystal = 92

**Comment by Mallard1995** [comment]
Bueno, lo he vuelto a probar y si... error mio. Funciona.
