### ISSUE TITLE
No funciona geologo

### ISSUE THREAD

**Issue by Mallard1995** [XGProyect/XG-Proyect-v3.x.x#94]
He estado probando el geologo, y no funciona. Es decir, si lo activas no produce ese 10% de producción extra.

Att Mallard.

**Comment by BeReal86** [comment]
![geolog-off](https://cloud.githubusercontent.com/assets/16218107/13964391/30cb3ef8-f072-11e5-99a0-f17a126de3ba.png)
producción horaria
Metal = 332
Crystal = 128

![geolog-on](https://cloud.githubusercontent.com/assets/16218107/13964398/363308da-f072-11e5-8a36-75e3606ae195.png)

producción horaria
Metal = 356
Crystal = 132

**Comment by Mallard1995** [comment]
vale, tienes razón. Yo lo estaba mirando a nivel 0 jeje. Funciona perfecto al parecer (y)

**Comment by BeReal86** [comment]
Sí, el propósito de mostrar que el original. El geólogo aumenta la producción de metal, cristal y deuterio en un 10% en cada planeta, pero no afecta el ingreso base.

Gracias por su colaboración.

Closed issues not a bug
