### ISSUE TITLE
Error al borrar el mensaje

### ISSUE THREAD

**Issue by djlolito** [XGProyect/XG-Proyect-v3.x.x#96]
Si mandas un mensaje global, le llega al usuario todo eso bien, pero no puedes borrarlo. Lo he marcado darle a borrar seleccionados y a ok pero nada no deja.

**Comment by BeReal86** [comment]
Hola, Gracias por sus comentarios con prioridad.
El problema con eliminar sólo los mensajes del comandante, cuando la sección está activada, se compone de. el comandante de todos los mensajes que usted no está activo, puede ser eliminado.

véase también el problema actual se han identificado y se ha escrito mucho antes.

https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/71

issue closed.

**Comment by djlolito** [comment]
En ningun momento dije comandante. He dicho mensaje global. Lease bien que no dije nada de comandante activo.

**Comment by BeReal86** [comment]
Quiero explicar a usted el error de borrar el mensaje que se producen en los horarios indicados. la beta 10 como usted ha dicho, un error no existe he comprobado.

**Comment by XGProyect** [comment]
No puedo reproducir el error.
