### ISSUE TITLE
buildings

### ISSUE THREAD

**Issue by calzon11** [XGProyect/XG-Proyect-v3.x.x#98]
Notice: Undefined offset: 2 in /home2/boro/public_html/xxxxxxxx/application/controllers/game/buildings.php on line 382

Warning: Cannot modify header information - headers already sent by (output started at /home2/boro/public_html/xxxxxxxx/application/controllers/game/buildings.php:382) in /home2/boro/public_html/xxxxxxxx/application/controllers/game/buildings.php on line 211

**Comment by BeReal86** [comment]
Hello @calzon11 

thank you for your feedback. Can you tell this error is more descriptive. I could not verify this error.

**Comment by FGServers** [comment]
En que momento te pasa @calzon11 estoy tratando de replicar el error y no puedo replicarlo

**Comment by calzon11** [comment]
www.uniblazar.com le pusen rates altos 10,000 velocidad del juego, y me puse a contruir minas de metal, crystal a lo loco, y de repente aparecio el error. Intentare replicarlo otra vez

**Comment by BeReal86** [comment]
Hola a todos,

Hice varios experimentos. No he encontrado ningún problema.


not a bug closed.

**Comment by FGServers** [comment]
Puede ser producto de las velocidades voy a revisarlo con altas velocidades
