### ISSUE TITLE
[Future Improvement] Plasma Technology Factor resource on factor production

### ISSUE THREAD

**Issue by FGServers** [XGProyect/XG-Proyect-v3.x.x#99]
Hello lucky, not here but if you want to give an idea for future versions it is producion plasma technology resources, Researching Plasma Technology is useful for Increasing the Present production of Both Crystal and Metal. Metal production Increases by 1% and crystal production by 0.66% per level of Plasma Technology if I can make the public in XGP You decide if you put it or not.
![sin titulo](https://cloud.githubusercontent.com/assets/2124810/14624096/dab2c526-05ad-11e6-8afd-0a17478feeb8.png)

**Comment by BeReal86** [comment]
Hello @FGServers 
Thanks for the information and explanations. it's a good idea :)

**Comment by XGProyect** [comment]
Included into milestone v3.5.0

**Comment by FGServers** [comment]
la formula seria algo asi 
((0.01 * plasmaTechLevel) * 30.0 * techLevel * Math.pow(1.1, techLevel)) * universeSpeedFactor

Pero no puedo integrarla al core

**Comment by BeReal86** [comment]
Thanks for help
